<a href="https://colab.research.google.com/github/SpencerNGARI/Kenya_Household_Credit_Risk/blob/main/exploratory_development.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import os

file_path = "/content/2024_Finaccess_Publicdata.dta"

size = os.path.getsize(file_path)

print(f"Bytes: {size:,}")
print(f"MB: {size / (1024**2):.2f}")
print(f"GB: {size / (1024**3):.4f}")

Bytes: 159,531,918
MB: 152.14
GB: 0.1486

In [34]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.6-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.13/dist-packages (from pyreadstat) (2.26.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pyreadstat) (2.1.3)
Downloading pyreadstat-1.3.6-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 30.3 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.6

In [35]:
import pyreadstat

file_path = "/content/2024_Finaccess_Publicdata.dta"

df, meta = pyreadstat.read_dta(
    file_path,
    apply_value_formats=False
)

print("Dataset loaded successfully!")
print("Rows:", f"{df.shape[0]:,}")
print("Columns:", f"{df.shape[1]:,}")

print("\nFirst 30 variables:")
for var in df.columns[:30]:
    print(var)

Dataset loaded successfully!
Rows: 20,871
Columns: 3,816

First 30 variables:
interview__key
interview__id
county
A07
A08
A10
Interview_Status
A9i
Z1
A13
A12ii_length
A14iv
A14vi
FHH_Spouse
A15a
A15i
A18
A19
A14i
A14ii
A14iii
A14iv_e
A14vii
A14_slept
RESPONDENT
Sex
Age
A16
NHM
A20

In [16]:
import os
import pandas as pd

file_path = "/content/2024_Finaccess_Publicdata.dta"

# Check that the file actually exists
if not os.path.exists(file_path):
    print("File was not found.")
    print("Files currently in /content:")
    print(os.listdir("/content"))
else:
    print("File found!")
    print(f"File size: {os.path.getsize(file_path) / (1024**3):.2f} GB")

    # Load without converting Stata labels to pandas categories
    df = pd.read_stata(
        file_path,
        convert_categoricals=False
    )

    print("\nDataset loaded successfully!")
    print(f"Rows:    {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]:,}")

File found!
File size: 0.15 GB

Dataset loaded successfully!
Rows:    20,871
Columns: 3,816

In [17]:
import os

file_path = "/content/2024_Finaccess_Publicdata.dta"

file_exists = os.path.exists(file_path)
print("File exists:", file_exists)

if file_exists:
    print("File size:", os.path.getsize(file_path) / (1024**3), "GB")
else:
    print("File size: N/A (File does not exist. Please upload or check the path.)")

File exists: True
File size: 0.1485756766051054 GB

In [18]:
# ------------------------------------------------------------
# 2. LOAD THE DATASET
# ------------------------------------------------------------

print("\nLoading dataset...")

df = pd.read_stata(
    file_path,
    convert_categoricals=False
)

print("Dataset loaded successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

Loading dataset...
Dataset loaded successfully.
Rows: 20,871
Columns: 3,816

In [19]:
# ------------------------------------------------------------
# 3. BASIC DATASET INFORMATION
# ------------------------------------------------------------

print("\n" + "="*60)
print("1. BASIC DATASET INFORMATION")
print("="*60)

rows, columns = df.shape

print(f"Number of rows:    {rows:,}")
print(f"Number of columns: {columns:,}")

print("\nMemory usage:")
print(f"{df.memory_usage(deep=True).sum() / (1024**2):.2f} MB")

============================================================
1. BASIC DATASET INFORMATION
============================================================
Number of rows:    20,871
Number of columns: 3,816

Memory usage:
787.37 MB

In [20]:
# ------------------------------------------------------------
# 4. FIRST FEW ROWS
# ------------------------------------------------------------

print("\n" + "="*60)
print("2. FIRST 5 ROWS")
print("="*60)

display(df.head())

============================================================
2. FIRST 5 ROWS
============================================================

,interview__key,interview__id,county,A07,A08,A10,Interview_Status,A9i,Z1,A13,...,sacco_redress,mobilemoney_redress,mobilebank_redress,not_registered_mmoney_24,using_someone_acc,insurance_including_NHIF_use,All_Insurance_excluding_NHIF_use,PWD,Latitude,Longitude
0,21-61-43-44,00005e63e7424aa19e63adb071955233,7,225,2,1,1,1,1,1,...,NaN,NaN,NaN,0,NaN,3,3,0,-0.435423,39.636586
1,87-78-54-60,000718d26f5942998522033a66594b4c,7,223,2,3,1,1,1,1,...,NaN,NaN,NaN,0,NaN,3,3,0,0.058794,40.305006
2,32-71-19-84,0008721681d2468aa1ef456bba4475dc,40,1514,2,3,1,1,1,2,...,NaN,NaN,NaN,0,NaN,3,3,0,0.636836,34.277390
3,48-18-78-99,00099e961d49470585c1a7f49fa3b7fb,22,796,2,3,1,1,1,1,...,NaN,NaN,NaN,0,NaN,3,3,0,-1.251917,36.719076
4,50-82-98-89,000bb72e959b4dd48443da902c01e920,21,763,2,16,1,1,1,2,...,NaN,NaN,NaN,0,1.0,3,3,0,-0.795820,37.131085

In [21]:
# 5. VARIABLE NAMES AND DATA TYPES
# ------------------------------------------------------------

print("\n" + "="*60)
print("3. VARIABLES AND DATA TYPES")
print("="*60)

variable_info = pd.DataFrame({
    "Variable": df.columns,
    "Data_Type": df.dtypes.astype(str),
    "Missing_Count": df.isna().sum().values,
    "Missing_Percent": (df.isna().mean().values * 100).round(2),
    "Unique_Values": df.nunique(dropna=True).values
})

display(variable_info.head(50))

============================================================
3. VARIABLES AND DATA TYPES
============================================================

,Variable,Data_Type,Missing_Count,Missing_Percent,Unique_Values
interview__key,interview__key,object,0,0.00,20871
interview__id,interview__id,object,0,0.00,20871
county,county,int8,0,0.00,47
A07,A07,int16,0,0.00,1849
A08,A08,int8,0,0.00,2
A10,A10,int16,0,0.00,84
Interview_Status,Interview_Status,int8,0,0.00,1
A9i,A9i,int8,0,0.00,1
Z1,Z1,int8,0,0.00,1
A13,A13,int8,0,0.00,2
A12ii_length,A12ii_length,int8,0,0.00,20
A14iv,A14iv,int8,0,0.00,13
A14vi,A14vi,int8,0,0.00,16
FHH_Spouse,FHH_Spouse,int8,0,0.00,2
A15a,A15a,int8,0,0.00,4
A15i,A15i,object,0,0.00,170
A18,A18,int16,0,0.00,90
A19,A19,int8,0,0.00,8
A14i,A14i,int16,0,0.00,91
A14ii,A14ii,int8,0,0.00,2
A14iii,A14iii,int8,0,0.00,8
A14iv_e,A14iv_e,int8,0,0.00,8
A14vii,A14vii,float64,16298,78.09,7
A14_slept,A14_slept,int8,0,0.00,1
RESPONDENT,RESPONDENT,int8,0,0.00,2
Sex,Sex,int8,0,0.00,2
Age,Age,int8,0,0.00,6
A16,A16,int8,0,0.00,1
NHM,NHM,int8,0,0.00,20
A20,A20,int8,0,0.00,13
A20i,A20i,object,0,0.00,16
A21,A21,int8,0,0.00,6
A22i,A22i,float64,4,0.02,20
A22ii,A22ii,float64,4801,23.00,9
A22iii,A22iii,float64,6797,32.57,16
A23,A23,int8,0,0.00,3
A24i,A24i,float64,2,0.01,4
A24ii,A24ii,float64,2,0.01,4
A24iii,A24iii,float64,1,0.00,4
A24iv,A24iv,int8,0,0.00,4
A24v,A24v,float64,2,0.01,4
A24vi,A24vi,float64,7,0.03,4
B1A,B1A,int8,0,0.00,9
B1Bi,B1Bi,int8,0,0.00,13
B1Bii,B1Bii,int8,0,0.00,13
B1C1,B1C1,int8,0,0.00,5
B1C2,B1C2,int8,0,0.00,5
B1C3,B1C3,int8,0,0.00,5
B1C4,B1C4,int8,0,0.00,5
B1Di,B1Di,int8,0,0.00,4

In [22]:
# ------------------------------------------------------------
# 6. COMPLETE VARIABLE LIST
# ------------------------------------------------------------

print("\n" + "="*60)
print("4. COMPLETE VARIABLE LIST")
print("="*60)

for i, column in enumerate(df.columns, start=1):
    print(f"{i:4}. {column}")

============================================================
4. COMPLETE VARIABLE LIST
============================================================
   1. interview__key
   2. interview__id
   3. county
   4. A07
   5. A08
   6. A10
   7. Interview_Status
   8. A9i
   9. Z1
  10. A13
  11. A12ii_length
  12. A14iv
  13. A14vi
  14. FHH_Spouse
  15. A15a
  16. A15i
  17. A18
  18. A19
  19. A14i
  20. A14ii
  21. A14iii
  22. A14iv_e
  23. A14vii
  24. A14_slept
  25. RESPONDENT
  26. Sex
  27. Age
  28. A16
  29. NHM
  30. A20
  31. A20i
  32. A21
  33. A22i
  34. A22ii
  35. A22iii
  36. A23
  37. A24i
  38. A24ii
  39. A24iii
  40. A24iv
  41. A24v
  42. A24vi
  43. B1A
  44. B1Bi
  45. B1Bii
  46. B1C1
  47. B1C2
  48. B1C3
  49. B1C4
  50. B1Di
  51. B1Dii
  52. B1Diii
  53. B1E1
  54. B1E2
  55. B1E3
  56. B1E4
  57. B1F2
  58. B1F1
  59. B1FI
  60. B1FIOTHER
  61. B1G
  62. B1H
  63. B1Ha
  64. B1Hi
  65. B1Hii
  66. B1Ii
  67. B1Iii
  68. B1J
  69. B1K
  70. B1L__1
  71. B1L__2
  72. B1L__3
  73. B1L__4
  74. B1L__5
  75. B1L__6
  76. B1M__1
  77. B1M__2
  78. B1M__3
  79. B1M__4
  80. B1N1
  81. B1N2
  82. B1O
  83. B1P
  84. secB1
  85. CountFINANCIAL_HEALTH
  86. B2A
  87. B2Ai
  88. B2B
  89. B2Ci
  90. B2Cii
  91. B2Cii_Other
  92. B2D
  93. B2Ei
  94. B2Eii
  95. B2Eiii
  96. B2F
  97. secFinancial_Awareness
  98. B3A__1
  99. B3A__2
 100. B3A__3
 101. B3A__4
 102. B3A__5
 103. B3A__6
 104. B3A__7
 105. B3A__8
 106. B3A__9
 107. B3A__10
 108. B3A__11
 109. B3A__98
 110. B3A__99
 111. B3Ai
 112. B3B
 113. B3Bi
 114. B3C
 115. B3Ci
 116. B3Cii_1
 117. B3Cii_2
 118. B3Cii_3
 119. B3Cii_4
 120. B3D__1_1
 121. B3D__2_1
 122. B3D__3_1
 123. B3D__4_1
 124. B3D__5_1
 125. B3D__6_1
 126. B3D__7_1
 127. B3D__8_1
 128. B3D__9_1
 129. B3D__10_1
 130. B3D__11_1
 131. B3D__98_1
 132. B3D__99_1
 133. B3Di_1
 134. B3E_1
 135. B3D__1_2
 136. B3D__2_2
 137. B3D__3_2
 138. B3D__4_2
 139. B3D__5_2
 140. B3D__6_2
 141. B3D__7_2
 142. B3D__8_2
 143. B3D__9_2
 144. B3D__10_2
 145. B3D__11_2
 146. B3D__98_2
 147. B3D__99_2
 148. B3Di_2
 149. B3E_2
 150. B3D__1_3
 151. B3D__2_3
 152. B3D__3_3
 153. B3D__4_3
 154. B3D__5_3
 155. B3D__6_3
 156. B3D__7_3
 157. B3D__8_3
 158. B3D__9_3
 159. B3D__10_3
 160. B3D__11_3
 161. B3D__98_3
 162. B3D__99_3
 163. B3Di_3
 164. B3E_3
 165. B3D__1_4
 166. B3D__2_4
 167. B3D__3_4
 168. B3D__4_4
 169. B3D__5_4
 170. B3D__6_4
 171. B3D__7_4
 172. B3D__8_4
 173. B3D__9_4
 174. B3D__10_4
 175. B3D__11_4
 176. B3D__98_4
 177. B3D__99_4
 178. B3Di_4
 179. B3E_4
 180. B3D__1_5
 181. B3D__2_5
 182. B3D__3_5
 183. B3D__4_5
 184. B3D__5_5
 185. B3D__6_5
 186. B3D__7_5
 187. B3D__8_5
 188. B3D__9_5
 189. B3D__10_5
 190. B3D__11_5
 191. B3D__98_5
 192. B3D__99_5
 193. B3Di_5
 194. B3E_5
 195. B3D__1_6
 196. B3D__2_6
 197. B3D__3_6
 198. B3D__4_6
 199. B3D__5_6
 200. B3D__6_6
 201. B3D__7_6
 202. B3D__8_6
 203. B3D__9_6
 204. B3D__10_6
 205. B3D__11_6
 206. B3D__98_6
 207. B3D__99_6
 208. B3Di_6
 209. B3E_6
 210. B3D__1_7
 211. B3D__2_7
 212. B3D__3_7
 213. B3D__4_7
 214. B3D__5_7
 215. B3D__6_7
 216. B3D__7_7
 217. B3D__8_7
 218. B3D__9_7
 219. B3D__10_7
 220. B3D__11_7
 221. B3D__98_7
 222. B3D__99_7
 223. B3Di_7
 224. B3E_7
 225. B3D__1_8
 226. B3D__2_8
 227. B3D__3_8
 228. B3D__4_8
 229. B3D__5_8
 230. B3D__6_8
 231. B3D__7_8
 232. B3D__8_8
 233. B3D__9_8
 234. B3D__10_8
 235. B3D__11_8
 236. B3D__98_8
 237. B3D__99_8
 238. B3Di_8
 239. B3E_8
 240. B3D__1_9
 241. B3D__2_9
 242. B3D__3_9
 243. B3D__4_9
 244. B3D__5_9
 245. B3D__6_9
 246. B3D__7_9
 247. B3D__8_9
 248. B3D__9_9
 249. B3D__10_9
 250. B3D__11_9
 251. B3D__98_9
 252. B3D__99_9
 253. B3Di_9
 254. B3E_9
 255. B3D__1_10
 256. B3D__2_10
 257. B3D__3_10
 258. B3D__4_10
 259. B3D__5_10
 260. B3D__6_10
 261. B3D__7_10
 262. B3D__8_10
 263. B3D__9_10
 264. B3D__10_10
 265. B3D__11_10
 266. B3D__98_10
 267. B3D__99_10
 268. B3Di_10
 269. B3E_10
 270. B3F1
 271. B3F2
 272. B3G
 273. B3H1
 274. B3H2
 275. B3H3
 276. B3H4
 277. B3H5
 278. B3H5i
 279. B3H6
 280. B3H6i
 281. B3Ii
 282. B3Iii
 283. B3Iiii
 284. IsSectionAnsweredLivelihood
 285. CountLivelihood
 286. C1_10
 287. C1_11
 288. C1_12
 289. C1_12ai_CHK__0
 290. C1_12ai_CHK__1
 291. C1_12ai_CHK__2
 292. C1_12ai_CHK__3
 293. C1_12ai_CHK__4
 294. C1_12ai_CHK__5
 295. C1_12ai_CHK__6
 296. C1_12ai_CHK__7
 297. C1_12ai_CHK__8
 298. C1_12ai_CHK__9
 299. C1_12ai_CHK__10
 300. C1_12ai_CHK__11
 301. C1_12ai_CHK__12
 302. C1_12ai_CHK__13
 303. C1_12ai_CHK__14
 304. C1_12ai_CHK__15
 305. C1_12ai_CHK__16
 306. C1_12ai_CHK__17
 307. C1_12ai_CHK__18
 308. C1_12ai_CHK__19
 309. C1_12ai_CHK__20
 310. C1_12ai_CHK__21
 311. C1_12ai_CHK__22
 312. C1_12ai_CHK__23
 313. C1_12ai_CHK__24
 314. C1_12ai_CHK__25
 315. C1_12ai_CHK__26
 316. C1_12ai_CHK__27
 317. C1_12ai_CHK__28
 318. C1_12ai_CHK__29
 319. C1_12ai_CHK__30
 320. C1_12ai_CHK__31
 321. C1_12ai_CHK__32
 322. C1_12ai_CHK__33
 323. C1_12ai_CHK__34
 324. C1_12ai_CHK__35
 325. C1_12ai_CHK__36
 326. C1_12ai_CHK__37
 327. C1_12ai_CHK__38
 328. C1_12ai_CHK__39
 329. C1_12ai_CHK__40
 330. C1_12ai_CHK__41
 331. C1_12ai_CHK__42
 332. C1_12ai_CHK__43
 333. C1_12ai_CHK__44
 334. C1_12ai_CHK__45
 335. C1_12ai_CHK__46
 336. C1_12ai_CHK__47
 337. C1_12ai_CHK__48
 338. C1_12ai_CHK__49
 339. C1_12ai_CHK__50
 340. C1_12ai_CHK__51
 341. C1_12ai_CHK__52
 342. C1_12ai_CHK__53
 343. C1_12a
 344. C1_12b
 345. C1_1a
 346. C1_1b
 347. C1_2
 348. C1_3
 349. C1_4
 350. C1_5
 351. C1_6
 352. C1_7
 353. C1_8
 354. C1_9
 355. C1_13a
 356. C1_13b
 357. C1_13c
 358. C1_14
 359. C1_15
 360. C1_16
 361. C1_17
 362. C1_18
 363. C1_19
 364. C1_20
 365. C1_21
 366. C1_22
 367. C1_23
 368. C1_24
 369. C1_25
 370. C1_26
 371. C1_27
 372. C1_28
 373. C1_29
 374. C1_30
 375. C1_31
 376. C1_32
 377. C1_33
 378. C1_34
 379. C1_35
 380. C1_36
 381. C1_37
 382. C1_38
 383. C1_39
 384. C1_40
 385. C1_41
 386. C1_42
 387. CountSECC7
 388. C1_43
 389. C2_15
 390. C2_16
 391. C2_19
 392. C2_23
 393. C3
 394. C3i
 395. C4
 396. C4i
 397. D1A__1
 398. D1A__2
 399. D1A__99
 400. D1Ai__1
 401. D1Ai__2
 402. D1Ai__3
 403. D1Ai__4
 404. D1Ai__5
 405. D1Ai__6
 406. D1Ai__7
 407. D1Ai__8
 408. D1Ai__98
 409. D1Ai__99
 410. D1B__1
 411. D1B__2
 412. D1B__3
 413. D1B__4
 414. D1B__5
 415. D1B__6
 416. D1B__7
 417. D1B__8
 418. D1B__9
 419. D1B__98
 420. D1B__99
 421. D1Bi
 422. D1C
 423. D1Ci
 424. D1D
 425. D1E
 426. D1Fi
 427. D1Fii
 428. D1G
 429. D1H__1
 430. D1H__2
 431. D1H__3
 432. D1H__4
 433. D1H__5
 434. D1I
 435. D1J
 436. D1K__1
 437. D1K__2
 438. D1K__3
 439. D1K__4
 440. D1K__5
 441. D1K__6
 442. D1K__7
 443. D1K__98
 444. D1K__99
 445. D1L
 446. D1Ma
 447. D1Mb
 448. D1Mc
 449. D1Md
 450. D1Me
 451. D1Mf
 452. D1
 453. D2__1
 454. D2__2
 455. D2__3
 456. D2__4
 457. D2__5
 458. D2__6
 459. D2__7
 460. D2__98
 461. D2__99
 462. D2i
 463. D3__1
 464. D3__2
 465. D3__3
 466. D3__4
 467. D3__5
 468. D3__6
 469. D3__96
 470. D3i
 471. D4__1
 472. D4__2
 473. D4__3
 474. D4__4
 475. D4__5
 476. D4__6
 477. D4__7
 478. D4__8
 479. D4__9
 480. D5
 481. D5i
 482. D6
 483. D6i
 484. D7
 485. D7_other_specify
 486. D8__1
 487. D8__2
 488. D8__3
 489. D8__4
 490. D8__5
 491. D9__1
 492. D9__2
 493. D9__3
 494. D9__4
 495. D9__96
 496. D10
 497. D11__1
 498. D11__3
 499. D11__4
 500. D11__5
 501. D11__6
 502. D11__7
 503. D11__8
 504. D11__98
 505. D11__99
 506. D12
 507. D13_1
 508. D13_2
 509. D13_3
 510. D13_4
 511. D13_5
 512. D13_6
 513. D13_7
 514. E1
 515. E2__1
 516. E2__2
 517. E2__3
 518. E2__4
 519. E2__5
 520. E2__6
 521. E2__7
 522. E2__8
 523. E2__9
 524. E2__10
 525. E2__11
 526. E2__12
 527. E2__13
 528. E2__14
 529. E2__15
 530. E3__15
 531. E3__16
 532. E3__17
 533. E3__18
 534. E2__96
 535. E2__98
 536. E2__99
 537. E2_Other
 538. E3__1
 539. E3__2
 540. E3__3
 541. E3__4
 542. E3__5
 543. E3__6
 544. E3__7
 545. E3__8
 546. E3__9
 547. E3__10
 548. E3__11
 549. E3__12
 550. E3__13
 551. E3__14
 552. E3__96
 553. E3__98
 554. E3__99
 555. E3_Other
 556. E4__1
 557. E4__2
 558. E4__3
 559. E4__4
 560. E4__5
 561. E4__6
 562. E4__7
 563. E4__8
 564. E4__9
 565. E4__96
 566. E4__98
 567. E4__99
 568. E4_Other_Specify
 569. E5__1
 570. E5__2
 571. E5__3
 572. E5__4
 573. E5__5
 574. E5__6
 575. E5__7
 576. E5__96
 577. E5__98
 578. E5__99
 579. E5_Others_Specify
 580. E1iA
 581. E1iiA
 582. E1iiiA
 583. E1iiiA_Other
 584. E1ivA
 585. E1ivA_Other
 586. E1vA
 587. E1vA_Other
 588. E1viA
 589. E1viA_Other
 590. E1viiA
 591. E1viiiA
 592. E1ixA
 593. E1xA
 594. E1xiA
 595. E1iB
 596. E1iiB
 597. E1iiiB
 598. E1iiiB_Other
 599. E1ivB
 600. E1ivB_Other
 601. E1vB
 602. E1vB_Other
 603. E1viB
 604. E1viB_Other
 605. E1viiB
 606. E1viiiB
 607. E1ixB
 608. E1xB
 609. E1xiB
 610. E1iC
 611. E1iiC
 612. E1iiiC
 613. E1iiiC_Other
 614. E1ivC
 615. E1ivC_Other
 616. E1vC
 617. E1vC_Other
 618. E1viC
 619. E1viC_Other
 620. E1viiC
 621. E1viiiC
 622. E1ixC
 623. E1xC
 624. E1xiC
 625. E1iD
 626. E1iiiD
 627. E1iiiD_Other
 628. E1vD
 629. E1vD_Other
 630. E1viD
 631. E1viD_Other
 632. E1viiD
 633. E1viiiD
 634. E1ixD
 635. E1xD
 636. E1iE
 637. E1iiE
 638. E1iiiE
 639. E1iiiE_Other
 640. E1vE
 641. E1vE_Other
 642. E1viiE
 643. E1viiiE
 644. E1ixE
 645. E1xE
 646. E1xiE
 647. E1iF
 648. E1iiF
 649. E1iiiF
 650. E1iiiF_Other
 651. E1viiF
 652. E1viiiF
 653. E1ixF
 654. E1xiF
 655. E1iG
 656. E1iiG
 657. E1iiiG
 658. E1iiiG_Other
 659. E1ivG
 660. E1ivG_Other
 661. E1vG
 662. E1vG_Other
 663. E1viG
 664. E1viG_Other
 665. E1viiG
 666. E1viiiG
 667. E1ixG
 668. E1xG
 669. E1xiG
 670. E1iH
 671. E1iiH
 672. E1iiiH
 673. E1iiiH_Other
 674. E1ivH
 675. E1ivH_Other
 676. E1vH
 677. E1vH_Other
 678. E1viH
 679. E1viH_Other
 680. E1viiH
 681. E1viiiH
 682. E1ixH
 683. E1xH
 684. E1xiH
 685. E1iI
 686. E1iiI
 687. E1iiiI
 688. E1iiiI_Other
 689. E1vI
 690. E1vI_Other
 691. E1viI
 692. E1viI_Other
 693. E1viiI
 694. E1viiiI
 695. E1ixI
 696. E1xI
 697. E1xiI
 698. E1iJ
 699. E1iiJ
 700. E1iiiJ
 701. E1iiiJ_Other
 702. E1ivJ
 703. E1ivJ_Other
 704. E1vJ
 705. E1vJ_Other
 706. E1viJ
 707. E1viJ_Other
 708. E1viiJ
 709. E1viiiJ
 710. E1ixJ
 711. E1xJ
 712. E1xiJ
 713. E1iK
 714. E1iiK
 715. E1iiiK
 716. E1iiiK_Other
 717. E1ivK
 718. E1ivK_Other
 719. E1vK
 720. E1vK_Other
 721. E1viK
 722. E1viK_Other
 723. E1viiK
 724. E1viiiK
 725. E1ixK
 726. E1xK
 727. E1xiK
 728. E1iL
 729. E1iiL
 730. E1iiiL
 731. E1iiiL_Other
 732. E1ivL
 733. E1ivL_Other
 734. E1vL
 735. E1vL_Other
 736. E1viL
 737. E1viL_Other
 738. E1viiL
 739. E1viiiL
 740. E1ixL
 741. E1xL
 742. E1xiL
 743. E1iM
 744. E1iiM
 745. E1iiiM
 746. E1iiiM_Other
 747. E1vM
 748. E1vM_Other
 749. E1viM
 750. E1viM_Other
 751. E1viiM
 752. E1viiiM
 753. E1ixM
 754. E1xM
 755. E1xiM
 756. E1iN
 757. E1iiN
 758. E1iiiN
 759. E1iiiN_Other
 760. E1vN
 761. E1vN_Other
 762. E1viN
 763. E1viN_Other
 764. E1viiN
 765. E1viiiN
 766. E1ixN
 767. E1xN
 768. E1xiN
 769. E1iO
 770. E1iiO
 771. E1iiiO
 772. E1iiiO_Other
 773. E1vO
 774. E1vO_Other
 775. E1viO
 776. E1viO_Other
 777. E1viiO
 778. E1viiiO
 779. E1ixO
 780. E1xO
 781. E1xiO
 782. E1iP
 783. E1iiP
 784. E1iiiP
 785. E1iiiP_Other
 786. E1ivP
 787. E1ivP_Other
 788. E1vP
 789. E1vP_Other
 790. E1viP
 791. E1viP_Other
 792. E1viiP
 793. E1viiiP
 794. E1ixP
 795. E1xP
 796. E1xiP
 797. E1iQ
 798. E1iiiQ
 799. E1iiiQ_Other
 800. E1vQ
 801. E1vQ_Other
 802. E1viQ
 803. E1viQ_Other
 804. E1viiQ
 805. E1viiiQ
 806. E1ixQ
 807. E1xQ
 808. E1xiQ
 809. E1iR
 810. E1iiiR
 811. E1iiiR_Other
 812. E1viiR
 813. E1viiiR
 814. E1ixR
 815. E1xiR
 816. E1iS
 817. E1iiS
 818. E1iiiS
 819. E1iiiS_Other
 820. E1vS
 821. E1vS_Other
 822. E1viS
 823. E1viS_Other
 824. E1viiS
 825. E1viiiS
 826. E1ixS
 827. E1xS
 828. E1iT
 829. E1iiT
 830. E1iiiT
 831. E1iiiT_Other
 832. E1ivT
 833. E1ivT_Other
 834. E1vT
 835. E1vT_Other
 836. E1viT
 837. E1viT_Other
 838. E1viiT
 839. E1viiiT
 840. E1ixT
 841. E1xT
 842. E1xiT
 843. E1iU
 844. E1iiU
 845. E1iiiU
 846. E1iiiU_Other
 847. E1ivU
 848. E1ivU_Other
 849. E1vU
 850. E1vU_Other
 851. E1viU
 852. E1viU_Other
 853. E1viiU
 854. E1viiiU
 855. E1ixU
 856. E1xU
 857. E1xiU
 858. E1_ii
 859. E1_iii
 860. E1_iii_Other
 861. E2A
 862. E2B
 863. E2C__1
 864. E2C__2
 865. E2C__3
 866. E2C__4
 867. E2C__5
 868. E2C__6
 869. E2C__7
 870. E2C__98
 871. E2C__99
 872. E2D__1
 873. E2D__2
 874. E2D__3
 875. E2D__4
 876. E2D__5
 877. E2D__6
 878. E2D__7
 879. E2D__8
 880. E2E
 881. E2F__1
 882. E2F__2
 883. E2F__3
 884. E2F__4
 885. E2F__5
 886. E2F__6
 887. E2F__7
 888. E2F__8
 889. E2F__9
 890. E2F__10
 891. E2F__11
 892. E2F__12
 893. E2F__13
 894. E2F__14
 895. E2F__15
 896. E2F__16
 897. E2F__17
 898. E2F__18
 899. E2F__19
 900. E2F__20
 901. E2F__21
 902. E2F__96
 903. E2F_Others
 904. E2G
 905. E2G_Others
 906. E2H__1
 907. E2H__2
 908. E2H__3
 909. E2H__4
 910. E2H__5
 911. E2H__6
 912. E2H__7
 913. E2H__8
 914. E2H__9
 915. E2H__10
 916. E2H__11
 917. E2H__12
 918. E2H__13
 919. E2H__96
 920. E2H__98
 921. E2H__99
 922. E3A__1
 923. E3A__2
 924. E3A__3
 925. E3A__4
 926. E3A__5
 927. E3A__6
 928. E3A__7
 929. E3A__8
 930. E3A__9
 931. E3A__10
 932. E3B__1
 933. E3B__2
 934. E3B__3
 935. E3B__4
 936. E3B__5
 937. E3B__6
 938. E3B__7
 939. E3B__8
 940. E3B__9
 941. E3C
 942. E3D__1
 943. E3D__2
 944. E3D__3
 945. E3D__4
 946. E3D__5
 947. E3D__6
 948. E3D__7
 949. E3D__99
 950. F1__1
 951. F1__2
 952. F1__3
 953. F1__4
 954. F1__5
 955. F1__96
 956. F1_Other
 957. F2__1
 958. F2__2
 959. F2__3
 960. F2__4
 961. F2__5
 962. F2__6
 963. F2__7
 964. F2__96
 965. F2__98
 966. F2__99
 967. F2_Other
 968. F3__1
 969. F3__2
 970. F3__3
 971. F3__4
 972. F3__5
 973. F3__6
 974. F3__7
 975. F3__8
 976. F3__96
 977. F3__98
 978. F3__99
 979. F3_Other
 980. F1iA
 981. F1iA_Other
 982. F1iiA
 983. F1iiA_Other
 984. F1iiiA
 985. F1iiiA_Other
 986. F1iB
 987. F1iB_Other
 988. F1iiB
 989. F1iiB_Other
 990. F1iiiB
 991. F1iiiB_Other
 992. F1iC
 993. F1iC_Other
 994. F1iiC
 995. F1iiC_Other
 996. F1iiiC
 997. F1iiiC_Other
 998. F1iD
 999. F1iD_Other
1000. F1iiD
1001. F1iiD_Other
1002. F1iiiD
1003. F1iiiD_Other
1004. F1iE
1005. F1iE_Other
1006. F1iiE
1007. F1iiE_Other
1008. F1iiiE
1009. F1iiiE_Other
1010. F1iF
1011. F1iF_Other
1012. F1iiF
1013. F1iiF_Other
1014. F1iiiF
1015. F1iiiF_Other
1016. F1iG
1017. F1iG_Other
1018. F1iiG
1019. F1iiG_Other
1020. F1iiiG
1021. F1iiiG_Other
1022. F1iH
1023. F1iH_Other
1024. F1iiH
1025. F1iiH_Other
1026. F1iiiH
1027. F1iiiH_Other
1028. F1iI
1029. F1iI_Other
1030. F1iiI
1031. F1iiI_Other
1032. F1iiiI
1033. F1iiiI_Other
1034. F1iJ
1035. F1iJ_Other
1036. F1iiJ
1037. F1iiJ_Other
1038. F1iiiJ
1039. F1iiiJ_Other
1040. F1iK
1041. F1iK_Other
1042. F1iiK
1043. F1iiK_Other
1044. F1iiiK
1045. F1iiiK_Other
1046. F1iL
1047. F1iL_Other
1048. F1iiL
1049. F1iiL_Other
1050. F1iiiL
1051. F1iiiL_Other
1052. F1_1
1053. F1_1Other
1054. F2Ai
1055. F2Aii
1056. F2Aiii
1057. F2B__1
1058. F2B__2
1059. F2B__3
1060. F2B__4
1061. F2B__5
1062. F2B__6
1063. F2B__7
1064. F2B__8
1065. F2B__99
1066. F2B_Others_Specify
1067. F2C__1
1068. F2C__2
1069. F2C__3
1070. F2C__4
1071. F2C__5
1072. F2C__6
1073. F2C__7
1074. F2C__8
1075. F2C__9
1076. F2C__98
1077. F2C__99
1078. F2C_Others_Specify
1079. F2D__1
1080. F2D__2
1081. F2D__3
1082. F2D__4
1083. F2D__5
1084. F2D__6
1085. F2D__7
1086. F2D__8
1087. F2D_Others_Specify
1088. F2E
1089. F2Ei
1090. F2Fa
1091. F2Fai
1092. F2Fb
1093. F2Fbi
1094. F2Fc
1095. F2Fci
1096. F2G
1097. F2Gi
1098. F2H__1
1099. F2H__2
1100. F2H__3
1101. F2H__4
1102. F2I__1
1103. F2I__2
1104. F2I__3
1105. F2I__4
1106. F2I__96
1107. F2I__98
1108. F2I__99
1109. F2Ii
1110. F2J
1111. F2K__1
1112. F2K__2
1113. F2K__3
1114. F2K__4
1115. F2K__5
1116. F2K__6
1117. F2K__7
1118. F2K__98
1119. F2K__99
1120. F2Ki
1121. F2L
1122. F2Ma
1123. F2Mb
1124. F2Mc
1125. F2Md
1126. F2Me
1127. F2Mf
1128. G1A1__1
1129. G1A1__2
1130. G1A1__3
1131. G1A1__4
1132. G1A1__5
1133. G1A1__6
1134. G1A1__7
1135. G1A1__8
1136. G1A1__9
1137. G1A1__10
1138. G1A1__11
1139. G1A1__13
1140. G1A1__96
1141. G1A1__98
1142. G1A1__99
1143. G1A1_Other
1144. G1B1
1145. G1B1_Other
1146. G1A2__1
1147. G1A2__2
1148. G1A2__3
1149. G1A2__4
1150. G1A2__5
1151. G1A2__6
1152. G1A2__7
1153. G1A2__8
1154. G1A2__9
1155. G1A2__10
1156. G1A2__11
1157. G1A2__13
1158. G1A2__96
1159. G1A2__98
1160. G1A2__99
1161. G1A2_Other
1162. G1B2
1163. G1B2_Other
1164. G1A3__1
1165. G1A3__2
1166. G1A3__3
1167. G1A3__4
1168. G1A3__5
1169. G1A3__6
1170. G1A3__7
1171. G1A3__8
1172. G1A3__9
1173. G1A3__10
1174. G1A3__11
1175. G1A3__13
1176. G1A3__96
1177. G1A3__98
1178. G1A3__99
1179. G1A3_Other
1180. G1B3
1181. G1B3_Other
1182. G1A4__1
1183. G1A4__2
1184. G1A4__3
1185. G1A4__4
1186. G1A4__5
1187. G1A4__6
1188. G1A4__7
1189. G1A4__8
1190. G1A4__9
1191. G1A4__10
1192. G1A4__11
1193. G1A4__13
1194. G1A4__96
1195. G1A4__98
1196. G1A4__99
1197. G1A4_Other
1198. G1B4
1199. G1B4_Other
1200. G1A5__1
1201. G1A5__2
1202. G1A5__3
1203. G1A5__4
1204. G1A5__5
1205. G1A5__6
1206. G1A5__7
1207. G1A5__8
1208. G1A5__9
1209. G1A5__10
1210. G1A5__11
1211. G1A5__12
1212. G1A5__13
1213. G1A5__96
1214. G1A5__98
1215. G1A5__99
1216. G1A5_Other
1217. G1B5
1218. G1B5_Other
1219. G1A6__1
1220. G1A6__2
1221. G1A6__3
1222. G1A6__4
1223. G1A6__5
1224. G1A6__6
1225. G1A6__7
1226. G1A6__8
1227. G1A6__9
1228. G1A6__10
1229. G1A6__11
1230. G1A6__12
1231. G1A6__13
1232. G1A6__96
1233. G1A6__98
1234. G1A6__99
1235. G1A6_Other
1236. G1B6
1237. G1B6_Other
1238. G1A7__1
1239. G1A7__2
1240. G1A7__3
1241. G1A7__4
1242. G1A7__5
1243. G1A7__6
1244. G1A7__7
1245. G1A7__8
1246. G1A7__9
1247. G1A7__10
1248. G1A7__11
1249. G1A7__12
1250. G1A7__13
1251. G1A7__96
1252. G1A7__98
1253. G1A7__99
1254. G1A7_Other
1255. G1B7
1256. G1B7_Other
1257. G1A8__1
1258. G1A8__2
1259. G1A8__3
1260. G1A8__4
1261. G1A8__5
1262. G1A8__6
1263. G1A8__7
1264. G1A8__8
1265. G1A8__9
1266. G1A8__10
1267. G1A8__11
1268. G1A8__12
1269. G1A8__13
1270. G1A8__96
1271. G1A8__98
1272. G1A8__99
1273. G1A_8Other
1274. G1B8
1275. G1B8_Other
1276. G1A9__1
1277. G1A9__2
1278. G1A9__3
1279. G1A9__4
1280. G1A9__5
1281. G1A9__6
1282. G1A9__7
1283. G1A9__8
1284. G1A9__9
1285. G1A9__10
1286. G1A9__11
1287. G1A9__12
1288. G1A9__13
1289. G1A9__96
1290. G1A9__98
1291. G1A9__99
1292. G1A9_Other
1293. G1B9
1294. G1B9_Other
1295. G2
1296. G3__0
1297. G3__1
1298. G3__2
1299. G3__3
1300. G3__4
1301. G3__5
1302. G3__6
1303. G3__7
1304. G3__8
1305. G3__9
1306. G3__10
1307. G3__11
1308. G3__12
1309. G3__13
1310. G3__14
1311. G3__15
1312. G3__16
1313. G3__17
1314. G3__18
1315. G3__19
1316. G3__20
1317. G3__21
1318. G3__22
1319. G3__23
1320. G3__24
1321. G3__25
1322. G3__26
1323. G3__27
1324. G3__28
1325. G3__29
1326. G3__30
1327. G3__31
1328. G3__32
1329. G3__33
1330. G3__34
1331. G3__35
1332. G3__36
1333. G3__37
1334. G3__38
1335. G3__39
1336. G3__40
1337. G3__41
1338. G3__42
1339. G3__43
1340. G3__44
1341. G3__45
1342. G3__46
1343. G3__47
1344. G3__48
1345. G3__49
1346. G3__50
1347. G3__51
1348. G3__52
1349. G3__53
1350. G3__54
1351. G3__55
1352. G3__56
1353. G3__57
1354. G3__58
1355. G3__59
1356. G3__60
1357. G3__61
1358. G3__62
1359. G3__63
1360. G3__64
1361. G3__65
1362. G3__66
1363. G3__67
1364. G3__68
1365. G3__69
1366. G3__70
1367. G3__71
1368. G3__72
1369. G3__73
1370. G3__74
1371. G3__75
1372. G3__76
1373. G3__77
1374. G3__78
1375. G3__79
1376. G3__80
1377. G3__81
1378. G3__82
1379. G3__83
1380. G3__84
1381. G3__85
1382. G3__86
1383. G3__87
1384. G3__88
1385. G3__89
1386. G3__90
1387. G3__91
1388. G3__92
1389. G3__93
1390. G3__94
1391. G3__95
1392. G3__96
1393. G3__97
1394. G3__98
1395. G3__99
1396. G3__100
1397. G3__101
1398. G3__102
1399. G3__103
1400. G3__104
1401. G3__105
1402. G3__106
1403. G3__107
1404. G3__108
1405. G3__109
1406. G3__110
1407. G3__111
1408. G3__112
1409. G3__113
1410. G3__114
1411. G3__115
1412. G3__116
1413. G3__117
1414. G3__118
1415. G3__119
1416. G3__120
1417. G3__121
1418. G3__122
1419. G3__123
1420. G3__124
1421. G3__125
1422. G3__126
1423. G3__127
1424. G3__128
1425. G3__129
1426. G3__130
1427. G3__131
1428. G3__132
1429. G3__133
1430. G3__134
1431. G3__135
1432. G3__136
1433. G3__137
1434. G3__138
1435. G3__139
1436. G3__140
1437. G3__141
1438. G3__142

In [23]:
# ------------------------------------------------------------
# 7. MISSING VALUES
# ------------------------------------------------------------

print("\n" + "="*60)
print("5. MISSING VALUES")
print("="*60)

missing_report = (
    df.isna()
      .sum()
      .to_frame("Missing_Count")
)

missing_report["Missing_Percent"] = (
    missing_report["Missing_Count"] / len(df) * 100
).round(2)

missing_report = missing_report.sort_values(
    "Missing_Percent",
    ascending=False
)

display(missing_report.head(50))

============================================================
5. MISSING VALUES
============================================================

         Missing_Count  Missing_Percent
J3__141          20871            100.0
J3__146          20871            100.0
J3__145          20871            100.0
J3__144          20871            100.0
J3__143          20871            100.0
J3__142          20871            100.0
J3__157          20871            100.0
J3__156          20871            100.0
J3__155          20871            100.0
J3__154          20871            100.0
J3__153          20871            100.0
J3__152          20871            100.0
J3__151          20871            100.0
J3__150          20871            100.0
J3__149          20870            100.0
J3__148          20871            100.0
J3__147          20871            100.0
J3__125          20871            100.0
J3__124          20871            100.0
J3__123          20871            100.0
J3__122          20871            100.0
J3__121          20871            100.0
J3__120          20871            100.0
J3__119          20871            100.0
J3__118          20871            100.0
J3__117          20871            100.0
J3__116          20871            100.0
J3__115          20871            100.0
J3__114          20871            100.0
J3__113          20871            100.0
H7ii_51          20870            100.0
H7i_51           20870            100.0
H6_51            20870            100.0
J3__112          20871            100.0
J3__111          20871            100.0
J3__110          20871            100.0
J3__162          20871            100.0
J3__161          20871            100.0
J3__160          20871            100.0
J3__159          20871            100.0
J3__158          20871            100.0
J3__172          20871            100.0
J3__171          20871            100.0
J3__170          20871            100.0
J3__169          20871            100.0
J3__168          20871            100.0
J3__167          20871            100.0
J3__166          20871            100.0
J3__165          20871            100.0
H7ii_39          20870            100.0

In [24]:
# ------------------------------------------------------------
# 8. NUMERIC VARIABLES
# ------------------------------------------------------------

print("\n" + "="*60)
print("6. NUMERIC VARIABLES")
print("="*60)

numeric_columns = df.select_dtypes(
    include=np.number
).columns.tolist()

print(f"Number of numeric variables: {len(numeric_columns)}")

display(
    df[numeric_columns].describe().T
)

============================================================
6. NUMERIC VARIABLES
============================================================

NameError: name 'np' is not defined

In [ ]:
# 9. CATEGORICAL / TEXT VARIABLES
# ------------------------------------------------------------

print("\n" + "="*60)
print("7. CATEGORICAL / TEXT VARIABLES")
print("="*60)

categorical_columns = df.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print(f"Number of categorical variables: {len(categorical_columns)}")

categorical_info = pd.DataFrame({
    "Variable": categorical_columns,
    "Unique_Values": [
        df[col].nunique(dropna=True)
        for col in categorical_columns
    ],
    "Missing_Percent": [
        round(df[col].isna().mean() * 100, 2)
        for col in categorical_columns
    ]
})

display(categorical_info)

In [ ]:
# ------------------------------------------------------------
# 10. EXAMINE VARIABLES WITH FEW CATEGORIES
# ------------------------------------------------------------

print("\n" + "="*60)
print("8. VARIABLES WITH FEW CATEGORIES")
print("="*60)

print("These are particularly useful for understanding")
print("Yes/No questions, demographic categories, etc.\n")

few_category_variables = []

for col in df.columns:

    unique_count = df[col].nunique(dropna=True)

    if 2 <= unique_count <= 10:

        few_category_variables.append({
            "Variable": col,
            "Unique_Values": unique_count,
            "Missing_Percent": round(
                df[col].isna().mean() * 100, 2
            )
        })

few_category_df = pd.DataFrame(few_category_variables)

display(
    few_category_df.sort_values("Unique_Values")
)

In [ ]:
# 11. SEARCH FOR FINANCIAL VARIABLES
# ------------------------------------------------------------

print("\n" + "="*60)
print("9. POSSIBLE FINANCIAL VARIABLES")
print("="*60)

financial_keywords = [
    "loan",
    "credit",
    "borrow",
    "debt",
    "saving",
    "savings",
    "insurance",
    "financial",
    "money",
    "income",
    "expenditure",
    "expense",
    "bank",
    "mobile",
    "mpesa",
    "m-pesa",
    "finance",
    "shock",
    "stress",
    "default",
    "repay",
    "payment",
    "lending"
]

financial_variables = []

for col in df.columns:

    col_lower = col.lower()

    if any(keyword in col_lower for keyword in financial_keywords):
        financial_variables.append(col)

print(f"Found {len(financial_variables)} possible financial variables:\n")

for col in financial_variables:
    print("-", col)

In [ ]:
# ------------------------------------------------------------
# 12. SEARCH FOR DEMOGRAPHIC VARIABLES
# ------------------------------------------------------------

print("\n" + "="*60)
print("10. POSSIBLE DEMOGRAPHIC VARIABLES")
print("="*60)

demographic_keywords = [
    "age",
    "gender",
    "sex",
    "male",
    "female",
    "education",
    "educ",
    "employment",
    "occupation",
    "county",
    "region",
    "urban",
    "rural",
    "household",
    "marital",
    "income"
]

demographic_variables = []

for col in df.columns:

    col_lower = col.lower()

    if any(keyword in col_lower for keyword in demographic_keywords):
        demographic_variables.append(col)

print(f"Found {len(demographic_variables)} possible demographic variables:\n")

for col in demographic_variables:
    print("-", col)

In [ ]:
# ------------------------------------------------------------
# 13. SEARCH FOR SURVEY / WEIGHT VARIABLES
# ------------------------------------------------------------

print("\n" + "="*60)
print("11. POSSIBLE SURVEY WEIGHT / DESIGN VARIABLES")
print("="*60)

survey_keywords = [
    "weight",
    "wt",
    "wgt",
    "strata",
    "cluster",
    "psu",
    "sampling",
    "sample",
    "factor"
]

survey_variables = []

for col in df.columns:

    col_lower = col.lower()

    if any(keyword in col_lower for keyword in survey_keywords):
        survey_variables.append(col)

print(f"Found {len(survey_variables)} possible survey/design variables:\n")

for col in survey_variables:
    print("-", col)

In [ ]:
# ------------------------------------------------------------
# 14. INSPECT FINANCIAL VARIABLES
# ------------------------------------------------------------

print("\n" + "="*60)
print("12. VALUES OF POSSIBLE FINANCIAL VARIABLES")
print("="*60)

for col in financial_variables[:30]:

    print("\n" + "-"*60)
    print("VARIABLE:", col)
    print("-"*60)

    print("Data type:", df[col].dtype)
    print("Unique values:", df[col].nunique(dropna=True))
    print("Missing:", f"{df[col].isna().mean()*100:.2f}%")

    # Show most common values
    print("\nMost common values:")

    display(
        df[col]
        .value_counts(dropna=False)
        .head(10)
        .to_frame("Count")
    )

In [ ]:
# ------------------------------------------------------------
# 15. DUPLICATE ROW CHECK
# ------------------------------------------------------------

print("\n" + "="*60)
print("13. DUPLICATE CHECK")
print("="*60)

duplicate_count = df.duplicated().sum()

print(f"Completely duplicated rows: {duplicate_count:,}")

if duplicate_count == 0:
    print("No completely duplicated rows found.")
else:
    print("Duplicates were found and should be investigated.")

In [ ]:
# ------------------------------------------------------------
# 16. POSSIBLE IDENTIFIER VARIABLES
# ------------------------------------------------------------

print("\n" + "="*60)
print("14. POSSIBLE IDENTIFIER VARIABLES")
print("="*60)

identifier_keywords = [
    "id",
    "identifier",
    "serial",
    "case",
    "respondent",
    "household",
    "hhid"
]

identifier_variables = []

for col in df.columns:

    col_lower = col.lower()

    if any(keyword in col_lower for keyword in identifier_keywords):

        identifier_variables.append({
            "Variable": col,
            "Unique_Values": df[col].nunique(dropna=True),
            "Rows": len(df)
        })

identifier_df = pd.DataFrame(identifier_variables)

display(identifier_df)

In [ ]:
# ------------------------------------------------------------
# 17. CREATE A CLEAN VARIABLE REPORT
# ------------------------------------------------------------

print("\n" + "="*60)
print("15. CREATING VARIABLE REPORT")
print("="*60)

variable_report = pd.DataFrame({
    "Variable": df.columns,
    "Data_Type": [str(df[col].dtype) for col in df.columns],
    "Non_Missing": [df[col].notna().sum() for col in df.columns],
    "Missing": [df[col].isna().sum() for col in df.columns],
    "Missing_Percent": [
        round(df[col].isna().mean() * 100, 2)
        for col in df.columns
    ],
    "Unique_Values": [
        df[col].nunique(dropna=True)
        for col in df.columns
    ]
})

display(variable_report.head(50))

In [ ]:
# ------------------------------------------------------------
# 18. SAVE REPORT
# ------------------------------------------------------------

variable_report.to_csv(
    "FinAccess_2024_Variable_Report.csv",
    index=False
)

print("\nVariable report saved as:")
print("FinAccess_2024_Variable_Report.csv")

In [ ]:
# ------------------------------------------------------------
# 19. FINAL SUMMARY
# ------------------------------------------------------------

print("\n" + "="*60)
print("FINACCESS DATASET SUMMARY")
print("="*60)

print(f"""
Rows:                  {rows:,}
Columns:               {columns:,}
Numeric variables:     {len(numeric_columns):,}
Categorical variables: {len(categorical_columns):,}
Financial variables:   {len(financial_variables):,}
Demographic variables: {len(demographic_variables):,}
Survey variables:      {len(survey_variables):,}
Duplicate rows:        {duplicate_count:,}
""")

print("Inspection complete.")
print("Do NOT begin modelling yet.")
print("First identify the appropriate target variable and understand")
print("the survey design and variable definitions.")

In [25]:
# Show the variable names and labels for financial + survey-related variables

from pandas.io.stata import StataReader

reader = StataReader(file_path)
labels = reader.variable_labels()

keywords = [
    "loan", "credit", "borrow", "saving", "savings",
    "income", "expense", "debt", "insurance",
    "financial", "bank", "mobile money", "shock",
    "vulnerability", "access", "weight", "strata",
    "cluster", "psu"
]

for var, label in labels.items():
    text = f"{var} {label}".lower()

    if any(k in text for k in keywords):
        print(f"{var:15} | {label}")

A07             | A7. Cluster Number
A08             | A8. Cluster type
B1C4            | B1C4. You could can cope with an unexpected large expense such as a medical bill
B1E1            | B1E-Unable to pay expenses Housing
B1E2            | B1E-Unable to pay expenses Energy for heating or cooking
B1E3            | B1E-Unable to pay expenses Water for drinking or cleaning
B1E4            | B1E-Unable to pay expenses Transportation costs
B1G             | Think about the money you owe (for example to a bank, MFI, SACCO, a shopkeeper,
B1H             | B1H- Access to Emmergency
B1Ha            | B1Ha.  Other Access to emergency
B1Hi            | B1Hi. Source of loans/credit
B1Hii           | B1Hii. From which type of Savings
B1J             | B1J. Access in Case of Emergency
B1K             | B1K. Access in Case of Emergency
B1M__2          | B1M__2:Other long-term savings accounts whose balances you do not planon withdra
B1M__3          | B1M__3:Financial securities (stocks or bonds) that you plan on holding for at le
B1O             | B1O:. Thinking about your longer-term financialgoals, such as, starting a busine
CountFINANCIAL_HEALTH | CountF
B2A             | B2A. Financial Advice
B2Ai            | B2Ai.  Financial Advice - Other
secFinancial_Awareness | Questions answered in secFinancial_Awareness
B3Ai            | B3Ai.  Income Sources- Other
B3D__2_1        | B3D__2.1: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_1        | B3D__3.1: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_1        | B3D__4.1: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_1        | B3D__6.1: B3D. Received Payments:Bank cheque
B3D__7_1        | B3D__7.1: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_1        | B3D__8.1: B3D. Received Payments:Credit cards / debit cards
B3D__2_2        | B3D__2.2: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_2        | B3D__3.2: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_2        | B3D__4.2: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_2        | B3D__6.2: B3D. Received Payments:Bank cheque
B3D__7_2        | B3D__7.2: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_2        | B3D__8.2: B3D. Received Payments:Credit cards / debit cards
B3D__2_3        | B3D__2.3: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_3        | B3D__3.3: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_3        | B3D__4.3: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_3        | B3D__6.3: B3D. Received Payments:Bank cheque
B3D__7_3        | B3D__7.3: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_3        | B3D__8.3: B3D. Received Payments:Credit cards / debit cards
B3D__2_4        | B3D__2.4: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_4        | B3D__3.4: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_4        | B3D__4.4: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_4        | B3D__6.4: B3D. Received Payments:Bank cheque
B3D__7_4        | B3D__7.4: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_4        | B3D__8.4: B3D. Received Payments:Credit cards / debit cards
B3D__2_5        | B3D__2.5: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_5        | B3D__3.5: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_5        | B3D__4.5: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_5        | B3D__6.5: B3D. Received Payments:Bank cheque
B3D__7_5        | B3D__7.5: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_5        | B3D__8.5: B3D. Received Payments:Credit cards / debit cards
B3D__2_6        | B3D__2.6: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_6        | B3D__3.6: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_6        | B3D__4.6: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_6        | B3D__6.6: B3D. Received Payments:Bank cheque
B3D__7_6        | B3D__7.6: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_6        | B3D__8.6: B3D. Received Payments:Credit cards / debit cards
B3D__2_7        | B3D__2.7: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_7        | B3D__3.7: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_7        | B3D__4.7: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_7        | B3D__6.7: B3D. Received Payments:Bank cheque
B3D__7_7        | B3D__7.7: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_7        | B3D__8.7: B3D. Received Payments:Credit cards / debit cards
B3D__2_8        | B3D__2.8: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_8        | B3D__3.8: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_8        | B3D__4.8: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_8        | B3D__6.8: B3D. Received Payments:Bank cheque
B3D__7_8        | B3D__7.8: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_8        | B3D__8.8: B3D. Received Payments:Credit cards / debit cards
B3D__2_9        | B3D__2.9: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_9        | B3D__3.9: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_9        | B3D__4.9: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_9        | B3D__6.9: B3D. Received Payments:Bank cheque
B3D__7_9        | B3D__7.9: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_9        | B3D__8.9: B3D. Received Payments:Credit cards / debit cards
B3D__2_10       | B3D__2.10: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Mone
B3D__3_10       | B3D__3.10: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bi
B3D__4_10       | B3D__4.10: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__6_10       | B3D__6.10: B3D. Received Payments:Bank cheque
B3D__7_10       | B3D__7.10: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ba
B3D__8_10       | B3D__8.10: B3D. Received Payments:Credit cards / debit cards
C1_10           | C1-10. Registered on Mobile money
C1_11           | C1_11. Registered on Mobile bank
C1_12           | C1_12. Registered on a bank/microfinance Bank account
C1_12ai_CHK__0  | C1_12ai_Which Bank do you currently hold an account in:0
C1_12ai_CHK__1  | C1_12ai_Which Bank do you currently hold an account in:1
C1_12ai_CHK__2  | C1_12ai_Which Bank do you currently hold an account in:2
C1_12ai_CHK__3  | C1_12ai_Which Bank do you currently hold an account in:3
C1_12ai_CHK__4  | C1_12ai_Which Bank do you currently hold an account in:4
C1_12ai_CHK__5  | C1_12ai_Which Bank do you currently hold an account in:5
C1_12ai_CHK__6  | C1_12ai_Which Bank do you currently hold an account in:6
C1_12ai_CHK__7  | C1_12ai_Which Bank do you currently hold an account in:7
C1_12ai_CHK__8  | C1_12ai_Which Bank do you currently hold an account in:8
C1_12ai_CHK__9  | C1_12ai_Which Bank do you currently hold an account in:9
C1_12ai_CHK__10 | C1_12ai_Which Bank do you currently hold an account in:10
C1_12ai_CHK__11 | C1_12ai_Which Bank do you currently hold an account in:11
C1_12ai_CHK__12 | C1_12ai_Which Bank do you currently hold an account in:12
C1_12ai_CHK__13 | C1_12ai_Which Bank do you currently hold an account in:13
C1_12ai_CHK__14 | C1_12ai_Which Bank do you currently hold an account in:14
C1_12ai_CHK__15 | C1_12ai_Which Bank do you currently hold an account in:15
C1_12ai_CHK__16 | C1_12ai_Which Bank do you currently hold an account in:16
C1_12ai_CHK__17 | C1_12ai_Which Bank do you currently hold an account in:17
C1_12ai_CHK__18 | C1_12ai_Which Bank do you currently hold an account in:18
C1_12ai_CHK__19 | C1_12ai_Which Bank do you currently hold an account in:19
C1_12ai_CHK__20 | C1_12ai_Which Bank do you currently hold an account in:20
C1_12ai_CHK__21 | C1_12ai_Which Bank do you currently hold an account in:21
C1_12ai_CHK__22 | C1_12ai_Which Bank do you currently hold an account in:22
C1_12ai_CHK__23 | C1_12ai_Which Bank do you currently hold an account in:23
C1_12ai_CHK__24 | C1_12ai_Which Bank do you currently hold an account in:24
C1_12ai_CHK__25 | C1_12ai_Which Bank do you currently hold an account in:25
C1_12ai_CHK__26 | C1_12ai_Which Bank do you currently hold an account in:26
C1_12ai_CHK__27 | C1_12ai_Which Bank do you currently hold an account in:27
C1_12ai_CHK__28 | C1_12ai_Which Bank do you currently hold an account in:28
C1_12ai_CHK__29 | C1_12ai_Which Bank do you currently hold an account in:29
C1_12ai_CHK__30 | C1_12ai_Which Bank do you currently hold an account in:30
C1_12ai_CHK__31 | C1_12ai_Which Bank do you currently hold an account in:31
C1_12ai_CHK__32 | C1_12ai_Which Bank do you currently hold an account in:32
C1_12ai_CHK__33 | C1_12ai_Which Bank do you currently hold an account in:33
C1_12ai_CHK__34 | C1_12ai_Which Bank do you currently hold an account in:34
C1_12ai_CHK__35 | C1_12ai_Which Bank do you currently hold an account in:35
C1_12ai_CHK__36 | C1_12ai_Which Bank do you currently hold an account in:36
C1_12ai_CHK__37 | C1_12ai_Which Bank do you currently hold an account in:37
C1_12ai_CHK__38 | C1_12ai_Which Bank do you currently hold an account in:38
C1_12ai_CHK__39 | C1_12ai_Which Bank do you currently hold an account in:39
C1_12ai_CHK__40 | C1_12ai_Which Bank do you currently hold an account in:40
C1_12ai_CHK__41 | C1_12ai_Which Bank do you currently hold an account in:41
C1_12ai_CHK__42 | C1_12ai_Which Bank do you currently hold an account in:42
C1_12ai_CHK__43 | C1_12ai_Which Bank do you currently hold an account in:43
C1_12ai_CHK__44 | C1_12ai_Which Bank do you currently hold an account in:44
C1_12ai_CHK__45 | C1_12ai_Which Bank do you currently hold an account in:45
C1_12ai_CHK__46 | C1_12ai_Which Bank do you currently hold an account in:46
C1_12ai_CHK__47 | C1_12ai_Which Bank do you currently hold an account in:47
C1_12ai_CHK__48 | C1_12ai_Which Bank do you currently hold an account in:48
C1_12ai_CHK__49 | C1_12ai_Which Bank do you currently hold an account in:49
C1_12ai_CHK__50 | C1_12ai_Which Bank do you currently hold an account in:50
C1_12ai_CHK__51 | C1_12ai_Which Bank do you currently hold an account in:51
C1_12ai_CHK__52 | C1_12ai_Which Bank do you currently hold an account in:52
C1_12ai_CHK__53 | C1_12ai_Which Bank do you currently hold an account in:53
C1_1a           | C1-1a. Savings at Bank/ Microfinance Bank
C1_1b           | C1-1b. Savings at Microfinance Institutions
C1_2            | C1-2. Savings through mobile banking Platform
C1_3            | C1-3. Savings/keeping through mobile money provider
C1_4            | C1-4. Savings at a Sacco / Savings and Credit Cooperative organisation
C1_5            | C1-5. Savings at a chama
C1_6            | C1-6.   Savings with a group/group of friends
C1_7            | C1-7. Savings given to a family or friend to keep
C1_8            | C1-8. Savings you keep in a secret hiding place
C1_9            | C1-9. Savings you keep in a Digital savings App
C1_13a          | C1_13a. Personal loan/business loan from a commercial bank
C1_13b          | C1_13b. Personal loan/business loan from a microfinance bank
C1_13c          | C1_13c. LBank/ Micro finance bank Overdraft
C1_14           | C1_14. Credit card
C1_15           | C1_15. Loan from mobile banking
C1_16           | C1_16. Loan from mobile provider (e.g Fuliza loan, Equity's Boostika)
C1_17           | C1_17. Loan from Sacco
C1_18           | C1_18. Loan from a microfinance institution
C1_19           | C1_19. Digital loans
C1_20           | C1-20. Loan from Shylocks
C1_21           | C1-21. Loan from a group/chama
C1_22           | C1_22:Loan from a government institution foreducation, agriculture or a developm
C1_23           | C1-23 Loan from Hustler Fund
C1_24           | C1-24 Loan from an employer
C1_25           | C1-25. Loan from family/friend/neighbour
C1_26           | C1-26. Cash loan from shopkeeper
C1_27           | C1-27. Taking goods and services on credit from a shopkeeper
C1_28           | C1_28:Loan / credits from buyer of your harvest / supplier of agricultural input
C1_29           | C1-29. Loan Lipa polepole / Hire Purchase
C1_30           | C1-30. Loan from Insurance
C1_31           | C1-31. Loan to buy / build a house (mortgage), or to buy land
C1_32           | C1-32. Postbank account
C1_36           | C1-36. Motor insurance
C1_38           | C1-38. Other medical/health insurance policy, NOT NHIF/SHIF
C1_39           | C1-39. Other insurance e.g. fire, education, crop, life
C2_15           | C2_15. Loan from mobile banking
C2_16           | C2_16. Loan from mobile money provider
C2_19           | C2_19:Take digital loans that you get through the phone that you download throug
C2_23           | C2_23. Loan from Hustler Fund?
C3              | C3. Most trusted financial service provider
D1A__2          | D1A_2: Not contributing - Received lumpsum pension payment
D1Ai__4         | D1Ai_4: Lack of saving incentives
D1E             | D1E: Currently saving for retirement or receiving monthly pension
D1G             | D1G: Partial access to Retirement benefits before retirement
D1I             | D1I: How I lost my retirement benefits savings
D1Md            | can easily access my funds in my retirement benfits/pension scheme account
D2__1           | D2_1: I lost my job/income
D2__2           | D2_2: I would like to continue with my insurance but I cant afford anymore
D2__3           | D2_3: I don't need insurance anymore/I have other options/family/savings
D2__4           | D2_4: I don't trust insurance providers/agents are dishnonest
D3__1           | D3_1: Don't have a regular income/job/too expensive/can't afford
D3__2           | D3_2: I don't understand or know about insurance/don't know where to get it
D3__3           | D3_3: I don't need insurance/it will not benefit me/I have other options to deal
D3__4           | D3_4: Insurance will bring bad luck- I don't believe in it
D3__5           | D3_5: I don't trust insurance providers/I don't trust that they will pay my clai
D3__6           | D3_6: I don't have an ID or the other requirements needed to get insurance polic
D4__1           | D4_1: Property (e.g House,building or contents insurance)
D4__2           | D4_2: Crop insurance
D4__3           | D4_3: Livestock insurance
D4__4           | D4_4: Life insurance
D4__5           | D4_5: Education insurance
D4__7           | D4_7: Fire Insurance
D4__9           | D4_9: Other insurance (SPECIFY)
D5              | D5: Ways acquired Insurance Policy
D6              | D6: Method of payment of the Insurance Premium
D8__1           | D8_1:Declined/Delayed/Underpaid insurance claim
D8__2           | D8_2: Discovered that your personal data was stolen or shared by insurance compa
D8__5           | D8_5: Cancelled policy due in insurance company collapsed
D10             | D10: Register a complaint or resolve an issue regarding your insurance policy
D13_1           | D13_1: Terms and conditions for the products and services at my insurance are cl
D13_2           | D13_2: The products and services offered by  my insurance are fairly priced
D13_3           | D13_3: I can easily communicate with my insurance if I need to
D13_4           | D13_4. I can easily claim on my insurance policy if need arise
D13_5           | D13_5. I can easily access my funds in my insurance account
D13_6           | D13_6: I trust my insurance  provider
D13_7           | D13_7: My insurance has good customer service
E1              | E1: Have you applied for and been denied a loan in the last 12 months?
E2__1           | E2_1: Commercial bank
E2__2           | E2_2: Microfinance bank
E2__4           | E2_4: Mobile money provider (e.g.
E2__5           | E2_5: Mobile banking (e.g. Mshwari
E2__6           | E2_6: Credit-Only institution  (e
E2__7           | E2_7: Digital loans that you get through App like Branch, Tala
E2__8           | E2_8: Insurance company
E2__10          | E2_10: Loan from a government institutions like AFC, HELB,Youth Fund (excluding
E3__16          | the lender did not have float/money at the time of borrowing
E3__5           | E3_5: Still had debt to pay
E3__7           | E3_7: Bad credit history
E3__8           | E3_8: No credit history
E3__9           | E3_9: Income is low and unab
E3__11          | E3_11: Savings too low
E4__1           | E4. :Don't have money/income/job; Can't afford loans
E4__2           | E4. :I don't know where or how to borrow
E4__3           | E4__3:I don't like borrowing/loansdon't benefit me/there are no loan products th
E4__4           | E4. :Loans are too risky for me
E4__5           | E4. :I don't trust loan providers
E4__9           | do not qualify/Bad credit history
E5__1           | E5. :I lost my job/income
E5__2           | E5__2:I can't afford to borrow at the moment/ it's too expensive
E5__3           | E5__2:Loans are not benefitting me/there are no loan products that meet my needs
E5__4           | E5. :Interest rates for loans are too high
E5__5           | E5. :Loans have become too risky for me
E5__6           | E5. :I don't trust loan providers
E5__7           | E5. :Unethical debt recovery/harassment
E1iA            | E1iA: Number of bank Loans past 12 months
E1iiA           | E1iiA: Number of Outstanding bank Loans
E1iiiA          | E1iiiA: Reason for taking bank loan product
E1iiiA_Other    | E1iiiA: Reason for taking Bank Loan Product; Others
E1ivA           | E1ivA: Collateral used for Bank Loan
E1ivA_Other     | E1ivA: Collateral used for Bank Loan; Others
E1vA            | E1vA: Frequency of bank loan repayments
E1vA_Other      | E1vA: Frequency of bank loan repayments; Others
E1viA           | E1viA: Channels used for repaying bank loan
E1viA_Other     | E1viA: Channels used for repaying bank loan; Others
E1viiA          | E1viiA: Amount of Bank loan borrowed
E1viiiA         | E1viiiA: Amount of bank loan approved
E1ixA           | E1ixA:  Date of borrowing the bank loan
E1xA            | E1xA: Bank Loan Repayment due date
E1xiA           | E1xiA: Outstanding bank loan amount
E1iB            | E1iB: Number of microfinance bank loans past 12 months
E1iiB           | E1iiB: Number of Outstanding microfinance bank loans
E1iiiB          | E1iiiB: Reason for taking microfinance bank loan product
E1iiiB_Other    | E1iiiB: Reason for taking microfinance bank loan product; Others
E1ivB           | E1ivB: Collateral used for microfinance bank loan
E1ivB_Other     | E1ivB: Collateral used for microfinance bank loan; Others
E1vB            | E1vB: Frequency of microfinance bank loan repayments
E1vB_Other      | E1vB: Frequency of microfinance bank loan repayments; Others
E1viB           | E1viB: Channels used for repaying microfinance bank loan
E1viB_Other     | E1viB: Channels used for repaying microfinance bank loan; Others
E1viiB          | E1viiB: Amount of microfinance bank loan borrowed
E1viiiB         | E1viiiB: Amount of microfinance bank loan approved
E1ixB           | E1ixB: Date of borrowing the microfinance bank loan
E1xB            | E1xB: Microfinance bank loan repayment due date
E1xiB           | E1xiB: Outstanding microfinance bank loan amount
E1iC            | E1iC: Number of bank overdraft loans past 12 months
E1iiC           | E1iiC: Number of Outstanding bank overdraft loans
E1iiiC          | E1iiiC: Reason for taking bank overdraft loan
E1iiiC_Other    | E1iiiC: Reason for taking bank overdraft loan product; Others
E1ivC           | E1ivC: Collateral used for bank overdraft loan

In [26]:
import os

file_path = "/content/2024_Finaccess_Publicdata.dta"

size = os.path.getsize(file_path)

print("Filename:", os.path.basename(file_path))
print("Bytes:", size)
print("MB:", round(size / (1024**2), 2))
print("GB:", round(size / (1024**3), 4))

Filename: 2024_Finaccess_Publicdata.dta
Bytes: 159531918
MB: 152.14
GB: 0.1486

In [32]:
from pandas.io.stata import StataReader

file_path = "/content/2024_Finaccess_Publicdata.dta"

reader = StataReader(file_path)

print("First 30 variable names:")

for i, var in enumerate(reader.varlist):
    print(var)
    if i == 29:
        break

First 30 variable names:

AttributeError: 'StataReader' object has no attribute 'varlist'

In [37]:
# Show variable names and their official FinAccess descriptions

print("VARIABLE | LABEL")
print("=" * 100)

for var, label in zip(meta.column_names, meta.column_labels):
    if label and label.strip():
        print(f"{var:25} | {label}")
        keywords = [
    "loan", "credit", "borrow", "saving", "savings",
    "income", "expense", "debt", "insurance",
    "financial", "bank", "mobile money", "money",
    "shock", "vulnerability", "access"
]

print("VARIABLE | LABEL")
print("=" * 100)

for var, label in zip(meta.column_names, meta.column_labels):
    text = f"{var} {label}".lower()

    if any(k in text for k in keywords):
        print(f"{var:25} | {label}")

VARIABLE | LABEL
====================================================================================================
interview__key            | Interview key (identifier in XX-XX-XX-XX format)
interview__id             | Unique 32-character long identifier of the interview
county                    | County
A07                       | A7. Cluster Number
A08                       | A8. Cluster type
A10                       | Housing Unit Number
Interview_Status          | Interview status
A9i                       | A9i. What was the RESULTS of this interview?
Z1                        | Results of the Interview
A13                       | A13. Sex
A12ii_length              | HH_roster_size_ex12ii
A14iv                     | Number of eligible persons
A14vi                     | Index of the selected person
FHH_Spouse                | FHH_Spouse
A15a                      | A15a Language
A15i                      | A15i. Language
A18                       | A18. AGE OF RESPONDENT
A19                       | A19. Relation to HH Head
A14i                      | A14i.How old is [NAME] in completed years?
A14ii                     | Sex of a household member
A14iii                    | Relationship of the household member to the head of household
A14iv_e                   | A14iv. Education level
A14vii                    | A14vii. Current School attendance
A14_slept                 | slept in the household last night
RESPONDENT                | A14vii. Select Name of the respondent who provided Household members information
Sex                       | Sex of Selected Individual
Age                       | Agegroup of Selected Individual
A16                       | A16. Status respondents interview
NHM                       | Number of household members.
A20                       | A20. Education Completed
A20i                      | A20i. Other Education level Completed
A21                       | A21. Marital Status
A22i                      | A22i) Number of children in the household
A22ii                     | A22ii) Number of children below 5 years
A22iii                    | A22iii) Number of children below 24 years still in school or university?
A23                       | A23 Household chronic disease status
A24i                      | A24i Difficulty seeing
A24ii                     | A24i Difficulty hearing
A24iii                    | A24i Difficulty walking
A24iv                     | A24i Difficulty with cognition
A24v                      | A24i Difficulty with selfcare
A24vi                     | A24i Difficulty with  communicating
B1A                       | B1A. Main Life Goal
B1Bi                      | B1Bi: Who makes the main decisions about howmoney is spent on day to day househo
B1Bii                     | B1Bii Who makes the main decisions about how money is spent on major/large house
B1C1                      | B1C1 People in your life
B1C2                      | B1C2. Keep money aside?
B1C3                      | B1C3. Spending plan
B1C4                      | B1C4. You could can cope with an unexpected large expense such as a medical bill
B1Di                      | B1Di: In the past 1 month, did you or any household member have to eat fewer mea
B1Dii                     | B1Dii. If Yes, how often did this happen?
B1Diii                    | B1Diii. Eat fewer meals
B1E1                      | B1E-Unable to pay expenses Housing
B1E2                      | B1E-Unable to pay expenses Energy for heating or cooking
B1E3                      | B1E-Unable to pay expenses Water for drinking or cleaning
B1E4                      | B1E-Unable to pay expenses Transportation costs
B1F2                      | B1F2. sent home for lack of school fees
B1F1                      | B1F1. Frequency gone without medicine or medical treatment
B1FI                      | Last time this happened, why did you not buy medicine/seek medical care?
B1FIOTHER                 | B1FI. Other specify
B1G                       | Think about the money you owe (for example to a bank, MFI, SACCO, a shopkeeper,
B1H                       | B1H- Access to Emmergency
B1Ha                      | B1Ha.  Other Access to emergency
B1Hi                      | B1Hi. Source of loans/credit
B1Hii                     | B1Hii. From which type of Savings
B1Ii                      | B1Ii. Raising KSH 13,000 within 30 days
B1Iii                     | B1Iii. Raising KSH 13,000 within 30 days
B1J                       | B1J. Access in Case of Emergency
B1K                       | B1K. Access in Case of Emergency
B1L__1                    | In the past 12 months, did you personally purchase any of the following?:Land
B1L__2                    | B1L__2:A new house
B1L__3                    | B1L__3:Materials to build or improve an existing house
B1L__4                    | B1L__4:Machinery, vehicles, equipment, tools, building for business/self-employm
B1L__5                    | B1L__5:Machinery, vehicles, equipment, tools for farming or raising livestock
B1L__6                    | B1L__6:Livestock
B1M__1                    | B1M__1:A pension (including through an employer'swage deductions suchas NSSF) or
B1M__2                    | B1M__2:Other long-term savings accounts whose balances you do not planon withdra
B1M__3                    | B1M__3:Financial securities (stocks or bonds) that you plan on holding for at le
B1M__4                    | B1M__4:Did you personally payany tuition for schooling, university, or othereduc
B1N1                      | B1N1: How worried are you right now about not having enough money to pay for dai
B1N2                      | B1N2: How worried are you right now about not being able to pay off your exisitn
B1O                       | B1O:. Thinking about your longer-term financialgoals, such as, starting a busine
B1P                       | B1P. Remained Same or Worsened
secB1                     | Questions answered in secB1
CountFINANCIAL_HEALTH     | CountF
B2A                       | B2A. Financial Advice
B2Ai                      | B2Ai.  Financial Advice - Other
B2B                       | B2B. Gaming
B2Ci                      | B2Ci.  Betting Amounts
B2Cii                     | B2Cii:You said that you have engaged in gaming(betting,lottery,gambling) activit
B2Cii_Other               | B2Cii.  Other
B2D                       | B2D. Gaming
B2Ei                      | B2Ei. Interest Paid Answer
B2Eii                     | B2Eii: If you spent Ksh. 500 for your daily needsin July last year, Can your KSh
B2Eiii                    | B2Eiii:Suppose you have have a large sum of money you would like to invest. Woul
B2F                       | B2F. Can Read SMS
secFinancial_Awareness    | Questions answered in secFinancial_Awareness
B3A__1                    | B3A. Farming (crops, keeping livestock, fishing, aquaculture)
B3A__2                    | B3A. Employed/regular employees
B3A__3                    | B3A. Casual worker/Seasonal Worker
B3A__4                    | B3A. Running own business/Self employed
B3A__5                    | B3A__5:Money from NGO / Government/Social transfer (e.g pesa ya wazee, inua jami
B3A__6                    | B3A. Renting, land, house/rooms, equipment
B3A__7                    | B3A. Earning money from investments, e.g. shares, stocks
B3A__8                    | B3A. Pension/Annuity
B3A__9                    | B3A. Support from family / friends / spouse/Remittances
B3A__10                   | B3A. Other (Specify)
B3A__11                   | B3A. None of these
B3A__98                   | B3A. Don't know (DO NOT READ OUT)
B3A__99                   | B3A. Refused to Answer (DO NOT READ OUT)
B3Ai                      | B3Ai.  Income Sources- Other
B3B                       | B3B. Main Source
B3Bi                      | B3Bi: You said you recieved support from fromfamily / friends / spouse/remittanc
B3C                       | B3C. Subsistence Answer
B3Ci                      | B3Ci. In the last 12 months have you earned money in any of the following digita
B3Cii_1                   | B3Cii_1 Ride hailing service/ digital driving (Uber, Bolt, Little, etc.)
B3Cii_2                   | B3Cii_2 Digital delivery or motorbike service (Glovo, Uber Eats, SafeBoda, etc.)
B3Cii_3                   | B3Cii_3. Freelance services e.g. online writing, transcription, or microtasking
B3Cii_4                   | B3Cii_4 Goods/services marketed/sold on social media platforms
B3D__1_1                  | B3D__1.1: B3D. Received Payments:Cash
B3D__2_1                  | B3D__2.1: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_1                  | B3D__3.1: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_1                  | B3D__4.1: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__5_1                  | B3D__5.1: B3D. Received Payments:Merchant/business paybill/till number
B3D__6_1                  | B3D__6.1: B3D. Received Payments:Bank cheque
B3D__7_1                  | B3D__7.1: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_1                  | B3D__8.1: B3D. Received Payments:Credit cards / debit cards
B3D__9_1                  | B3D__9.1: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
B3D__10_1                 | B3D__10.1: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
B3D__11_1                 | B3D__11.1: B3D. Received Payments:Other (SPECIFY)
B3D__98_1                 | B3D__98.1: B3D. Received Payments:Don't know
B3D__99_1                 | B3D__99.1: B3D. Received Payments:Refused to Answer
B3Di_1                    | B3Di.1: B3Di. Received Payments - Other
B3E_1                     | B3E.1: B3E. Received Payments
B3D__1_2                  | B3D__1.2: B3D. Received Payments:Cash
B3D__2_2                  | B3D__2.2: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_2                  | B3D__3.2: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_2                  | B3D__4.2: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__5_2                  | B3D__5.2: B3D. Received Payments:Merchant/business paybill/till number
B3D__6_2                  | B3D__6.2: B3D. Received Payments:Bank cheque
B3D__7_2                  | B3D__7.2: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_2                  | B3D__8.2: B3D. Received Payments:Credit cards / debit cards
B3D__9_2                  | B3D__9.2: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
B3D__10_2                 | B3D__10.2: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
B3D__11_2                 | B3D__11.2: B3D. Received Payments:Other (SPECIFY)
B3D__98_2                 | B3D__98.2: B3D. Received Payments:Don't know
B3D__99_2                 | B3D__99.2: B3D. Received Payments:Refused to Answer
B3Di_2                    | B3Di.2: B3Di. Received Payments - Other
B3E_2                     | B3E.2: B3E. Received Payments
B3D__1_3                  | B3D__1.3: B3D. Received Payments:Cash
B3D__2_3                  | B3D__2.3: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_3                  | B3D__3.3: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_3                  | B3D__4.3: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__5_3                  | B3D__5.3: B3D. Received Payments:Merchant/business paybill/till number
B3D__6_3                  | B3D__6.3: B3D. Received Payments:Bank cheque
B3D__7_3                  | B3D__7.3: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_3                  | B3D__8.3: B3D. Received Payments:Credit cards / debit cards
B3D__9_3                  | B3D__9.3: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
B3D__10_3                 | B3D__10.3: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
B3D__11_3                 | B3D__11.3: B3D. Received Payments:Other (SPECIFY)
B3D__98_3                 | B3D__98.3: B3D. Received Payments:Don't know
B3D__99_3                 | B3D__99.3: B3D. Received Payments:Refused to Answer
B3Di_3                    | B3Di.3: B3Di. Received Payments - Other
B3E_3                     | B3E.3: B3E. Received Payments
B3D__1_4                  | B3D__1.4: B3D. Received Payments:Cash
B3D__2_4                  | B3D__2.4: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_4                  | B3D__3.4: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_4                  | B3D__4.4: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__5_4                  | B3D__5.4: B3D. Received Payments:Merchant/business paybill/till number
B3D__6_4                  | B3D__6.4: B3D. Received Payments:Bank cheque
B3D__7_4                  | B3D__7.4: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_4                  | B3D__8.4: B3D. Received Payments:Credit cards / debit cards
B3D__9_4                  | B3D__9.4: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
B3D__10_4                 | B3D__10.4: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
B3D__11_4                 | B3D__11.4: B3D. Received Payments:Other (SPECIFY)
B3D__98_4                 | B3D__98.4: B3D. Received Payments:Don't know
B3D__99_4                 | B3D__99.4: B3D. Received Payments:Refused to Answer
B3Di_4                    | B3Di.4: B3Di. Received Payments - Other
B3E_4                     | B3E.4: B3E. Received Payments
B3D__1_5                  | B3D__1.5: B3D. Received Payments:Cash
B3D__2_5                  | B3D__2.5: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_5                  | B3D__3.5: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_5                  | B3D__4.5: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__5_5                  | B3D__5.5: B3D. Received Payments:Merchant/business paybill/till number
B3D__6_5                  | B3D__6.5: B3D. Received Payments:Bank cheque
B3D__7_5                  | B3D__7.5: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_5                  | B3D__8.5: B3D. Received Payments:Credit cards / debit cards
B3D__9_5                  | B3D__9.5: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
B3D__10_5                 | B3D__10.5: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
B3D__11_5                 | B3D__11.5: B3D. Received Payments:Other (SPECIFY)
B3D__98_5                 | B3D__98.5: B3D. Received Payments:Don't know
B3D__99_5                 | B3D__99.5: B3D. Received Payments:Refused to Answer
B3Di_5                    | B3Di.5: B3Di. Received Payments - Other
B3E_5                     | B3E.5: B3E. Received Payments
B3D__1_6                  | B3D__1.6: B3D. Received Payments:Cash
B3D__2_6                  | B3D__2.6: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_6                  | B3D__3.6: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_6                  | B3D__4.6: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__5_6                  | B3D__5.6: B3D. Received Payments:Merchant/business paybill/till number
B3D__6_6                  | B3D__6.6: B3D. Received Payments:Bank cheque
B3D__7_6                  | B3D__7.6: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_6                  | B3D__8.6: B3D. Received Payments:Credit cards / debit cards
B3D__9_6                  | B3D__9.6: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
B3D__10_6                 | B3D__10.6: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
B3D__11_6                 | B3D__11.6: B3D. Received Payments:Other (SPECIFY)
B3D__98_6                 | B3D__98.6: B3D. Received Payments:Don't know
B3D__99_6                 | B3D__99.6: B3D. Received Payments:Refused to Answer
B3Di_6                    | B3Di.6: B3Di. Received Payments - Other
B3E_6                     | B3E.6: B3E. Received Payments
B3D__1_7                  | B3D__1.7: B3D. Received Payments:Cash
B3D__2_7                  | B3D__2.7: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_7                  | B3D__3.7: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_7                  | B3D__4.7: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__5_7                  | B3D__5.7: B3D. Received Payments:Merchant/business paybill/till number
B3D__6_7                  | B3D__6.7: B3D. Received Payments:Bank cheque
B3D__7_7                  | B3D__7.7: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_7                  | B3D__8.7: B3D. Received Payments:Credit cards / debit cards
B3D__9_7                  | B3D__9.7: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
B3D__10_7                 | B3D__10.7: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
B3D__11_7                 | B3D__11.7: B3D. Received Payments:Other (SPECIFY)
B3D__98_7                 | B3D__98.7: B3D. Received Payments:Don't know
B3D__99_7                 | B3D__99.7: B3D. Received Payments:Refused to Answer
B3Di_7                    | B3Di.7: B3Di. Received Payments - Other
B3E_7                     | B3E.7: B3E. Received Payments
B3D__1_8                  | B3D__1.8: B3D. Received Payments:Cash
B3D__2_8                  | B3D__2.8: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_8                  | B3D__3.8: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_8                  | B3D__4.8: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__5_8                  | B3D__5.8: B3D. Received Payments:Merchant/business paybill/till number
B3D__6_8                  | B3D__6.8: B3D. Received Payments:Bank cheque
B3D__7_8                  | B3D__7.8: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_8                  | B3D__8.8: B3D. Received Payments:Credit cards / debit cards
B3D__9_8                  | B3D__9.8: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
B3D__10_8                 | B3D__10.8: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
B3D__11_8                 | B3D__11.8: B3D. Received Payments:Other (SPECIFY)
B3D__98_8                 | B3D__98.8: B3D. Received Payments:Don't know
B3D__99_8                 | B3D__99.8: B3D. Received Payments:Refused to Answer
B3Di_8                    | B3Di.8: B3Di. Received Payments - Other
B3E_8                     | B3E.8: B3E. Received Payments
B3D__1_9                  | B3D__1.9: B3D. Received Payments:Cash
B3D__2_9                  | B3D__2.9: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
B3D__3_9                  | B3D__3.9: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__4_9                  | B3D__4.9: B3D. Received Payments:Bank/SACCO/MFI paybill
B3D__5_9                  | B3D__5.9: B3D. Received Payments:Merchant/business paybill/till number
B3D__6_9                  | B3D__6.9: B3D. Received Payments:Bank cheque
B3D__7_9                  | B3D__7.9: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
B3D__8_9                  | B3D__8.9: B3D. Received Payments:Credit cards / debit cards
B3D__9_9                  | B3D__9.9: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
B3D__10_9                 | B3D__10.9: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
B3D__11_9                 | B3D__11.9: B3D. Received Payments:Other (SPECIFY)

In [38]:
# ============================================================
# FINACCESS 2024 — FINANCIAL VARIABLE SHORTLIST
# ============================================================

keywords = [
    "loan",
    "credit",
    "borrow",
    "borrowing",
    "save",
    "savings",
    "saving",
    "income",
    "expense",
    "expenditure",
    "debt",
    "insurance",
    "financial",
    "bank",
    "mobile money",
    "mobile",
    "money",
    "shock",
    "vulnerability",
    "access",
    "account",
    "investment",
    "invest",
    "pension",
    "wealth",
    "payment"
]

matches = []

# Search both variable names and official variable labels
for var, label in zip(meta.column_names, meta.column_labels):

    var_text = str(var)
    label_text = str(label)

    combined_text = f"{var_text} {label_text}".lower()

    if any(keyword in combined_text for keyword in keywords):
        matches.append((var_text, label_text))


# ============================================================
# REMOVE DUPLICATES
# ============================================================

unique_matches = []
seen = set()

for var, label in matches:

    if var not in seen:
        unique_matches.append((var, label))
        seen.add(var)


# ============================================================
# DISPLAY RESULTS
# ============================================================

print("=" * 100)
print("FINACCESS 2024 — POTENTIALLY RELEVANT FINANCIAL VARIABLES")
print("=" * 100)

print(f"\nTotal matching variables: {len(unique_matches)}\n")

for number, (var, label) in enumerate(unique_matches, start=1):

    print(f"{number:3}. {var:25} | {label}")

print("\n" + "=" * 100)
print("Inspection complete.")
print("=" * 100)

====================================================================================================
FINACCESS 2024 — POTENTIALLY RELEVANT FINANCIAL VARIABLES
====================================================================================================

Total matching variables: 2084

  1. B1Bi                      | B1Bi: Who makes the main decisions about howmoney is spent on day to day househo
  2. B1Bii                     | B1Bii Who makes the main decisions about how money is spent on major/large house
  3. B1C2                      | B1C2. Keep money aside?
  4. B1C4                      | B1C4. You could can cope with an unexpected large expense such as a medical bill
  5. B1E1                      | B1E-Unable to pay expenses Housing
  6. B1E2                      | B1E-Unable to pay expenses Energy for heating or cooking
  7. B1E3                      | B1E-Unable to pay expenses Water for drinking or cleaning
  8. B1E4                      | B1E-Unable to pay expenses Transportation costs
  9. B1G                       | Think about the money you owe (for example to a bank, MFI, SACCO, a shopkeeper,
 10. B1H                       | B1H- Access to Emmergency
 11. B1Ha                      | B1Ha.  Other Access to emergency
 12. B1Hi                      | B1Hi. Source of loans/credit
 13. B1Hii                     | B1Hii. From which type of Savings
 14. B1J                       | B1J. Access in Case of Emergency
 15. B1K                       | B1K. Access in Case of Emergency
 16. B1M__1                    | B1M__1:A pension (including through an employer'swage deductions suchas NSSF) or
 17. B1M__2                    | B1M__2:Other long-term savings accounts whose balances you do not planon withdra
 18. B1M__3                    | B1M__3:Financial securities (stocks or bonds) that you plan on holding for at le
 19. B1N1                      | B1N1: How worried are you right now about not having enough money to pay for dai
 20. B1O                       | B1O:. Thinking about your longer-term financialgoals, such as, starting a busine
 21. CountFINANCIAL_HEALTH     | CountF
 22. B2A                       | B2A. Financial Advice
 23. B2Ai                      | B2Ai.  Financial Advice - Other
 24. B2Eiii                    | B2Eiii:Suppose you have have a large sum of money you would like to invest. Woul
 25. secFinancial_Awareness    | Questions answered in secFinancial_Awareness
 26. B3A__5                    | B3A__5:Money from NGO / Government/Social transfer (e.g pesa ya wazee, inua jami
 27. B3A__7                    | B3A. Earning money from investments, e.g. shares, stocks
 28. B3A__8                    | B3A. Pension/Annuity
 29. B3Ai                      | B3Ai.  Income Sources- Other
 30. B3Ci                      | B3Ci. In the last 12 months have you earned money in any of the following digita
 31. B3D__1_1                  | B3D__1.1: B3D. Received Payments:Cash
 32. B3D__2_1                  | B3D__2.1: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
 33. B3D__3_1                  | B3D__3.1: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
 34. B3D__4_1                  | B3D__4.1: B3D. Received Payments:Bank/SACCO/MFI paybill
 35. B3D__5_1                  | B3D__5.1: B3D. Received Payments:Merchant/business paybill/till number
 36. B3D__6_1                  | B3D__6.1: B3D. Received Payments:Bank cheque
 37. B3D__7_1                  | B3D__7.1: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
 38. B3D__8_1                  | B3D__8.1: B3D. Received Payments:Credit cards / debit cards
 39. B3D__9_1                  | B3D__9.1: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
 40. B3D__10_1                 | B3D__10.1: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
 41. B3D__11_1                 | B3D__11.1: B3D. Received Payments:Other (SPECIFY)
 42. B3D__98_1                 | B3D__98.1: B3D. Received Payments:Don't know
 43. B3D__99_1                 | B3D__99.1: B3D. Received Payments:Refused to Answer
 44. B3Di_1                    | B3Di.1: B3Di. Received Payments - Other
 45. B3E_1                     | B3E.1: B3E. Received Payments
 46. B3D__1_2                  | B3D__1.2: B3D. Received Payments:Cash
 47. B3D__2_2                  | B3D__2.2: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
 48. B3D__3_2                  | B3D__3.2: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
 49. B3D__4_2                  | B3D__4.2: B3D. Received Payments:Bank/SACCO/MFI paybill
 50. B3D__5_2                  | B3D__5.2: B3D. Received Payments:Merchant/business paybill/till number
 51. B3D__6_2                  | B3D__6.2: B3D. Received Payments:Bank cheque
 52. B3D__7_2                  | B3D__7.2: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
 53. B3D__8_2                  | B3D__8.2: B3D. Received Payments:Credit cards / debit cards
 54. B3D__9_2                  | B3D__9.2: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
 55. B3D__10_2                 | B3D__10.2: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
 56. B3D__11_2                 | B3D__11.2: B3D. Received Payments:Other (SPECIFY)
 57. B3D__98_2                 | B3D__98.2: B3D. Received Payments:Don't know
 58. B3D__99_2                 | B3D__99.2: B3D. Received Payments:Refused to Answer
 59. B3Di_2                    | B3Di.2: B3Di. Received Payments - Other
 60. B3E_2                     | B3E.2: B3E. Received Payments
 61. B3D__1_3                  | B3D__1.3: B3D. Received Payments:Cash
 62. B3D__2_3                  | B3D__2.3: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
 63. B3D__3_3                  | B3D__3.3: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
 64. B3D__4_3                  | B3D__4.3: B3D. Received Payments:Bank/SACCO/MFI paybill
 65. B3D__5_3                  | B3D__5.3: B3D. Received Payments:Merchant/business paybill/till number
 66. B3D__6_3                  | B3D__6.3: B3D. Received Payments:Bank cheque
 67. B3D__7_3                  | B3D__7.3: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
 68. B3D__8_3                  | B3D__8.3: B3D. Received Payments:Credit cards / debit cards
 69. B3D__9_3                  | B3D__9.3: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
 70. B3D__10_3                 | B3D__10.3: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
 71. B3D__11_3                 | B3D__11.3: B3D. Received Payments:Other (SPECIFY)
 72. B3D__98_3                 | B3D__98.3: B3D. Received Payments:Don't know
 73. B3D__99_3                 | B3D__99.3: B3D. Received Payments:Refused to Answer
 74. B3Di_3                    | B3Di.3: B3Di. Received Payments - Other
 75. B3E_3                     | B3E.3: B3E. Received Payments
 76. B3D__1_4                  | B3D__1.4: B3D. Received Payments:Cash
 77. B3D__2_4                  | B3D__2.4: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
 78. B3D__3_4                  | B3D__3.4: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
 79. B3D__4_4                  | B3D__4.4: B3D. Received Payments:Bank/SACCO/MFI paybill
 80. B3D__5_4                  | B3D__5.4: B3D. Received Payments:Merchant/business paybill/till number
 81. B3D__6_4                  | B3D__6.4: B3D. Received Payments:Bank cheque
 82. B3D__7_4                  | B3D__7.4: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
 83. B3D__8_4                  | B3D__8.4: B3D. Received Payments:Credit cards / debit cards
 84. B3D__9_4                  | B3D__9.4: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
 85. B3D__10_4                 | B3D__10.4: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
 86. B3D__11_4                 | B3D__11.4: B3D. Received Payments:Other (SPECIFY)
 87. B3D__98_4                 | B3D__98.4: B3D. Received Payments:Don't know
 88. B3D__99_4                 | B3D__99.4: B3D. Received Payments:Refused to Answer
 89. B3Di_4                    | B3Di.4: B3Di. Received Payments - Other
 90. B3E_4                     | B3E.4: B3E. Received Payments
 91. B3D__1_5                  | B3D__1.5: B3D. Received Payments:Cash
 92. B3D__2_5                  | B3D__2.5: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
 93. B3D__3_5                  | B3D__3.5: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
 94. B3D__4_5                  | B3D__4.5: B3D. Received Payments:Bank/SACCO/MFI paybill
 95. B3D__5_5                  | B3D__5.5: B3D. Received Payments:Merchant/business paybill/till number
 96. B3D__6_5                  | B3D__6.5: B3D. Received Payments:Bank cheque
 97. B3D__7_5                  | B3D__7.5: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
 98. B3D__8_5                  | B3D__8.5: B3D. Received Payments:Credit cards / debit cards
 99. B3D__9_5                  | B3D__9.5: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
100. B3D__10_5                 | B3D__10.5: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
101. B3D__11_5                 | B3D__11.5: B3D. Received Payments:Other (SPECIFY)
102. B3D__98_5                 | B3D__98.5: B3D. Received Payments:Don't know
103. B3D__99_5                 | B3D__99.5: B3D. Received Payments:Refused to Answer
104. B3Di_5                    | B3Di.5: B3Di. Received Payments - Other
105. B3E_5                     | B3E.5: B3E. Received Payments
106. B3D__1_6                  | B3D__1.6: B3D. Received Payments:Cash
107. B3D__2_6                  | B3D__2.6: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
108. B3D__3_6                  | B3D__3.6: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
109. B3D__4_6                  | B3D__4.6: B3D. Received Payments:Bank/SACCO/MFI paybill
110. B3D__5_6                  | B3D__5.6: B3D. Received Payments:Merchant/business paybill/till number
111. B3D__6_6                  | B3D__6.6: B3D. Received Payments:Bank cheque
112. B3D__7_6                  | B3D__7.6: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
113. B3D__8_6                  | B3D__8.6: B3D. Received Payments:Credit cards / debit cards
114. B3D__9_6                  | B3D__9.6: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
115. B3D__10_6                 | B3D__10.6: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
116. B3D__11_6                 | B3D__11.6: B3D. Received Payments:Other (SPECIFY)
117. B3D__98_6                 | B3D__98.6: B3D. Received Payments:Don't know
118. B3D__99_6                 | B3D__99.6: B3D. Received Payments:Refused to Answer
119. B3Di_6                    | B3Di.6: B3Di. Received Payments - Other
120. B3E_6                     | B3E.6: B3E. Received Payments
121. B3D__1_7                  | B3D__1.7: B3D. Received Payments:Cash
122. B3D__2_7                  | B3D__2.7: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
123. B3D__3_7                  | B3D__3.7: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
124. B3D__4_7                  | B3D__4.7: B3D. Received Payments:Bank/SACCO/MFI paybill
125. B3D__5_7                  | B3D__5.7: B3D. Received Payments:Merchant/business paybill/till number
126. B3D__6_7                  | B3D__6.7: B3D. Received Payments:Bank cheque
127. B3D__7_7                  | B3D__7.7: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
128. B3D__8_7                  | B3D__8.7: B3D. Received Payments:Credit cards / debit cards
129. B3D__9_7                  | B3D__9.7: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
130. B3D__10_7                 | B3D__10.7: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
131. B3D__11_7                 | B3D__11.7: B3D. Received Payments:Other (SPECIFY)
132. B3D__98_7                 | B3D__98.7: B3D. Received Payments:Don't know
133. B3D__99_7                 | B3D__99.7: B3D. Received Payments:Refused to Answer
134. B3Di_7                    | B3Di.7: B3Di. Received Payments - Other
135. B3E_7                     | B3E.7: B3E. Received Payments
136. B3D__1_8                  | B3D__1.8: B3D. Received Payments:Cash
137. B3D__2_8                  | B3D__2.8: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
138. B3D__3_8                  | B3D__3.8: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
139. B3D__4_8                  | B3D__4.8: B3D. Received Payments:Bank/SACCO/MFI paybill
140. B3D__5_8                  | B3D__5.8: B3D. Received Payments:Merchant/business paybill/till number
141. B3D__6_8                  | B3D__6.8: B3D. Received Payments:Bank cheque
142. B3D__7_8                  | B3D__7.8: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
143. B3D__8_8                  | B3D__8.8: B3D. Received Payments:Credit cards / debit cards
144. B3D__9_8                  | B3D__9.8: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
145. B3D__10_8                 | B3D__10.8: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
146. B3D__11_8                 | B3D__11.8: B3D. Received Payments:Other (SPECIFY)
147. B3D__98_8                 | B3D__98.8: B3D. Received Payments:Don't know
148. B3D__99_8                 | B3D__99.8: B3D. Received Payments:Refused to Answer
149. B3Di_8                    | B3Di.8: B3Di. Received Payments - Other
150. B3E_8                     | B3E.8: B3E. Received Payments
151. B3D__1_9                  | B3D__1.9: B3D. Received Payments:Cash
152. B3D__2_9                  | B3D__2.9: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Money
153. B3D__3_9                  | B3D__3.9: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
154. B3D__4_9                  | B3D__4.9: B3D. Received Payments:Bank/SACCO/MFI paybill
155. B3D__5_9                  | B3D__5.9: B3D. Received Payments:Merchant/business paybill/till number
156. B3D__6_9                  | B3D__6.9: B3D. Received Payments:Bank cheque
157. B3D__7_9                  | B3D__7.9: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ban
158. B3D__8_9                  | B3D__8.9: B3D. Received Payments:Credit cards / debit cards
159. B3D__9_9                  | B3D__9.9: B3D. Received Payments:No cash (Inkind payments in goods and/or servic
160. B3D__10_9                 | B3D__10.9: B3D. Received Payments:Digital /community currency e.g bitcoin, bangl
161. B3D__11_9                 | B3D__11.9: B3D. Received Payments:Other (SPECIFY)
162. B3D__98_9                 | B3D__98.9: B3D. Received Payments:Don't know
163. B3D__99_9                 | B3D__99.9: B3D. Received Payments:Refused to Answer
164. B3Di_9                    | B3Di.9: B3Di. Received Payments - Other
165. B3E_9                     | B3E.9: B3E. Received Payments
166. B3D__1_10                 | B3D__1.10: B3D. Received Payments:Cash
167. B3D__2_10                 | B3D__2.10: B3D. Received Payments:Mobile money (Send money) (M-Pesa, Airtel Mone
168. B3D__3_10                 | B3D__3.10: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bi
169. B3D__4_10                 | B3D__4.10: B3D. Received Payments:Bank/SACCO/MFI paybill
170. B3D__5_10                 | B3D__5.10: B3D. Received Payments:Merchant/business paybill/till number
171. B3D__6_10                 | B3D__6.10: B3D. Received Payments:Bank cheque
172. B3D__7_10                 | B3D__7.10: B3D. Received Payments:Bank transfer (e.g. EFT, SWIFT, Pesalink) / Ba
173. B3D__8_10                 | B3D__8.10: B3D. Received Payments:Credit cards / debit cards
174. B3D__9_10                 | B3D__9.10: B3D. Received Payments:No cash (Inkind payments in goods and/or servi
175. B3D__10_10                | B3D__10.10: B3D. Received Payments:Digital /community currency e.g bitcoin, bang
176. B3D__11_10                | B3D__11.10: B3D. Received Payments:Other (SPECIFY)
177. B3D__98_10                | B3D__98.10: B3D. Received Payments:Don't know
178. B3D__99_10                | B3D__99.10: B3D. Received Payments:Refused to Answer
179. B3Di_10                   | B3Di.10: B3Di. Received Payments - Other
180. B3E_10                    | B3E.10: B3E. Received Payments
181. B3H5                      | B3H5. Other Money from NGO / Government/Social transfe
182. B3Ii                      | B3Ii ) In the past one month, how much money did you get in total from all your
183. B3Iii                     | B3Iii. In the past 12 months, what was the most money you received in one calend
184. B3Iiii                    | B3Iiii) In the past 12 months, what was the least money you received in one cale
185. C1_10                     | C1-10. Registered on Mobile money
186. C1_11                     | C1_11. Registered on Mobile bank
187. C1_12                     | C1_12. Registered on a bank/microfinance Bank account
188. C1_12ai_CHK__0            | C1_12ai_Which Bank do you currently hold an account in:0
189. C1_12ai_CHK__1            | C1_12ai_Which Bank do you currently hold an account in:1
190. C1_12ai_CHK__2            | C1_12ai_Which Bank do you currently hold an account in:2
191. C1_12ai_CHK__3            | C1_12ai_Which Bank do you currently hold an account in:3
192. C1_12ai_CHK__4            | C1_12ai_Which Bank do you currently hold an account in:4
193. C1_12ai_CHK__5            | C1_12ai_Which Bank do you currently hold an account in:5
194. C1_12ai_CHK__6            | C1_12ai_Which Bank do you currently hold an account in:6
195. C1_12ai_CHK__7            | C1_12ai_Which Bank do you currently hold an account in:7
196. C1_12ai_CHK__8            | C1_12ai_Which Bank do you currently hold an account in:8
197. C1_12ai_CHK__9            | C1_12ai_Which Bank do you currently hold an account in:9
198. C1_12ai_CHK__10           | C1_12ai_Which Bank do you currently hold an account in:10
199. C1_12ai_CHK__11           | C1_12ai_Which Bank do you currently hold an account in:11
200. C1_12ai_CHK__12           | C1_12ai_Which Bank do you currently hold an account in:12
201. C1_12ai_CHK__13           | C1_12ai_Which Bank do you currently hold an account in:13
202. C1_12ai_CHK__14           | C1_12ai_Which Bank do you currently hold an account in:14
203. C1_12ai_CHK__15           | C1_12ai_Which Bank do you currently hold an account in:15
204. C1_12ai_CHK__16           | C1_12ai_Which Bank do you currently hold an account in:16
205. C1_12ai_CHK__17           | C1_12ai_Which Bank do you currently hold an account in:17
206. C1_12ai_CHK__18           | C1_12ai_Which Bank do you currently hold an account in:18
207. C1_12ai_CHK__19           | C1_12ai_Which Bank do you currently hold an account in:19
208. C1_12ai_CHK__20           | C1_12ai_Which Bank do you currently hold an account in:20
209. C1_12ai_CHK__21           | C1_12ai_Which Bank do you currently hold an account in:21
210. C1_12ai_CHK__22           | C1_12ai_Which Bank do you currently hold an account in:22
211. C1_12ai_CHK__23           | C1_12ai_Which Bank do you currently hold an account in:23
212. C1_12ai_CHK__24           | C1_12ai_Which Bank do you currently hold an account in:24
213. C1_12ai_CHK__25           | C1_12ai_Which Bank do you currently hold an account in:25
214. C1_12ai_CHK__26           | C1_12ai_Which Bank do you currently hold an account in:26
215. C1_12ai_CHK__27           | C1_12ai_Which Bank do you currently hold an account in:27

In [39]:
# ============================================================
# FINACCESS 2024 — TARGET VARIABLE SHORTLIST
# ============================================================

target_keywords = [
    "borrow",
    "borrowing",
    "loan",
    "credit",
    "save",
    "savings",
    "saving",
    "insurance",
    "income",
    "debt",
    "financial health",
    "financial vulnerability",
    "financial shock",
    "shock",
    "bank account",
    "account ownership",
    "formal financial",
    "financial access",
    "financial inclusion",
    "investment",
    "pension"
]

matches = []

for var, label in zip(meta.column_names, meta.column_labels):

    var_text = str(var).lower()
    label_text = str(label).lower()

    # Focus primarily on the QUESTION LABEL rather than
    # matching thousands of variables based on generic words.
    if any(keyword in label_text for keyword in target_keywords):
        matches.append((var, label))


print("=" * 110)
print("FINACCESS 2024 — POTENTIAL OUTCOME / TARGET VARIABLES")
print("=" * 110)

print(f"\nPotential matches: {len(matches)}\n")

for number, (var, label) in enumerate(matches, start=1):
    print(f"{number:3}. {var:25} | {label}")

print("\n" + "=" * 110)

==============================================================================================================
FINACCESS 2024 — POTENTIAL OUTCOME / TARGET VARIABLES
==============================================================================================================

Potential matches: 909

  1. B1Hi                      | B1Hi. Source of loans/credit
  2. B1Hii                     | B1Hii. From which type of Savings
  3. B1M__1                    | B1M__1:A pension (including through an employer'swage deductions suchas NSSF) or
  4. B1M__2                    | B1M__2:Other long-term savings accounts whose balances you do not planon withdra
  5. B3A__7                    | B3A. Earning money from investments, e.g. shares, stocks
  6. B3A__8                    | B3A. Pension/Annuity
  7. B3Ai                      | B3Ai.  Income Sources- Other
  8. B3D__8_1                  | B3D__8.1: B3D. Received Payments:Credit cards / debit cards
  9. B3D__8_2                  | B3D__8.2: B3D. Received Payments:Credit cards / debit cards
 10. B3D__8_3                  | B3D__8.3: B3D. Received Payments:Credit cards / debit cards
 11. B3D__8_4                  | B3D__8.4: B3D. Received Payments:Credit cards / debit cards
 12. B3D__8_5                  | B3D__8.5: B3D. Received Payments:Credit cards / debit cards
 13. B3D__8_6                  | B3D__8.6: B3D. Received Payments:Credit cards / debit cards
 14. B3D__8_7                  | B3D__8.7: B3D. Received Payments:Credit cards / debit cards
 15. B3D__8_8                  | B3D__8.8: B3D. Received Payments:Credit cards / debit cards
 16. B3D__8_9                  | B3D__8.9: B3D. Received Payments:Credit cards / debit cards
 17. B3D__8_10                 | B3D__8.10: B3D. Received Payments:Credit cards / debit cards
 18. C1_12                     | C1_12. Registered on a bank/microfinance Bank account
 19. C1_1a                     | C1-1a. Savings at Bank/ Microfinance Bank
 20. C1_1b                     | C1-1b. Savings at Microfinance Institutions
 21. C1_2                      | C1-2. Savings through mobile banking Platform
 22. C1_3                      | C1-3. Savings/keeping through mobile money provider
 23. C1_4                      | C1-4. Savings at a Sacco / Savings and Credit Cooperative organisation
 24. C1_5                      | C1-5. Savings at a chama
 25. C1_6                      | C1-6.   Savings with a group/group of friends
 26. C1_7                      | C1-7. Savings given to a family or friend to keep
 27. C1_8                      | C1-8. Savings you keep in a secret hiding place
 28. C1_9                      | C1-9. Savings you keep in a Digital savings App
 29. C1_13a                    | C1_13a. Personal loan/business loan from a commercial bank
 30. C1_13b                    | C1_13b. Personal loan/business loan from a microfinance bank
 31. C1_14                     | C1_14. Credit card
 32. C1_15                     | C1_15. Loan from mobile banking
 33. C1_16                     | C1_16. Loan from mobile provider (e.g Fuliza loan, Equity's Boostika)
 34. C1_17                     | C1_17. Loan from Sacco
 35. C1_18                     | C1_18. Loan from a microfinance institution
 36. C1_19                     | C1_19. Digital loans
 37. C1_20                     | C1-20. Loan from Shylocks
 38. C1_21                     | C1-21. Loan from a group/chama
 39. C1_22                     | C1_22:Loan from a government institution foreducation, agriculture or a developm
 40. C1_23                     | C1-23 Loan from Hustler Fund
 41. C1_24                     | C1-24 Loan from an employer
 42. C1_25                     | C1-25. Loan from family/friend/neighbour
 43. C1_26                     | C1-26. Cash loan from shopkeeper
 44. C1_27                     | C1-27. Taking goods and services on credit from a shopkeeper
 45. C1_28                     | C1_28:Loan / credits from buyer of your harvest / supplier of agricultural input
 46. C1_29                     | C1-29. Loan Lipa polepole / Hire Purchase
 47. C1_30                     | C1-30. Loan from Insurance
 48. C1_31                     | C1-31. Loan to buy / build a house (mortgage), or to buy land
 49. C1_32                     | C1-32. Postbank account
 50. C1_34                     | C1_34:Mutual Funds/ Unit Trust/ (mali, moneymarket funds) Real Estate Investment
 51. C1_36                     | C1-36. Motor insurance
 52. C1_38                     | C1-38. Other medical/health insurance policy, NOT NHIF/SHIF
 53. C1_39                     | C1-39. Other insurance e.g. fire, education, crop, life
 54. C1_41                     | C1-41. Employment/ Occupation pension scheme, NOT NSSF
 55. C1_42                     | C1-42. Other Retirement benefits / pension pla
 56. C2_15                     | C2_15. Loan from mobile banking
 57. C2_16                     | C2_16. Loan from mobile money provider
 58. C2_19                     | C2_19:Take digital loans that you get through the phone that you download throug
 59. C2_23                     | C2_23. Loan from Hustler Fund?
 60. D1A__1                    | D1A_1: Not contributing - Not received pension paymnent
 61. D1A__2                    | D1A_2: Not contributing - Received lumpsum pension payment
 62. D1Ai__4                   | D1Ai_4: Lack of saving incentives
 63. D1Ai__5                   | D1Ai_5: Distrust in pension providers
 64. D1Ai__7                   | D1Ai_7: Poor customer service from pension providers
 65. D1B__1                    | D1B_1: Lack of a regular job/can't afford a pension
 66. D1B__2                    | D1B_2: Lack of information about pensions
 67. D1B__3                    | D1B_3: Don't need/want a pension
 68. D1B__5                    | D1B_5: Lack of trust in pension providers
 69. D1B__6                    | D1B_6: Don't have an ID or other requirements to get a pension
 70. D1Ci                      | D1C_2: Other pension scheme
 71. D1E                       | D1E: Currently saving for retirement or receiving monthly pension
 72. D1Fi                      | D1Fii: Adequacy of Retirement benefits/pension payments
 73. D1H__2                    | D1H__2: Lost money from pension account
 74. D1I                       | D1I: How I lost my retirement benefits savings
 75. D1K__1                    | D1K_1: Contacted my pension scheme trustees to file my complaint
 76. D1Ma                      | D1Ma: Understanding of terms, conditions, prices for pension products
 77. D1Md                      | can easily access my funds in my retirement benfits/pension scheme account
 78. D2__1                     | D2_1: I lost my job/income
 79. D2__2                     | D2_2: I would like to continue with my insurance but I cant afford anymore
 80. D2__3                     | D2_3: I don't need insurance anymore/I have other options/family/savings
 81. D2__4                     | D2_4: I don't trust insurance providers/agents are dishnonest
 82. D3__1                     | D3_1: Don't have a regular income/job/too expensive/can't afford
 83. D3__2                     | D3_2: I don't understand or know about insurance/don't know where to get it
 84. D3__3                     | D3_3: I don't need insurance/it will not benefit me/I have other options to deal
 85. D3__4                     | D3_4: Insurance will bring bad luck- I don't believe in it
 86. D3__5                     | D3_5: I don't trust insurance providers/I don't trust that they will pay my clai
 87. D3__6                     | D3_6: I don't have an ID or the other requirements needed to get insurance polic
 88. D4__1                     | D4_1: Property (e.g House,building or contents insurance)
 89. D4__2                     | D4_2: Crop insurance
 90. D4__3                     | D4_3: Livestock insurance
 91. D4__4                     | D4_4: Life insurance
 92. D4__5                     | D4_5: Education insurance
 93. D4__7                     | D4_7: Fire Insurance
 94. D4__9                     | D4_9: Other insurance (SPECIFY)
 95. D5                        | D5: Ways acquired Insurance Policy
 96. D6                        | D6: Method of payment of the Insurance Premium
 97. D8__1                     | D8_1:Declined/Delayed/Underpaid insurance claim
 98. D8__2                     | D8_2: Discovered that your personal data was stolen or shared by insurance compa
 99. D8__5                     | D8_5: Cancelled policy due in insurance company collapsed
100. D10                       | D10: Register a complaint or resolve an issue regarding your insurance policy
101. D13_1                     | D13_1: Terms and conditions for the products and services at my insurance are cl
102. D13_2                     | D13_2: The products and services offered by  my insurance are fairly priced
103. D13_3                     | D13_3: I can easily communicate with my insurance if I need to
104. D13_4                     | D13_4. I can easily claim on my insurance policy if need arise
105. D13_5                     | D13_5. I can easily access my funds in my insurance account
106. D13_6                     | D13_6: I trust my insurance  provider
107. D13_7                     | D13_7: My insurance has good customer service
108. E1                        | E1: Have you applied for and been denied a loan in the last 12 months?
109. E2__6                     | E2_6: Credit-Only institution  (e
110. E2__7                     | E2_7: Digital loans that you get through App like Branch, Tala
111. E2__8                     | E2_8: Insurance company
112. E2__10                    | E2_10: Loan from a government institutions like AFC, HELB,Youth Fund (excluding
113. E3__16                    | the lender did not have float/money at the time of borrowing
114. E3__5                     | E3_5: Still had debt to pay
115. E3__7                     | E3_7: Bad credit history
116. E3__8                     | E3_8: No credit history
117. E3__9                     | E3_9: Income is low and unab
118. E3__11                    | E3_11: Savings too low
119. E4__1                     | E4. :Don't have money/income/job; Can't afford loans
120. E4__2                     | E4. :I don't know where or how to borrow
121. E4__3                     | E4__3:I don't like borrowing/loansdon't benefit me/there are no loan products th
122. E4__4                     | E4. :Loans are too risky for me
123. E4__5                     | E4. :I don't trust loan providers
124. E4__9                     | do not qualify/Bad credit history
125. E5__1                     | E5. :I lost my job/income
126. E5__2                     | E5__2:I can't afford to borrow at the moment/ it's too expensive
127. E5__3                     | E5__2:Loans are not benefitting me/there are no loan products that meet my needs
128. E5__4                     | E5. :Interest rates for loans are too high
129. E5__5                     | E5. :Loans have become too risky for me
130. E5__6                     | E5. :I don't trust loan providers
131. E5__7                     | E5. :Unethical debt recovery/harassment
132. E1iA                      | E1iA: Number of bank Loans past 12 months
133. E1iiA                     | E1iiA: Number of Outstanding bank Loans
134. E1iiiA                    | E1iiiA: Reason for taking bank loan product
135. E1iiiA_Other              | E1iiiA: Reason for taking Bank Loan Product; Others
136. E1ivA                     | E1ivA: Collateral used for Bank Loan
137. E1ivA_Other               | E1ivA: Collateral used for Bank Loan; Others
138. E1vA                      | E1vA: Frequency of bank loan repayments
139. E1vA_Other                | E1vA: Frequency of bank loan repayments; Others
140. E1viA                     | E1viA: Channels used for repaying bank loan
141. E1viA_Other               | E1viA: Channels used for repaying bank loan; Others
142. E1viiA                    | E1viiA: Amount of Bank loan borrowed
143. E1viiiA                   | E1viiiA: Amount of bank loan approved
144. E1ixA                     | E1ixA:  Date of borrowing the bank loan
145. E1xA                      | E1xA: Bank Loan Repayment due date
146. E1xiA                     | E1xiA: Outstanding bank loan amount
147. E1iB                      | E1iB: Number of microfinance bank loans past 12 months
148. E1iiB                     | E1iiB: Number of Outstanding microfinance bank loans
149. E1iiiB                    | E1iiiB: Reason for taking microfinance bank loan product
150. E1iiiB_Other              | E1iiiB: Reason for taking microfinance bank loan product; Others
151. E1ivB                     | E1ivB: Collateral used for microfinance bank loan
152. E1ivB_Other               | E1ivB: Collateral used for microfinance bank loan; Others
153. E1vB                      | E1vB: Frequency of microfinance bank loan repayments
154. E1vB_Other                | E1vB: Frequency of microfinance bank loan repayments; Others
155. E1viB                     | E1viB: Channels used for repaying microfinance bank loan
156. E1viB_Other               | E1viB: Channels used for repaying microfinance bank loan; Others
157. E1viiB                    | E1viiB: Amount of microfinance bank loan borrowed
158. E1viiiB                   | E1viiiB: Amount of microfinance bank loan approved
159. E1ixB                     | E1ixB: Date of borrowing the microfinance bank loan
160. E1xB                      | E1xB: Microfinance bank loan repayment due date
161. E1xiB                     | E1xiB: Outstanding microfinance bank loan amount
162. E1iC                      | E1iC: Number of bank overdraft loans past 12 months
163. E1iiC                     | E1iiC: Number of Outstanding bank overdraft loans
164. E1iiiC                    | E1iiiC: Reason for taking bank overdraft loan
165. E1iiiC_Other              | E1iiiC: Reason for taking bank overdraft loan product; Others
166. E1ivC                     | E1ivC: Collateral used for bank overdraft loan
167. E1ivC_Other               | E1ivC: Collateral used for bank overdraft loan; Others
168. E1vC                      | E1vC: Frequency of bank overdraft loan repayments
169. E1vC_Other                | E1vC: Frequency of bank overdraft loan repayments; Others
170. E1viC                     | E1viC: Channels used for repaying bank overdraft loan
171. E1viC_Other               | E1viC: Channels used for repaying bank overdraft loan; Others
172. E1viiC                    | E1viiC: Amount of bank overdraft loan borrowed
173. E1viiiC                   | E1viiiC: Amount of bank overdraft loan approved
174. E1ixC                     | E1ixC:  Date of borrowing the bank overdraft loan
175. E1xC                      | E1xC: Bank overdraft loan repayment due date
176. E1xiC                     | E1xiC: Outstanding bank overdraft loan amount
177. E1iD                      | E1iD: Number of creditcard loans past 12 months
178. E1iiiD                    | E1iiiD: Reason for taking creditcard loan product
179. E1iiiD_Other              | E1iiiD: Reason for taking creditcard loan; Others
180. E1vD                      | E1vD: Frequency of creditcard loan repayments
181. E1vD_Other                | E1vD: Frequency of creditcard loan repayments; Others
182. E1viD                     | E1viD: Channels used for repaying creditcard loan
183. E1viD_Other               | E1viD: Channels used for repaying creditcard loan; Others
184. E1viiD                    | E1viiD: Amount of creditcard loan borrowed
185. E1viiiD                   | E1viiiD: Amount of creditcard loan approved
186. E1ixD                     | E1ixD: Date of borrowing the creditcard loan
187. E1xD                      | E1xD: Creditcard loan repayment due date
188. E1iE                      | E1iE: Number of mobile banking loans past 12 months
189. E1iiE                     | E1iiE: Number of Outstanding mobile banking loans
190. E1iiiE                    | E1iiiE: Reason for taking mobile banking loan product
191. E1iiiE_Other              | E1iiiE: Reason for taking mobile banking loan product; Others
192. E1vE                      | E1vE: Frequency of mobile banking loan repayments
193. E1vE_Other                | E1vE: Frequency of mobile banking loan repayments; Others
194. E1viiE                    | E1viiE: Amount of mobile banking loan borrowed
195. E1viiiE                   | E1viiiE: Amount of mobile banking loan approved
196. E1ixE                     | E1ixE: Date of borrowing the mobile banking loan
197. E1xE                      | E1xE: Mobile banking loan repayment due date
198. E1xiE                     | E1xiE: Outstanding mobile banking loan amount
199. E1iF                      | E1iF: Number of mobile money provider loans past 12 months
200. E1iiF                     | E1iiF: Number of Outstanding mobile money provider loans
201. E1iiiF                    | E1iiiF: Reason for taking mobile money provider loan product
202. E1iiiF_Other              | E1iiiF: Reason for taking mobile money provider loan product; Others
203. E1viiF                    | E1viiF: Amount of mobile money provider loan borrowed
204. E1viiiF                   | E1viiiF: Amount of mobile money provider loan approved
205. E1ixF                     | E1ixF: Date of borrowing the mobile money provider loan
206. E1xiF                     | E1xiF: Outstanding mobile money provider loan amount
207. E1iG                      | E1iG: Number of Sacco loans past 12 months
208. E1iiG                     | E1iiG: Number of outstanding Sacco Loans
209. E1iiiG                    | E1iiiG: Reason for taking Sacco loan product
210. E1iiiG_Other              | E1iiiG: Reason for taking Sacco loan; Others
211. E1ivG                     | E1ivG: Collateral used for Sacco loan
212. E1ivG_Other               | E1ivG: Collateral used for Sacco loan; Others
213. E1vG                      | E1vG: Frequency of Sacco loan repayments
214. E1vG_Other                | E1vG: Frequency of Sacco loan repayments; Others
215. E1viG                     | E1viG: Channels used for repaying Sacco loan
216. E1viG_Other               | E1viG: Channels used for repaying Sacco loan; Others
217. E1viiG                    | E1viiG: Amount of Sacco loan borrowed
218. E1viiiG                   | E1viiiG: Amount of Sacco loan approved
219. E1ixG                     | E1ixG: Date of borrowing the Sacco loan
220. E1xG                      | E1xG: Sacco Loan Repayment due date
221. E1xiG                     | E1xiG: Outstanding Sacco loan amount
222. E1iH                      | E1iH: Number of MFI loans past 12 months
223. E1iiH                     | E1iiH: Number of outstanding MFI Loans
224. E1iiiH                    | E1iiiH: Reason for taking MFI loan product
225. E1iiiH_Other              | E1iiiH: Reason for taking MFI loan; Others
226. E1ivH                     | E1ivH: Collateral used for MFI loan
227. E1ivH_Other               | E1ivH: Collateral used for MFI loan; Others
228. E1vH                      | E1vH: Frequency of MFI loan repayments
229. E1vH_Other                | E1vH: Frequency of MFI loan repayments; Others
230. E1viH                     | E1viH: Channels used for repaying MFI loan
231. E1viH_Other               | E1viH: Channels used for repaying MFI loan; Others
232. E1viiH                    | E1viiH: Amount of MFI loan borrowed
233. E1viiiH                   | E1viiiH: Amount of MFI loan approved
234. E1ixH                     | E1ixH: Date of borrowing the MFI loan
235. E1xH                      | E1xH: MFI Loan Repayment due date
236. E1xiH                     | E1xiH: Outstanding MFI loan amount
237. E1iI                      | E1iI: Number of Digital loans past 12 months e.g. Tala, Zenka, Zash Loans etc
238. E1iiI                     | E1iiI: Number of outstanding Digital loans
239. E1iiiI                    | E1iiiI: Reason for taking Digital loan product
240. E1iiiI_Other              | E1iiiI: Reason for taking Digital loan; Others

In [40]:
variables = [
    "new_fh_score",
    "nfh_categories",
    "nfhi_13",
    "nfhi_21",
    "defaulted",
    "experienced_shock",
    "Loan_usage_fnl",
    "Digital_credit_usage_fnl",
    "formal_digital_loan_fnl",
    "formal_non_digital_loan_fnl",
    "E1",
    "E2E"
]

for var in variables:

    print("\n" + "=" * 75)
    print("VARIABLE:", var)

    if var not in df.columns:
        print("NOT FOUND")
        continue

    idx = meta.column_names.index(var)
    print("LABEL:", meta.column_labels[idx])

    print("\nVALUE COUNTS:")
    print(df[var].value_counts(dropna=False).head(20))

===========================================================================
VARIABLE: new_fh_score
LABEL: New financial health score

VALUE COUNTS:
new_fh_score
0.333333    4276
0.666667    3161
0.222222    2537
0.555556    2528
0.444444    2499
0.111111    2244
0.000000    1283
1.000000    1119
0.888889     720
0.777778     504
Name: count, dtype: int64

===========================================================================
VARIABLE: nfh_categories
LABEL: New financial health categories

VALUE COUNTS:
nfh_categories
2    9303
3    6064
1    5504
Name: count, dtype: int64

===========================================================================
VARIABLE: nfhi_13
LABEL: No debt stress past 3 months

VALUE COUNTS:
nfhi_13
1    13151
0     7720
Name: count, dtype: int64

===========================================================================
VARIABLE: nfhi_21
LABEL: Protection against shocks

VALUE COUNTS:
nfhi_21
0    16337
1     4534
Name: count, dtype: int64

===========================================================================
VARIABLE: defaulted
LABEL: Defaulted on Loans_Debt

VALUE COUNTS:
defaulted
0    13920
1     6951
Name: count, dtype: int64

===========================================================================
VARIABLE: experienced_shock
LABEL: experienced shock

VALUE COUNTS:
experienced_shock
0    11785
1     9086
Name: count, dtype: int64

===========================================================================
VARIABLE: Loan_usage_fnl
LABEL: Loan usage overall final

VALUE COUNTS:
Loan_usage_fnl
1    12775
0     8096
Name: count, dtype: int64

===========================================================================
VARIABLE: Digital_credit_usage_fnl
LABEL: Digital_credit_hustlerfund_mobile_money_provider_m_banking_& Digital_MFIs

VALUE COUNTS:
Digital_credit_usage_fnl
0    13620
1     7251
Name: count, dtype: int64

===========================================================================
VARIABLE: formal_digital_loan_fnl
LABEL: formal_digital_loan_fnl

VALUE COUNTS:
formal_digital_loan_fnl
0    13620
1     7251
Name: count, dtype: int64

===========================================================================
VARIABLE: formal_non_digital_loan_fnl
LABEL: Formal Non Digital Loans Final

VALUE COUNTS:
formal_non_digital_loan_fnl
0    17808
1     3063
Name: count, dtype: int64

===========================================================================
VARIABLE: E1
LABEL: E1: Have you applied for and been denied a loan in the last 12 months?

VALUE COUNTS:
E1
2     18196
1      2645
9        24
99        6
Name: count, dtype: int64

===========================================================================
VARIABLE: E2E
LABEL: E2E:  In the past 12 months were you either late paying any of your loans

VALUE COUNTS:
E2E
NaN    7720
3      6160
2      5015
1      1936
98       37
99        3
Name: count, dtype: int64

In [41]:
for var in ["defaulted", "nfh_categories", "nfhi_13", "nfhi_21", "E1", "E2E"]:

    print("\n" + "=" * 70)
    print(var)

    print("Variable label:")
    idx = meta.column_names.index(var)
    print(meta.column_labels[idx])

    print("\nValue labels:")
    print(meta.variable_value_labels.get(var))

======================================================================
defaulted
Variable label:
Defaulted on Loans_Debt

Value labels:
{0: 'No', 1: 'Yes'}

======================================================================
nfh_categories
Variable label:
New financial health categories

Value labels:
{1: 'High', 2: 'Medium', 3: 'Low'}

======================================================================
nfhi_13
Variable label:
No debt stress past 3 months

Value labels:
{0: 'No', 1: 'Yes'}

======================================================================
nfhi_21
Variable label:
Protection against shocks

Value labels:
{0: 'No', 1: 'Yes'}

======================================================================
E1
Variable label:
E1: Have you applied for and been denied a loan in the last 12 months?

Value labels:
{1: 'Yes', 2: 'No', 9: 'Not stated', 99: 'Refused to Answer'}

======================================================================
E2E
Variable label:
E2E:  In the past 12 months were you either late paying any of your loans

Value labels:
{1: "Didn't pay at all", 2: 'Paid late/Missed a payment/Paid less', 3: 'I did not default/always pay on time', 98: 'Don’t know', 99: 'Refused to Answer'}

In [42]:
print("Defaulted vs Loan Usage")
print(pd.crosstab(
    df["defaulted"],
    df["Loan_usage_fnl"],
    margins=True,
    dropna=False
))

Defaulted vs Loan Usage
Loan_usage_fnl     0      1    All
defaulted
0               8031   5889  13920
1                 65   6886   6951
All             8096  12775  20871

In [43]:
for var in ["defaulted", "E2E", "E2A", "E2H__2", "E2H__3", "E2H__4", "E2H__5"]:
    print("\n" + "=" * 70)
    print(var)

    idx = meta.column_names.index(var)
    print("LABEL:", meta.column_labels[idx])
    print("VALUE LABELS:", meta.variable_value_labels.get(var))

======================================================================
defaulted
LABEL: Defaulted on Loans_Debt
VALUE LABELS: {0: 'No', 1: 'Yes'}

======================================================================
E2E
LABEL: E2E:  In the past 12 months were you either late paying any of your loans
VALUE LABELS: {1: "Didn't pay at all", 2: 'Paid late/Missed a payment/Paid less', 3: 'I did not default/always pay on time', 98: 'Don’t know', 99: 'Refused to Answer'}

======================================================================
E2A
LABEL: E2A: In the past month how much did you spend to repay your outstanding loans?
VALUE LABELS: {98: 'Don’t know', 99: 'Refused to Answer'}

======================================================================
E2H__2
LABEL: E2H:Reduction in future loan limit
VALUE LABELS: None

======================================================================
E2H__3
LABEL: E2H:Negatively listed  at credit bureau
VALUE LABELS: None

======================================================================
E2H__4
LABEL: E2H:Denied access to future loan with the same lender
VALUE LABELS: None

======================================================================
E2H__5
LABEL: E2H:Denied access to future loan with another lender
VALUE LABELS: None

In [44]:
pd.crosstab(
    df["defaulted"],
    df["E2E"],
    margins=True,
    dropna=False
)

E2E         1.0   2.0   3.0  98.0  99.0   NaN    All
defaulted
0             0     0  6160    37     3  7720  13920
1          1936  5015     0     0     0     0   6951
All        1936  5015  6160    37     3     0  20871

In [45]:
pd.crosstab(
    df["defaulted"],
    df["E2E"],
    margins=True,
    dropna=False
)

E2E         1.0   2.0   3.0  98.0  99.0   NaN    All
defaulted
0             0     0  6160    37     3  7720  13920
1          1936  5015     0     0     0     0   6951
All        1936  5015  6160    37     3     0  20871

In [46]:
keywords = [
    "default",
    "repay",
    "late",
    "debt stress",
    "debt",
    "loan consequence",
    "denied",
    "credit bureau"
]

for var, label in zip(meta.column_names, meta.column_labels):

    text = f"{var} | {label}".lower()

    if any(keyword in text for keyword in keywords):
        print(f"{var:35} | {label}")

D2__5                               | D2_5: My claims were denied/underpaid
E1                                  | E1: Have you applied for and been denied a loan in the last 12 months?
E3__1                               | E3_1: Lack of collateral
E3__5                               | E3_5: Still had debt to pay
E4__7                               | E4. :I don't have collateral or a guarantor
E5__7                               | E5. :Unethical debt recovery/harassment
E1ivA                               | E1ivA: Collateral used for Bank Loan
E1ivA_Other                         | E1ivA: Collateral used for Bank Loan; Others
E1vA                                | E1vA: Frequency of bank loan repayments
E1vA_Other                          | E1vA: Frequency of bank loan repayments; Others
E1viA                               | E1viA: Channels used for repaying bank loan
E1viA_Other                         | E1viA: Channels used for repaying bank loan; Others
E1xA                                | E1xA: Bank Loan Repayment due date
E1ivB                               | E1ivB: Collateral used for microfinance bank loan
E1ivB_Other                         | E1ivB: Collateral used for microfinance bank loan; Others
E1vB                                | E1vB: Frequency of microfinance bank loan repayments
E1vB_Other                          | E1vB: Frequency of microfinance bank loan repayments; Others
E1viB                               | E1viB: Channels used for repaying microfinance bank loan
E1viB_Other                         | E1viB: Channels used for repaying microfinance bank loan; Others
E1xB                                | E1xB: Microfinance bank loan repayment due date
E1ivC                               | E1ivC: Collateral used for bank overdraft loan
E1ivC_Other                         | E1ivC: Collateral used for bank overdraft loan; Others
E1vC                                | E1vC: Frequency of bank overdraft loan repayments
E1vC_Other                          | E1vC: Frequency of bank overdraft loan repayments; Others
E1viC                               | E1viC: Channels used for repaying bank overdraft loan
E1viC_Other                         | E1viC: Channels used for repaying bank overdraft loan; Others
E1xC                                | E1xC: Bank overdraft loan repayment due date
E1vD                                | E1vD: Frequency of creditcard loan repayments
E1vD_Other                          | E1vD: Frequency of creditcard loan repayments; Others
E1viD                               | E1viD: Channels used for repaying creditcard loan
E1viD_Other                         | E1viD: Channels used for repaying creditcard loan; Others
E1xD                                | E1xD: Creditcard loan repayment due date
E1vE                                | E1vE: Frequency of mobile banking loan repayments
E1vE_Other                          | E1vE: Frequency of mobile banking loan repayments; Others
E1xE                                | E1xE: Mobile banking loan repayment due date
E1ivG                               | E1ivG: Collateral used for Sacco loan
E1ivG_Other                         | E1ivG: Collateral used for Sacco loan; Others
E1vG                                | E1vG: Frequency of Sacco loan repayments
E1vG_Other                          | E1vG: Frequency of Sacco loan repayments; Others
E1viG                               | E1viG: Channels used for repaying Sacco loan
E1viG_Other                         | E1viG: Channels used for repaying Sacco loan; Others
E1xG                                | E1xG: Sacco Loan Repayment due date
E1ivH                               | E1ivH: Collateral used for MFI loan
E1ivH_Other                         | E1ivH: Collateral used for MFI loan; Others
E1vH                                | E1vH: Frequency of MFI loan repayments
E1vH_Other                          | E1vH: Frequency of MFI loan repayments; Others
E1viH                               | E1viH: Channels used for repaying MFI loan
E1viH_Other                         | E1viH: Channels used for repaying MFI loan; Others
E1xH                                | E1xH: MFI Loan Repayment due date
E1vI                                | E1vI: Frequency of Digital loan repayments
E1vI_Other                          | E1vI: Frequency of Digital loan repayments; Others
E1viI                               | E1viI: Channels used for repaying Digital loan
E1viI_Other                         | E1viI: Channels used for repaying Digital loan; Others
E1xI                                | E1xI: Digital Loan Repayment due date
E1ivJ                               | E1ivJ: Collateral used for Shylock loan
E1ivJ_Other                         | E1ivJ: Collateral used for Shylock loan; Others
E1vJ                                | E1vJ: Frequency of Shylock loan repayments
E1vJ_Other                          | E1vJ: Frequency of Shylock loan repayments; Others
E1viJ                               | E1viJ: Channels used for repaying Shylock loan
E1viJ_Other                         | E1viJ: Channels used for repaying Shylock loan; Others
E1xJ                                | E1xJ: Shylock Loan Repayment due date
E1ivK                               | E1ivK: Collateral used for Group/Chama loan
E1ivK_Other                         | E1ivK: Collateral used for Group/Chama loan; Others
E1vK                                | E1vK: Frequency of Group/Chama loan repayments
E1vK_Other                          | E1vK: Frequency of Group/Chama loan repayments; Others
E1viK                               | E1viK: Channels used for repaying Group/Chama loan
E1viK_Other                         | E1viK: Channels used for repaying Group/Chama loan; Others
E1xK                                | E1xK: Group/Chama Loan Repayment due date
E1ivL                               | E1ivL: Collateral used for Government Institution loan
E1ivL_Other                         | E1ivL: Collateral used for Government Institution loan; Others
E1vL                                | E1vL: Frequency of Government Institution loan repayments
E1vL_Other                          | E1vL: Frequency of Government Institution loan repayments; Others
E1viL                               | E1viL: Channels used for repaying Government Institution loan
E1viL_Other                         | E1viL: Channels used for repaying Government Institution loan; Others
E1xL                                | E1xL: Government Institution Loan Repayment due date
E1vM                                | E1vM: Frequency of Hustlerfund loan repayments
E1vM_Other                          | E1vM: Frequency of Hustlerfund loan repayments; Others
E1viM                               | E1viM: Channels used for repaying Hustlerfund loan
E1viM_Other                         | E1viM: Channels used for repaying Hustlerfund loan; Others
E1xM                                | E1xM: Hustlerfund Loan Repayment due date
E1vN                                | E1vN: Frequency of Employer loan repayments
E1vN_Other                          | E1vN: Frequency of Employer loan repayments; Others
E1viN                               | E1viN: Channels used for repaying Employer loan
E1viN_Other                         | E1viN: Channels used for repaying Employer loan; Others
E1xN                                | E1xN: Employer Loan Repayment due date
E1vO                                | E1vO: Frequency of Family/Friend/Neighbour loan repayments
E1vO_Other                          | E1vO: Frequency of Family/Friend/Neighbour loan repayments; Others
E1viO                               | E1viO: Channels used for repaying Family/Friend/Neighbour loan
E1viO_Other                         | E1viO: Channels used for repaying Family/Friend/Neighbour loan; Others
E1xO                                | E1xO: Family/Friend/Neighbour Loan Repayment due date
E1ivP                               | E1ivP: Collateral used forShopkeeper loan
E1ivP_Other                         | E1ivP: Collateral used for Shopkeeper loan; Others
E1vP                                | E1vP: Frequency of Shopkeeper loan repayments
E1vP_Other                          | E1vP: Frequency of Shopkeeper loan repayments; Others
E1viP                               | E1viP: Channels used for repaying Shopkeeper loan
E1viP_Other                         | E1viP: Channels used for repaying Shopkeeper loan; Others
E1xP                                | E1xP: Shopkeeper Loan Repayment due date
E1vQ                                | E1vQ: Repayment frequency for goods purchased on credit from the shopkeeper
E1vQ_Other                          | E1vQ: Repayment frequency for goods purchased on credit from the shopkeeper; Oth
E1viQ                               | E1viQ: Channels used to repay for goods purchased on credit from the shopkeeper
E1viQ_Other                         | E1viQ: Channels used to repay for goods purchased on credit from the shopkeeper;
E1xQ                                | E1xQ: Due date for repaying goods purchased on credit from the shopkeeper
E1vS                                | E1vS: Repayment frequency for goods purchased on Hire purchase
E1vS_Other                          | E1vS: Repayment frequency for goods purchased on Hire purchase; Others
E1viS                               | E1viS: Channels used to repay for goods purchased on Hire purchase
E1viS_Other                         | E1viS: Channels used to repay for goods purchased on Hire purchase; Others
E1ivT                               | E1ivT: Collateral used for Insurance loan
E1ivT_Other                         | E1ivT: Collateral used for Insurance loan; Others
E1vT                                | E1vT: Frequency of Insurance loan repayments
E1vT_Other                          | E1vT: Frequency of Insurance loan repayments; Others
E1viT                               | E1viT: Channels used for repaying Insurance loan
E1viT_Other                         | E1viT: Channels used for repaying Insurance loan; Others
E1xT                                | E1xT: Insurance Loan Repayment due date
E1ivU                               | E1ivU: Collateral used for Mortgage loan
E1ivU_Other                         | E1ivU: Collateral used for Mortgage loan; Others
E1vU                                | E1vU: Frequency of Mortgage loan repayments
E1vU_Other                          | E1vU: Frequency of Mortgage loan repayments; Others
E1viU                               | E1viU: Channels used for repaying Mortgage loan
E1viU_Other                         | E1viU: Channels used for repaying Mortgage loan; Others
E1xU                                | E1xU: Mortgage Loan Repayment due date
E2A                                 | E2A: In the past month how much did you spend to repay your outstanding loans?
E2B                                 | E2B: In the past 12 months, did someone in your household repay or help to repay
E2D__1                              | Borrowed money to repay the loan
E2D__2                              | Used savings to repaythe loan
E2D__3                              | Sold/gave assets or belongings to repay the loan
E2D__4                              | Reduced expenditureson food products to repay the loan
E2D__5                              | Reduced expenditures on nonfood products to repay the loan
E2D__8                              | Deducted from my monthly pension payments to repay the loan
E2E                                 | E2E:  In the past 12 months were you either late paying any of your loans
E2G                                 | E2G: Reasons for Default
E2H__3                              | E2H:Negatively listed  at credit bureau
E2H__4                              | E2H:Denied access to future loan with the same lender
E2H__5                              | E2H:Denied access to future loan with another lender
E2H__11                             | E2H:Lender agreed to give me more time to repay
E3D__1                              | E3D: Who in your household did you repay a loan for?:Spouse/ partner
E3D__2                              | E3D: Who in your household did you repay a loan for?:Mother
E3D__3                              | E3D: Who in your household did you repay a loan for?:Father
E3D__4                              | E3D: Who in your household did you repay a loan for?:Daughter
E3D__5                              | E3D: Who in your household did you repay a loan for?:Son
E3D__6                              | E3D: Who in your household did you repay a loan for?:Other relative(s)
E3D__7                              | E3D: Who in your household did you repay a loan for?:Non relative(s)
E3D__99                             | E3D: Who in your household did you repay a loan for?:Refused to Answer
I1a__27                             | Lipa Later
J3__0                               | J3__0:Name of the Regulated SACCO
J3i                                 | J3i: Unregulated SACCO
M2ii__7                             | M2ii__7:Unethical debt recovery/harassment
M2ii__11                            | Defaulted on loan
M2ii__12                            | Denied credit
N2ii__6                             | N2ii__6:Unethical debt recovery/harassment
N10__4                              | N10__4:Through dishonesty or default by members
O5__12                              | O5_12 To repay a loan/ debt
P1_1__12                            | P1_1. Over indebtedness
P5a__3                              | P5a. Penalties due to late filing of returns
P22__8                              | P22. Reason(s) for worsened:High debt
Q8a__7                              | Q8a. Late delivery of inputs
Q24__8                              | Q24. High debt
Q24__12                             | Late delivery of inputs
S5__1                               | Educational activities (undertaking online courses, finding education-related ma
S5__2                               | Health related activities (seeking information/advice about medical conditions,
S5__3                               | Employment and career related activities (searching for jobs/vacancies etc.)
U19b__13                            | U19b. Own Land:To develop later
CalcExpenditure                     | Calculated Expenditure
defaulted                           | Defaulted on Loans_Debt
bank_usage                          | All commecial banks (+MFBs)  + mobile bank providers  regulated by CBK + Post Ba
Regulated_Saccos                    |  Regulated Sacco usage
Non_Regulated_Saccos                | Non Regulated Sacco usage
bank_usage_overall                  | All commecial banks (+MFBs)  + mobile bank providers (fuliza) regulated by CBK +
nfhi_13                             | No debt stress past 3 months
managedebt_perception               | Perception on managingexisting debts
Pay_off_debts_credit                | To pay off debts
Repay_debts_someone_else_credit     | To repay debts for someone else who was unable to repay such as family, friend
For_old_age_credit                  | To repay debts for someone else who was unable to repay such as family, friend

In [47]:
# Inspect metadata for the target itself
target = "defaulted"

idx = meta.column_names.index(target)

print("Variable:", meta.column_names[idx])
print("Label:", meta.column_labels[idx])

# Value labels attached to defaulted
print("\nValue labels:")
print(meta.variable_value_labels.get(target))

Variable: defaulted
Label: Defaulted on Loans_Debt

Value labels:
{0: 'No', 1: 'Yes'}

In [48]:
target_keywords = [
    "defaulted on loans",
    "defaulted",
    "default",
    "late paying",
    "didn't pay",
    "missed a payment",
    "repayment",
    "debt stress"
]

for var, label in zip(meta.column_names, meta.column_labels):
    text = str(label).lower()

    if any(k in text for k in target_keywords):
        print(f"{var:35} | {label}")

E1vA                                | E1vA: Frequency of bank loan repayments
E1vA_Other                          | E1vA: Frequency of bank loan repayments; Others
E1xA                                | E1xA: Bank Loan Repayment due date
E1vB                                | E1vB: Frequency of microfinance bank loan repayments
E1vB_Other                          | E1vB: Frequency of microfinance bank loan repayments; Others
E1xB                                | E1xB: Microfinance bank loan repayment due date
E1vC                                | E1vC: Frequency of bank overdraft loan repayments
E1vC_Other                          | E1vC: Frequency of bank overdraft loan repayments; Others
E1xC                                | E1xC: Bank overdraft loan repayment due date
E1vD                                | E1vD: Frequency of creditcard loan repayments
E1vD_Other                          | E1vD: Frequency of creditcard loan repayments; Others
E1xD                                | E1xD: Creditcard loan repayment due date
E1vE                                | E1vE: Frequency of mobile banking loan repayments
E1vE_Other                          | E1vE: Frequency of mobile banking loan repayments; Others
E1xE                                | E1xE: Mobile banking loan repayment due date
E1vG                                | E1vG: Frequency of Sacco loan repayments
E1vG_Other                          | E1vG: Frequency of Sacco loan repayments; Others
E1xG                                | E1xG: Sacco Loan Repayment due date
E1vH                                | E1vH: Frequency of MFI loan repayments
E1vH_Other                          | E1vH: Frequency of MFI loan repayments; Others
E1xH                                | E1xH: MFI Loan Repayment due date
E1vI                                | E1vI: Frequency of Digital loan repayments
E1vI_Other                          | E1vI: Frequency of Digital loan repayments; Others
E1xI                                | E1xI: Digital Loan Repayment due date
E1vJ                                | E1vJ: Frequency of Shylock loan repayments
E1vJ_Other                          | E1vJ: Frequency of Shylock loan repayments; Others
E1xJ                                | E1xJ: Shylock Loan Repayment due date
E1vK                                | E1vK: Frequency of Group/Chama loan repayments
E1vK_Other                          | E1vK: Frequency of Group/Chama loan repayments; Others
E1xK                                | E1xK: Group/Chama Loan Repayment due date
E1vL                                | E1vL: Frequency of Government Institution loan repayments
E1vL_Other                          | E1vL: Frequency of Government Institution loan repayments; Others
E1xL                                | E1xL: Government Institution Loan Repayment due date
E1vM                                | E1vM: Frequency of Hustlerfund loan repayments
E1vM_Other                          | E1vM: Frequency of Hustlerfund loan repayments; Others
E1xM                                | E1xM: Hustlerfund Loan Repayment due date
E1vN                                | E1vN: Frequency of Employer loan repayments
E1vN_Other                          | E1vN: Frequency of Employer loan repayments; Others
E1xN                                | E1xN: Employer Loan Repayment due date
E1vO                                | E1vO: Frequency of Family/Friend/Neighbour loan repayments
E1vO_Other                          | E1vO: Frequency of Family/Friend/Neighbour loan repayments; Others
E1xO                                | E1xO: Family/Friend/Neighbour Loan Repayment due date
E1vP                                | E1vP: Frequency of Shopkeeper loan repayments
E1vP_Other                          | E1vP: Frequency of Shopkeeper loan repayments; Others
E1xP                                | E1xP: Shopkeeper Loan Repayment due date
E1vQ                                | E1vQ: Repayment frequency for goods purchased on credit from the shopkeeper
E1vQ_Other                          | E1vQ: Repayment frequency for goods purchased on credit from the shopkeeper; Oth
E1vS                                | E1vS: Repayment frequency for goods purchased on Hire purchase
E1vS_Other                          | E1vS: Repayment frequency for goods purchased on Hire purchase; Others
E1vT                                | E1vT: Frequency of Insurance loan repayments
E1vT_Other                          | E1vT: Frequency of Insurance loan repayments; Others
E1xT                                | E1xT: Insurance Loan Repayment due date
E1vU                                | E1vU: Frequency of Mortgage loan repayments
E1vU_Other                          | E1vU: Frequency of Mortgage loan repayments; Others
E1xU                                | E1xU: Mortgage Loan Repayment due date
E2E                                 | E2E:  In the past 12 months were you either late paying any of your loans
E2G                                 | E2G: Reasons for Default
M2ii__11                            | Defaulted on loan
N10__4                              | N10__4:Through dishonesty or default by members
defaulted                           | Defaulted on Loans_Debt
nfhi_13                             | No debt stress past 3 months

In [49]:
pd.crosstab(
    df["defaulted"],
    df["M2ii__11"],
    margins=True
)

M2ii__11       0   1    All
defaulted
0          13910  10  13920
1           6927  24   6951
All        20837  34  20871

In [50]:
print(df["M2ii__11"].value_counts(dropna=False))

M2ii__11
0    20837
1       34
Name: count, dtype: int64

In [51]:
# Show all E-section variables in questionnaire order
for var, label in zip(meta.column_names, meta.column_labels):
    if var.startswith("E"):
        print(f"{var:35} | {label}")

E1                                  | E1: Have you applied for and been denied a loan in the last 12 months?
E2__1                               | E2_1: Commercial bank
E2__2                               | E2_2: Microfinance bank
E2__3                               | E2_3: SACCO/ M-SACCO
E2__4                               | E2_4: Mobile money provider (e.g.
E2__5                               | E2_5: Mobile banking (e.g. Mshwari
E2__6                               | E2_6: Credit-Only institution  (e
E2__7                               | E2_7: Digital loans that you get through App like Branch, Tala
E2__8                               | E2_8: Insurance company
E2__9                               | E2_9: Shylocks/Money Lenders
E2__10                              | E2_10: Loan from a government institutions like AFC, HELB,Youth Fund (excluding
E2__11                              | E2_11: Chama/groups
E2__12                              | E2_12: Shop keeper
E2__13                              | E2_13: Hustler fund
E2__14                              | relative/friend
E2__15                              | employer
E3__15                              | do not qualify
E3__16                              | the lender did not have float/money at the time of borrowing
E3__17                              | zero/low limit
E3__18                              | technological issues
E2__96                              | E2_96: Other (SPECIFY)
E2__98                              | E2_98: Don't know
E2__99                              | E299: Refused to Answer
E2_Other                            | E2_: Other
E3__1                               | E3_1: Lack of collateral
E3__2                               | E3_2: No pay slip
E3__3                               | E3_3: Lack of records
E3__4                               | E3_4: Lack of business propo
E3__5                               | E3_5: Still had debt to pay
E3__6                               | E3_6: No guarantor
E3__7                               | E3_7: Bad credit history
E3__8                               | E3_8: No credit history
E3__9                               | E3_9: Income is low and unab
E3__10                              | E3_10: Project is too risky
E3__11                              | E3_11: Savings too low
E3__12                              | E3_12: Was not given a reason
E3__13                              | E3_13: Negative listing by CRB
E3__14                              | E3_14: Discrimination (Gender/Culture
E3__96                              | E3_96: Other (SPECIFY)
E3__98                              | E3_98: Don't know
E3__99                              | E3_99: Refused to Answer
E3_Other                            | E3_: Other
E4__1                               | E4. :Don't have money/income/job; Can't afford loans
E4__2                               | E4. :I don't know where or how to borrow
E4__3                               | E4__3:I don't like borrowing/loansdon't benefit me/there are no loan products th
E4__4                               | E4. :Loans are too risky for me
E4__5                               | E4. :I don't trust loan providers
E4__6                               | E4. :I don't have an ID
E4__7                               | E4. :I don't have collateral or a guarantor
E4__8                               | E4. :My religion does not allow me
E4__9                               | do not qualify/Bad credit history
E4__96                              | E4. :Other (SPECIFY)/Nyingine (Taja)
E4__98                              | E4. :Don’t know/Sijui (DO NOT READ OUT)
E4__99                              | E4. :Refused to Answer/Kataa kujibu (DO NOT READ OUT
E4_Other_Specify                    | E4_Other_Specify. Other specify
E5__1                               | E5. :I lost my job/income
E5__2                               | E5__2:I can't afford to borrow at the moment/ it's too expensive
E5__3                               | E5__2:Loans are not benefitting me/there are no loan products that meet my needs
E5__4                               | E5. :Interest rates for loans are too high
E5__5                               | E5. :Loans have become too risky for me
E5__6                               | E5. :I don't trust loan providers
E5__7                               | E5. :Unethical debt recovery/harassment
E5__96                              | E5. :Other (SPECIFY)/Nyingine (Taja)
E5__98                              | E5. :Don’t know/Sijui(DO NOT READ OUT)
E5__99                              | E5__99:Refused to Answer/Kataa kujibu(DO NOT READ OUT)
E5_Others_Specify                   | E5_Others_Specify. Others specify
E1iA                                | E1iA: Number of bank Loans past 12 months
E1iiA                               | E1iiA: Number of Outstanding bank Loans
E1iiiA                              | E1iiiA: Reason for taking bank loan product
E1iiiA_Other                        | E1iiiA: Reason for taking Bank Loan Product; Others
E1ivA                               | E1ivA: Collateral used for Bank Loan
E1ivA_Other                         | E1ivA: Collateral used for Bank Loan; Others
E1vA                                | E1vA: Frequency of bank loan repayments
E1vA_Other                          | E1vA: Frequency of bank loan repayments; Others
E1viA                               | E1viA: Channels used for repaying bank loan
E1viA_Other                         | E1viA: Channels used for repaying bank loan; Others
E1viiA                              | E1viiA: Amount of Bank loan borrowed
E1viiiA                             | E1viiiA: Amount of bank loan approved
E1ixA                               | E1ixA:  Date of borrowing the bank loan
E1xA                                | E1xA: Bank Loan Repayment due date
E1xiA                               | E1xiA: Outstanding bank loan amount
E1iB                                | E1iB: Number of microfinance bank loans past 12 months
E1iiB                               | E1iiB: Number of Outstanding microfinance bank loans
E1iiiB                              | E1iiiB: Reason for taking microfinance bank loan product
E1iiiB_Other                        | E1iiiB: Reason for taking microfinance bank loan product; Others
E1ivB                               | E1ivB: Collateral used for microfinance bank loan
E1ivB_Other                         | E1ivB: Collateral used for microfinance bank loan; Others
E1vB                                | E1vB: Frequency of microfinance bank loan repayments
E1vB_Other                          | E1vB: Frequency of microfinance bank loan repayments; Others
E1viB                               | E1viB: Channels used for repaying microfinance bank loan
E1viB_Other                         | E1viB: Channels used for repaying microfinance bank loan; Others
E1viiB                              | E1viiB: Amount of microfinance bank loan borrowed
E1viiiB                             | E1viiiB: Amount of microfinance bank loan approved
E1ixB                               | E1ixB: Date of borrowing the microfinance bank loan
E1xB                                | E1xB: Microfinance bank loan repayment due date
E1xiB                               | E1xiB: Outstanding microfinance bank loan amount
E1iC                                | E1iC: Number of bank overdraft loans past 12 months
E1iiC                               | E1iiC: Number of Outstanding bank overdraft loans
E1iiiC                              | E1iiiC: Reason for taking bank overdraft loan
E1iiiC_Other                        | E1iiiC: Reason for taking bank overdraft loan product; Others
E1ivC                               | E1ivC: Collateral used for bank overdraft loan
E1ivC_Other                         | E1ivC: Collateral used for bank overdraft loan; Others
E1vC                                | E1vC: Frequency of bank overdraft loan repayments
E1vC_Other                          | E1vC: Frequency of bank overdraft loan repayments; Others
E1viC                               | E1viC: Channels used for repaying bank overdraft loan
E1viC_Other                         | E1viC: Channels used for repaying bank overdraft loan; Others
E1viiC                              | E1viiC: Amount of bank overdraft loan borrowed
E1viiiC                             | E1viiiC: Amount of bank overdraft loan approved
E1ixC                               | E1ixC:  Date of borrowing the bank overdraft loan
E1xC                                | E1xC: Bank overdraft loan repayment due date
E1xiC                               | E1xiC: Outstanding bank overdraft loan amount
E1iD                                | E1iD: Number of creditcard loans past 12 months
E1iiiD                              | E1iiiD: Reason for taking creditcard loan product
E1iiiD_Other                        | E1iiiD: Reason for taking creditcard loan; Others
E1vD                                | E1vD: Frequency of creditcard loan repayments
E1vD_Other                          | E1vD: Frequency of creditcard loan repayments; Others
E1viD                               | E1viD: Channels used for repaying creditcard loan
E1viD_Other                         | E1viD: Channels used for repaying creditcard loan; Others
E1viiD                              | E1viiD: Amount of creditcard loan borrowed
E1viiiD                             | E1viiiD: Amount of creditcard loan approved
E1ixD                               | E1ixD: Date of borrowing the creditcard loan
E1xD                                | E1xD: Creditcard loan repayment due date
E1iE                                | E1iE: Number of mobile banking loans past 12 months
E1iiE                               | E1iiE: Number of Outstanding mobile banking loans
E1iiiE                              | E1iiiE: Reason for taking mobile banking loan product
E1iiiE_Other                        | E1iiiE: Reason for taking mobile banking loan product; Others
E1vE                                | E1vE: Frequency of mobile banking loan repayments
E1vE_Other                          | E1vE: Frequency of mobile banking loan repayments; Others
E1viiE                              | E1viiE: Amount of mobile banking loan borrowed
E1viiiE                             | E1viiiE: Amount of mobile banking loan approved
E1ixE                               | E1ixE: Date of borrowing the mobile banking loan
E1xE                                | E1xE: Mobile banking loan repayment due date
E1xiE                               | E1xiE: Outstanding mobile banking loan amount
E1iF                                | E1iF: Number of mobile money provider loans past 12 months
E1iiF                               | E1iiF: Number of Outstanding mobile money provider loans
E1iiiF                              | E1iiiF: Reason for taking mobile money provider loan product
E1iiiF_Other                        | E1iiiF: Reason for taking mobile money provider loan product; Others
E1viiF                              | E1viiF: Amount of mobile money provider loan borrowed
E1viiiF                             | E1viiiF: Amount of mobile money provider loan approved
E1ixF                               | E1ixF: Date of borrowing the mobile money provider loan
E1xiF                               | E1xiF: Outstanding mobile money provider loan amount
E1iG                                | E1iG: Number of Sacco loans past 12 months
E1iiG                               | E1iiG: Number of outstanding Sacco Loans
E1iiiG                              | E1iiiG: Reason for taking Sacco loan product
E1iiiG_Other                        | E1iiiG: Reason for taking Sacco loan; Others
E1ivG                               | E1ivG: Collateral used for Sacco loan
E1ivG_Other                         | E1ivG: Collateral used for Sacco loan; Others
E1vG                                | E1vG: Frequency of Sacco loan repayments
E1vG_Other                          | E1vG: Frequency of Sacco loan repayments; Others
E1viG                               | E1viG: Channels used for repaying Sacco loan
E1viG_Other                         | E1viG: Channels used for repaying Sacco loan; Others
E1viiG                              | E1viiG: Amount of Sacco loan borrowed
E1viiiG                             | E1viiiG: Amount of Sacco loan approved
E1ixG                               | E1ixG: Date of borrowing the Sacco loan
E1xG                                | E1xG: Sacco Loan Repayment due date
E1xiG                               | E1xiG: Outstanding Sacco loan amount
E1iH                                | E1iH: Number of MFI loans past 12 months
E1iiH                               | E1iiH: Number of outstanding MFI Loans
E1iiiH                              | E1iiiH: Reason for taking MFI loan product
E1iiiH_Other                        | E1iiiH: Reason for taking MFI loan; Others
E1ivH                               | E1ivH: Collateral used for MFI loan
E1ivH_Other                         | E1ivH: Collateral used for MFI loan; Others
E1vH                                | E1vH: Frequency of MFI loan repayments
E1vH_Other                          | E1vH: Frequency of MFI loan repayments; Others
E1viH                               | E1viH: Channels used for repaying MFI loan
E1viH_Other                         | E1viH: Channels used for repaying MFI loan; Others
E1viiH                              | E1viiH: Amount of MFI loan borrowed
E1viiiH                             | E1viiiH: Amount of MFI loan approved
E1ixH                               | E1ixH: Date of borrowing the MFI loan
E1xH                                | E1xH: MFI Loan Repayment due date
E1xiH                               | E1xiH: Outstanding MFI loan amount
E1iI                                | E1iI: Number of Digital loans past 12 months e.g. Tala, Zenka, Zash Loans etc
E1iiI                               | E1iiI: Number of outstanding Digital loans
E1iiiI                              | E1iiiI: Reason for taking Digital loan product
E1iiiI_Other                        | E1iiiI: Reason for taking Digital loan; Others
E1vI                                | E1vI: Frequency of Digital loan repayments
E1vI_Other                          | E1vI: Frequency of Digital loan repayments; Others
E1viI                               | E1viI: Channels used for repaying Digital loan
E1viI_Other                         | E1viI: Channels used for repaying Digital loan; Others
E1viiI                              | E1viiI: Amount of Digital loan borrowed
E1viiiI                             | E1viiiI: Amount of Digital loan approved
E1ixI                               | E1ixI: Date of borrowing the Digital loan
E1xI                                | E1xI: Digital Loan Repayment due date
E1xiI                               | E1xiI: Outstanding Digital loan amount
E1iJ                                | E1iJ: Number of Shylock loans past 12 months ( e.g. loans not disbursed via phon
E1iiJ                               | E1iiJ: Number of outstanding Shylock loans
E1iiiJ                              | E1iiiJ: Reason for taking Shylock loan product
E1iiiJ_Other                        | E1iiiJ: Reason for taking Shylock loan; Others
E1ivJ                               | E1ivJ: Collateral used for Shylock loan
E1ivJ_Other                         | E1ivJ: Collateral used for Shylock loan; Others
E1vJ                                | E1vJ: Frequency of Shylock loan repayments
E1vJ_Other                          | E1vJ: Frequency of Shylock loan repayments; Others
E1viJ                               | E1viJ: Channels used for repaying Shylock loan
E1viJ_Other                         | E1viJ: Channels used for repaying Shylock loan; Others
E1viiJ                              | E1viiJ: Amount of Shylock loan borrowed
E1viiiJ                             | E1viiiJ: Amount of Shylock loan approved
E1ixJ                               | E1ixJ: Date of borrowing the Shylock loan
E1xJ                                | E1xJ: Shylock Loan Repayment due date
E1xiJ                               | E1xiJ: Outstanding Shylock loan amount
E1iK                                | E1iK: Number of Group/Chama loans past 12 months
E1iiK                               | E1iiK: Number of outstanding Group/Chama loans
E1iiiK                              | E1iiiK: Reason for taking Group/Chama loan product
E1iiiK_Other                        | E1iiiK: Reason for taking Shylock loan; Others
E1ivK                               | E1ivK: Collateral used for Group/Chama loan
E1ivK_Other                         | E1ivK: Collateral used for Group/Chama loan; Others
E1vK                                | E1vK: Frequency of Group/Chama loan repayments
E1vK_Other                          | E1vK: Frequency of Group/Chama loan repayments; Others
E1viK                               | E1viK: Channels used for repaying Group/Chama loan
E1viK_Other                         | E1viK: Channels used for repaying Group/Chama loan; Others
E1viiK                              | E1viiK: Amount of Group/Chama loan borrowed
E1viiiK                             | E1viiiK: Amount of Group/Chama loan approved
E1ixK                               | E1ixK: Date of borrowing the Group/Chama loan
E1xK                                | E1xK: Group/Chama Loan Repayment due date
E1xiK                               | E1xiK: Outstanding Group/Chama loan amount
E1iL                                | E1iL: Number of Government Institution loans past 12 months
E1iiL                               | E1iiL: Number of outstanding Government Institution loans
E1iiiL                              | E1iiiL: Reason for taking Government Institution loan product
E1iiiL_Other                        | E1iiiL: Reason for taking Government Institution loan; Others
E1ivL                               | E1ivL: Collateral used for Government Institution loan
E1ivL_Other                         | E1ivL: Collateral used for Government Institution loan; Others
E1vL                                | E1vL: Frequency of Government Institution loan repayments
E1vL_Other                          | E1vL: Frequency of Government Institution loan repayments; Others
E1viL                               | E1viL: Channels used for repaying Government Institution loan
E1viL_Other                         | E1viL: Channels used for repaying Government Institution loan; Others
E1viiL                              | E1viiL: Amount of Government Institution loan borrowed
E1viiiL                             | E1viiiL: Amount of Government Institution loan approved
E1ixL                               | E1ixL: Date of borrowing the Government Institution loan
E1xL                                | E1xL: Government Institution Loan Repayment due date
E1xiL                               | E1xiL: Outstanding Government Institution loan amount
E1iM                                | E1iM: Number of Hustlerfund loans past 12 months
E1iiM                               | E1iiM: Number of outstanding Hustlerfund loans
E1iiiM                              | E1iiiM: Reason for taking Hustlerfund loan product
E1iiiM_Other                        | E1iiiM: Reason for taking Hustlerfund loan; Others
E1vM                                | E1vM: Frequency of Hustlerfund loan repayments
E1vM_Other                          | E1vM: Frequency of Hustlerfund loan repayments; Others
E1viM                               | E1viM: Channels used for repaying Hustlerfund loan
E1viM_Other                         | E1viM: Channels used for repaying Hustlerfund loan; Others
E1viiM                              | E1viiM: Amount of Hustlerfund loan borrowed
E1viiiM                             | E1viiiM: Amount of Hustlerfund loan approved
E1ixM                               | E1ixM: Date of borrowing the Hustlerfund loan
E1xM                                | E1xM: Hustlerfund Loan Repayment due date
E1xiM                               | E1xiM: Outstanding Hustlerfund loan amount

In [52]:
# Search for variables related to survey weights, strata, clusters and PSUs

survey_keywords = [
    "weight",
    "weights",
    "sampling weight",
    "strata",
    "stratum",
    "cluster",
    "psu",
    "primary sampling",
    "enumeration area",
    "enumeration",
    "ea"
]

for var, label in zip(meta.column_names, meta.column_labels):
    text = f"{var} | {label}".lower()

    if any(keyword in text for keyword in survey_keywords):
        print(f"{var:40} | {label}")

A07                                      | A7. Cluster Number
A08                                      | A8. Cluster type
A19                                      | A19. Relation to HH Head
A14i                                     | A14i.How old is [NAME] in completed years?
A14iii                                   | Relationship of the household member to the head of household
A22ii                                    | A22ii) Number of children below 5 years
A22iii                                   | A22iii) Number of children below 24 years still in school or university?
A23                                      | A23 Household chronic disease status
A24ii                                    | A24i Difficulty hearing
B1Di                                     | B1Di: In the past 1 month, did you or any household member have to eat fewer mea
B1Diii                                   | B1Diii. Eat fewer meals
B1E2                                     | B1E-Unable to pay expenses Energy for heating or cooking
B1E3                                     | B1E-Unable to pay expenses Water for drinking or cleaning
B1F1                                     | B1F1. Frequency gone without medicine or medical treatment
CountFINANCIAL_HEALTH                    | CountF
B2Eii                                    | B2Eii: If you spent Ksh. 500 for your daily needsin July last year, Can your KSh
B2F                                      | B2F. Can Read SMS
B3A__3                                   | B3A. Casual worker/Seasonal Worker
B3A__7                                   | B3A. Earning money from investments, e.g. shares, stocks
B3A__98                                  | B3A. Don't know (DO NOT READ OUT)
B3A__99                                  | B3A. Refused to Answer (DO NOT READ OUT)
B3Ci                                     | B3Ci. In the last 12 months have you earned money in any of the following digita
B3Cii_2                                  | B3Cii_2 Digital delivery or motorbike service (Glovo, Uber Eats, SafeBoda, etc.)
B3Iiii                                   | B3Iiii) In the past 12 months, what was the least money you received in one cale
C1_34                                    | C1_34:Mutual Funds/ Unit Trust/ (mali, moneymarket funds) Real Estate Investment
C1_38                                    | C1-38. Other medical/health insurance policy, NOT NHIF/SHIF
D1A__2                                   | D1A_2: Not contributing - Received lumpsum pension payment
D1Ai__8                                  | D1Ai_8: Other reasons
D1B__7                                   | D1B_7: Other reasons
D1Bi                                     | D1Bi: Other reasons
D1Mb                                     | D1Mb: The scheme treats me fairly and with respect
D1Mc                                     | D1Mc: Communication with scheme is easy
D1Md                                     | can easily access my funds in my retirement benfits/pension scheme account
D2__6                                    | D2_6: Poor treatment/customer service
D3__3                                    | D3_3: I don't need insurance/it will not benefit me/I have other options to deal
D13_3                                    | D13_3: I can easily communicate with my insurance if I need to
D13_4                                    | D13_4. I can easily claim on my insurance policy if need arise
D13_5                                    | D13_5. I can easily access my funds in my insurance account
E3__12                                   | E3_12: Was not given a reason
E4__98                                   | E4. :Don’t know/Sijui (DO NOT READ OUT)
E4__99                                   | E4. :Refused to Answer/Kataa kujibu (DO NOT READ OUT
E5__98                                   | E5. :Don’t know/Sijui(DO NOT READ OUT)
E5__99                                   | E5__99:Refused to Answer/Kataa kujibu(DO NOT READ OUT)
E1iiiA                                   | E1iiiA: Reason for taking bank loan product
E1iiiA_Other                             | E1iiiA: Reason for taking Bank Loan Product; Others
E1iiiB                                   | E1iiiB: Reason for taking microfinance bank loan product
E1iiiB_Other                             | E1iiiB: Reason for taking microfinance bank loan product; Others
E1iiiC                                   | E1iiiC: Reason for taking bank overdraft loan
E1iiiC_Other                             | E1iiiC: Reason for taking bank overdraft loan product; Others
E1iiiD                                   | E1iiiD: Reason for taking creditcard loan product
E1iiiD_Other                             | E1iiiD: Reason for taking creditcard loan; Others
E1iiiE                                   | E1iiiE: Reason for taking mobile banking loan product
E1iiiE_Other                             | E1iiiE: Reason for taking mobile banking loan product; Others
E1iiiF                                   | E1iiiF: Reason for taking mobile money provider loan product
E1iiiF_Other                             | E1iiiF: Reason for taking mobile money provider loan product; Others
E1iiiG                                   | E1iiiG: Reason for taking Sacco loan product
E1iiiG_Other                             | E1iiiG: Reason for taking Sacco loan; Others
E1iiiH                                   | E1iiiH: Reason for taking MFI loan product
E1iiiH_Other                             | E1iiiH: Reason for taking MFI loan; Others
E1iiiI                                   | E1iiiI: Reason for taking Digital loan product
E1iiiI_Other                             | E1iiiI: Reason for taking Digital loan; Others
E1iiiJ                                   | E1iiiJ: Reason for taking Shylock loan product
E1iiiJ_Other                             | E1iiiJ: Reason for taking Shylock loan; Others
E1iiiK                                   | E1iiiK: Reason for taking Group/Chama loan product
E1iiiK_Other                             | E1iiiK: Reason for taking Shylock loan; Others
E1iiiL                                   | E1iiiL: Reason for taking Government Institution loan product
E1iiiL_Other                             | E1iiiL: Reason for taking Government Institution loan; Others
E1iiiM                                   | E1iiiM: Reason for taking Hustlerfund loan product
E1iiiM_Other                             | E1iiiM: Reason for taking Hustlerfund loan; Others
E1iiiN                                   | E1iiiN: Reason for taking the loan from Employer
E1iiiN_Other                             | E1iiiN: Reason for taking the loan from Employer; Others
E1iiiO                                   | E1iiiO: Reason for taking the loan from Family/Friend/Neighbour
E1iiiO_Other                             | E1iiiO: Reason for taking the loan from Family/Friend/Neighbour; Others
E1iiiP                                   | E1iiiP: Reason for taking Shopkeeper loan product
E1iiiP_Other                             | E1iiiP: Reason for taking Shopkeeper loan; Others
E1iiiQ                                   | E1iiiQ: Reason for taking goods on credit from Shopkeeper
E1iiiQ_Other                             | E1iiiQ: Reason for taking goods on credit from Shopkeeper; Others
E1iiiR                                   | E1iiiR: Reason for taking agricultural input loans
E1iiiR_Other                             | E1iiiR: Reason for taking agricultural input loans; Others
E1iiiS                                   | E1iiiS: Reason for taking Hire purchase loan
E1iiiS_Other                             | E1iiiS: Reason for taking Hire purchase loans; Others
E1iiiT                                   | E1iiiT: Reason for taking Insurance loan product
E1iiiT_Other                             | E1iiiT: Reason for taking Insurance loan; Others
E1iiiU                                   | E1iiiU: Reason for taking Mortgage loan product
E1iiiU_Other                             | E1iiiU: Reason for taking Mortgage loan; Others
E1_iii                                   | E1_iii: Loan Features
E2F__3                                   | Mobile bank (e.g. MShwari,KCB MPesa, MCoop Cash, Eazzy Loan, Timiza, HF Whizz)
E2G                                      | E2G: Reasons for Default
E2H__3                                   | E2H:Negatively listed  at credit bureau
F2__7                                    | F2_7: Other reasons for not currently saving
F3__7                                    | F3_7: Other reasons for not saving
F3__96                                   | F3: Reasons for NOT Saving:Other (SPECIFY)/Nyingine (Taja)
F1iiA                                    | F1iiA: Reason choosing this Saving Product in Bank/MFB
F1iiB                                    | F1iiB: Reason choosing this Saving Product in Microfinance Institutions (Credit
F1iiC                                    | F1iiC: Reason choosing this Saving Product in mobile banking Platform
F1iiD                                    | F1iiD: Reason choosing this Saving Product in Savings/keeping through mobile mon
F1iiE                                    | F1iiE: Reason choosing this Saving Product
F1iiF                                    | F1iiF: Reason choosing this Saving Product
F1iiG                                    | F1iiG: Reason for choosing this Saving Produc
F1iiH                                    | F1iiH: Reason choosing this Saving Product
F1iiI                                    | F1iiI: Reason choosing this Saving Product
F1iiJ                                    | F1iiJ: Reason choosing this Saving Product
F1iiK                                    | F1iiK: Reason choosing this Saving Product
F1iiL                                    | F1iiL. Reason choosing this Saving Product
F2Aii                                    | F2Aii:Mutual Funds/ Unit Trust/ (mali, money market funds) Real Estate Investmen
F2B__7                                   | F2B_7: Poor treatment/customer service
F2B__8                                   | F2B_8: Other reasons for stopping investing
F2C__8                                   | F2C_8: Other reasons for never investing
F2K__2                                   | F2K_2: Reached out to customer care
F2Mb                                     | F2Mb: My intermediary/service provider treats me fairly and with respect
F2Mc                                     | F2Mc: I can easily communicate with my intermediary/ervice provider if I need to
F2Mf                                     | F2Mf: My intermediary/ service provider cares for me/has my interests at heart
G7_Other                                 | G7_Other Reason
G12_Other                                | G12_Other Reason
H2__3                                    | H2__3:I have not heard of/ not aware/ don't understand banking/bank products
H2__98                                   | H2. Don’t know/Sijui(DO NOT READ OUT)
H2__99                                   | H2__99:Refused to Answer/Kataa kujibu(DO NOT READ OUT)
H2_Other_specify                         | H2_Other reasons for not having bank account
H4i_Other_specify                        | H4i_Other_specify. Other reasons you stopped using bank products and services
H4ii_Other_specify                       | H4ii. Other reasons you stopped using microfinance products/services
H5__27                                   | H5__27:Middle East Bank (K) Ltd
H5__98                                   | H5__98:Don't know (DO NOT READ
H5__99                                   | H5__99:Refused to Answer (DO NOT READ OUT
H10i__99                                 | Refused to Answer/Kataa kujibu (DO NOT READ OUT)99
H12__98                                  | H12. How did you lose money from your account:Don’t know/Sijui (DO NOT READ OUT)
H14__98                                  | H14__98:Don't know/Sijui(DO NOT READ OUT)
H16_3                                    | H16_3. I can easily communicate with my bank if I need to
H16_4                                    | H16_4.  I can easily access my funds in my bank account
H16_6                                    | H16_6. My bank cares for me/has my interests at heart
I1a__1                                   | Asante Financial Services (East Africa) Limited
I1a__9                                   | Creditarea Capital Limite
I1a__11                                  | Dexintec Kenya Limited T/A Easybuy
I1a__42                                  | Okolea International Limited
I1a__81                                  | Real People Kenya Limited
I6__98                                   | I6__98:Don't know/Sijui (DO NOT READ OUT)
I6__99                                   | I6__99:Refused to Answer/Kataa kujibu (DO NOT READ OUT)
I8_2                                     | I8_2.My [Institution] treats me fairly and with respect
I8_3                                     | I8_3. I can easily communicate with my [institution] if I need to
I8_4                                     | I8_4. I can easily access my funds in my institution account
J1__9                                    | J1_9: Poor treatment/customer service
J1_Other_Specify                         | J1_: Reason why you stopped using SACCO In Own Name
J2_Others_Specify                        | J2_: Other reasons for not having SACCO Account
J12_1                                    | J12_1: Terms and conditions  for product and services like fees are clear
J12_3                                    | J12_3: I can easily communicate with my SACCO
J12_4                                    | J12_4: I can easily access my funds at my SACCO Account
K2i__3                                   | K2i__3:I have not heard of/don't understand how to use mobile money
K2ii__5                                  | K2ii__5:Poor teatment/customer service
K2ii_Other                               | K2ii_Other:Other reasons (specify)
K14_3                                    | K14_3:I can easily communicate with my mobile money provider if I need to
K14_4                                    | K14_4:I can easily access my funds in my mobile money  account
M2i__3                                   | M2i__3:I have not heard of/don't understand how to use mobile banking
M3__4                                    | M3__4:Equitel/ Eazzy loan
M12_3                                    | M12_3:I can easily communicate with my mobile bank provider if I need to
M12_4                                    | M12_4:I can easily access my funds in my mobile banking account
N2i__6                                   | N2i__6:There are no chamas near me
N2i__11                                  | relocated to the area
N2ii__5                                  | N2ii__5:I don't trust my chama/poor leadership
N4__1                                    | N4__1:Welfare - We collect money to help each other through life events e.g. fun
N4__2                                    | N4__2:Lump sum-We collect money and give to each member a lump sum (pot) or gift
N12_1c                                   | N12_1c:I can easily communicate with my chama if I need to
N12_1d                                   | N12_1d:I can easily access my funds in my chama if I need to
N12_1f                                   | N12_1f:My chama treats me well and with respect
O3__12                                   | O3_12 Colleagues
O5__1                                    | O5_1 Medical reasons
O5__2                                    | O5_2 Death of friend or family member
O5__16                                   | Personal reasons/personal care
O5i                                      | O5. Financial Assistance Reason - Other
P1_1__11                                 | P1_1. Personal/Family reasons/Sickness/accident
P2i                                      | P2. Year Started
P2iia                                    | P2iia. Other area of operation - Before Feb 2020 (Precovid)
P5__6                                    | P5. High/increased cost of supplies
P5__12                                   | P5. Increased competition due to selling similar products
P5__18                                   | Pests & Diseases
P5__19                                   | Owner's health issues
P5__98                                   | P5. Don’t know (DO NOT READ OUT)
P5__99                                   | P5. Refused to Answer  (DO NOT READ OUT)
P5a__7                                   | P5a. Increased tax for my business
P8                                       | P8.  Reason choosing Financing Channel
P9                                       | P9. Reason Loan Business
P9i                                      | P9. Reason Loan Business - other
P11__99                                  | P11. "Refused to Answer  (DO NOT READ OUT)"
P12__2                                   | P12. Card reader machine (e.g. POS device / PDQ)
P21__2                                   | P21:Inceased customers/ high demand for my products or services
P21__3                                   | P21:Increased access to finance/ available credit
P21__8                                   | Better weather/ climatic conditions
P22__1                                   | P22. Reason(s) for worsened:Increased/ high cost of compliance
P22__3                                   | P22. Reason(s) for worsened:Reduced access to finance/ credit
P22__4                                   | P22. Reason(s) for worsened:Increased/ high competition
P22__5                                   | P22. Reason(s) for worsened:Increased/high cost of supplies
P22__6                                   | P22. Reason(s) for worsened:Insecurity
P22__7                                   | P22. Reason(s) for worsened:Poor infrastructure
P22__8                                   | P22. Reason(s) for worsened:High debt
P22__10                                  | Bad weather/ climatic conditions
P22__15                                  | Owner's health issues
P22__16                                  | Pests & Diseases
P22__96                                  | P22. Reason(s) for worsened:Others Specify
P22__98                                  | P22. Reason(s) for worsened:Don't know
P22__99                                  | P22. Reason(s) for worsened:Refused to Answer
Q1i                                      | Q1i. Unit of measure
Q2__4                                    | Lease/Rent (you don't own)
Q2__98                                   | Don’t know (DO NOT READ OUT)
Q2__99                                   | "Refused to Answer (DO NOT READ OUT)
Q7a__9                                   | Q7a. top five crops/livestock:Beans
Q7a__10                                  | Q7a. top five crops/livestock:Cowpeas
Q7a__11                                  | Q7a. top five crops/livestock:Pigeon peas
Q7a__25                                  | Q7a. top five crops/livestock:Tea
Q7a__37                                  | Q7a. top five crops/livestock:Goat - meat
Q7a__50                                  | black  beans
Q7a__63                                  | French beans
Q7a__72                                  | Peas
Q7a__76                                  | Wheat
Q7a__83                                  | cereal
Q7a__86                                  | guinea fowl
Q7a__89                                  | pineapple
Q8a__2                                   | Q8a. Pests and diseases
Q8a__3                                   | Q8a. Floods/ Heavy Rains
Q8a__4                                   | Q8a. High/Increased cost of inputs
Q10                                      | Q10. Main Source of Finance Reason
Q10i                                     | Q10. Main Source of Finance Reason - Other
Q11                                      | Q11. Reason LoanAgriculture
Q11i                                     | Q11i. Reason Loan Agriculture - Other
Q16__4                                   | Q16. regular use of:Internet search engines eg. Google

In [53]:
# Replace these with the variables discovered above
candidate_vars = [
    # "weight_variable",
    # "strata_variable",
    # "psu_variable"
]

for var in candidate_vars:
    print("\n" + "=" * 80)
    print(f"VARIABLE: {var}")
    print(f"LABEL: {meta.column_labels[meta.column_names.index(var)]}")
    print(f"TYPE: {df[var].dtype}")
    print(f"UNIQUE VALUES: {df[var].nunique(dropna=False)}")
    print(df[var].describe())

In [54]:
for var in candidate_vars:
    print("\n" + "=" * 80)
    print(f"VALUE COUNTS: {var}")
    print(df[var].value_counts(dropna=False).head(30))

In [55]:
# Search metadata for anything potentially related to sampling design

keywords = [
    "strat",
    "sampling",
    "sample",
    "enumeration",
    "EA",
    "cluster",
    "county",
    "urban",
    "rural",
    "region"
]

for var, label in zip(meta.column_names, meta.column_labels):
    text = f"{var} | {label}".lower()

    if any(k.lower() in text for k in keywords):
        print(f"{var:40} | {label}")

county                                   | County
A07                                      | A7. Cluster Number
A08                                      | A8. Cluster type
A19                                      | A19. Relation to HH Head
A14i                                     | A14i.How old is [NAME] in completed years?
A14iii                                   | Relationship of the household member to the head of household
A22ii                                    | A22ii) Number of children below 5 years
A22iii                                   | A22iii) Number of children below 24 years still in school or university?
A23                                      | A23 Household chronic disease status
A24ii                                    | A24i Difficulty hearing
B1Di                                     | B1Di: In the past 1 month, did you or any household member have to eat fewer mea
B1Diii                                   | B1Diii. Eat fewer meals
B1E2                                     | B1E-Unable to pay expenses Energy for heating or cooking
B1E3                                     | B1E-Unable to pay expenses Water for drinking or cleaning
B1F1                                     | B1F1. Frequency gone without medicine or medical treatment
CountFINANCIAL_HEALTH                    | CountF
B2Eii                                    | B2Eii: If you spent Ksh. 500 for your daily needsin July last year, Can your KSh
B2F                                      | B2F. Can Read SMS
B3A__3                                   | B3A. Casual worker/Seasonal Worker
B3A__7                                   | B3A. Earning money from investments, e.g. shares, stocks
B3A__98                                  | B3A. Don't know (DO NOT READ OUT)
B3A__99                                  | B3A. Refused to Answer (DO NOT READ OUT)
B3Ci                                     | B3Ci. In the last 12 months have you earned money in any of the following digita
B3Cii_2                                  | B3Cii_2 Digital delivery or motorbike service (Glovo, Uber Eats, SafeBoda, etc.)
B3Iiii                                   | B3Iiii) In the past 12 months, what was the least money you received in one cale
C1_34                                    | C1_34:Mutual Funds/ Unit Trust/ (mali, moneymarket funds) Real Estate Investment
C1_38                                    | C1-38. Other medical/health insurance policy, NOT NHIF/SHIF
D1Ai__8                                  | D1Ai_8: Other reasons
D1B__7                                   | D1B_7: Other reasons
D1B__8                                   | In the Process of Registration/Planning to Register
D1Bi                                     | D1Bi: Other reasons
D1Mb                                     | D1Mb: The scheme treats me fairly and with respect
D1Mc                                     | D1Mc: Communication with scheme is easy
D1Md                                     | can easily access my funds in my retirement benfits/pension scheme account
D2__6                                    | D2_6: Poor treatment/customer service
D3__3                                    | D3_3: I don't need insurance/it will not benefit me/I have other options to deal
D13_3                                    | D13_3: I can easily communicate with my insurance if I need to
D13_4                                    | D13_4. I can easily claim on my insurance policy if need arise
D13_5                                    | D13_5. I can easily access my funds in my insurance account
E3__12                                   | E3_12: Was not given a reason
E4__98                                   | E4. :Don’t know/Sijui (DO NOT READ OUT)
E4__99                                   | E4. :Refused to Answer/Kataa kujibu (DO NOT READ OUT
E5__98                                   | E5. :Don’t know/Sijui(DO NOT READ OUT)
E5__99                                   | E5__99:Refused to Answer/Kataa kujibu(DO NOT READ OUT)
E1iiiA                                   | E1iiiA: Reason for taking bank loan product
E1iiiA_Other                             | E1iiiA: Reason for taking Bank Loan Product; Others
E1iiiB                                   | E1iiiB: Reason for taking microfinance bank loan product
E1iiiB_Other                             | E1iiiB: Reason for taking microfinance bank loan product; Others
E1iiiC                                   | E1iiiC: Reason for taking bank overdraft loan
E1iiiC_Other                             | E1iiiC: Reason for taking bank overdraft loan product; Others
E1iiiD                                   | E1iiiD: Reason for taking creditcard loan product
E1iiiD_Other                             | E1iiiD: Reason for taking creditcard loan; Others
E1iiiE                                   | E1iiiE: Reason for taking mobile banking loan product
E1iiiE_Other                             | E1iiiE: Reason for taking mobile banking loan product; Others
E1iiiF                                   | E1iiiF: Reason for taking mobile money provider loan product
E1iiiF_Other                             | E1iiiF: Reason for taking mobile money provider loan product; Others
E1iiiG                                   | E1iiiG: Reason for taking Sacco loan product
E1iiiG_Other                             | E1iiiG: Reason for taking Sacco loan; Others
E1iiiH                                   | E1iiiH: Reason for taking MFI loan product
E1iiiH_Other                             | E1iiiH: Reason for taking MFI loan; Others
E1iiiI                                   | E1iiiI: Reason for taking Digital loan product
E1iiiI_Other                             | E1iiiI: Reason for taking Digital loan; Others
E1iiiJ                                   | E1iiiJ: Reason for taking Shylock loan product
E1iiiJ_Other                             | E1iiiJ: Reason for taking Shylock loan; Others
E1iiiK                                   | E1iiiK: Reason for taking Group/Chama loan product
E1iiiK_Other                             | E1iiiK: Reason for taking Shylock loan; Others
E1iiiL                                   | E1iiiL: Reason for taking Government Institution loan product
E1iiiL_Other                             | E1iiiL: Reason for taking Government Institution loan; Others
E1iiiM                                   | E1iiiM: Reason for taking Hustlerfund loan product
E1iiiM_Other                             | E1iiiM: Reason for taking Hustlerfund loan; Others
E1iiiN                                   | E1iiiN: Reason for taking the loan from Employer
E1iiiN_Other                             | E1iiiN: Reason for taking the loan from Employer; Others
E1iiiO                                   | E1iiiO: Reason for taking the loan from Family/Friend/Neighbour
E1iiiO_Other                             | E1iiiO: Reason for taking the loan from Family/Friend/Neighbour; Others
E1iiiP                                   | E1iiiP: Reason for taking Shopkeeper loan product
E1iiiP_Other                             | E1iiiP: Reason for taking Shopkeeper loan; Others
E1iiiQ                                   | E1iiiQ: Reason for taking goods on credit from Shopkeeper
E1iiiQ_Other                             | E1iiiQ: Reason for taking goods on credit from Shopkeeper; Others
E1iiiR                                   | E1iiiR: Reason for taking agricultural input loans
E1iiiR_Other                             | E1iiiR: Reason for taking agricultural input loans; Others
E1iiiS                                   | E1iiiS: Reason for taking Hire purchase loan
E1iiiS_Other                             | E1iiiS: Reason for taking Hire purchase loans; Others
E1iiiT                                   | E1iiiT: Reason for taking Insurance loan product
E1iiiT_Other                             | E1iiiT: Reason for taking Insurance loan; Others
E1iiiU                                   | E1iiiU: Reason for taking Mortgage loan product
E1iiiU_Other                             | E1iiiU: Reason for taking Mortgage loan; Others
E1_iii                                   | E1_iii: Loan Features
E2F__3                                   | Mobile bank (e.g. MShwari,KCB MPesa, MCoop Cash, Eazzy Loan, Timiza, HF Whizz)
E2G                                      | E2G: Reasons for Default
E2H__3                                   | E2H:Negatively listed  at credit bureau
F2__7                                    | F2_7: Other reasons for not currently saving
F3__7                                    | F3_7: Other reasons for not saving
F3__96                                   | F3: Reasons for NOT Saving:Other (SPECIFY)/Nyingine (Taja)
F1iiA                                    | F1iiA: Reason choosing this Saving Product in Bank/MFB
F1iiB                                    | F1iiB: Reason choosing this Saving Product in Microfinance Institutions (Credit
F1iiC                                    | F1iiC: Reason choosing this Saving Product in mobile banking Platform
F1iiD                                    | F1iiD: Reason choosing this Saving Product in Savings/keeping through mobile mon
F1iiE                                    | F1iiE: Reason choosing this Saving Product
F1iiF                                    | F1iiF: Reason choosing this Saving Product
F1iiG                                    | F1iiG: Reason for choosing this Saving Produc
F1iiH                                    | F1iiH: Reason choosing this Saving Product
F1iiI                                    | F1iiI: Reason choosing this Saving Product
F1iiJ                                    | F1iiJ: Reason choosing this Saving Product
F1iiK                                    | F1iiK: Reason choosing this Saving Product
F1iiL                                    | F1iiL. Reason choosing this Saving Product
F2Aii                                    | F2Aii:Mutual Funds/ Unit Trust/ (mali, money market funds) Real Estate Investmen
F2B__7                                   | F2B_7: Poor treatment/customer service
F2B__8                                   | F2B_8: Other reasons for stopping investing
F2C__8                                   | F2C_8: Other reasons for never investing
F2K__2                                   | F2K_2: Reached out to customer care
F2Mb                                     | F2Mb: My intermediary/service provider treats me fairly and with respect
F2Mc                                     | F2Mc: I can easily communicate with my intermediary/ervice provider if I need to
F2Mf                                     | F2Mf: My intermediary/ service provider cares for me/has my interests at heart
G7_Other                                 | G7_Other Reason
G12_Other                                | G12_Other Reason
H2__3                                    | H2__3:I have not heard of/ not aware/ don't understand banking/bank products
H2__98                                   | H2. Don’t know/Sijui(DO NOT READ OUT)
H2__99                                   | H2__99:Refused to Answer/Kataa kujibu(DO NOT READ OUT)
H2_Other_specify                         | H2_Other reasons for not having bank account
H4i_Other_specify                        | H4i_Other_specify. Other reasons you stopped using bank products and services
H4ii_Other_specify                       | H4ii. Other reasons you stopped using microfinance products/services
H5__27                                   | H5__27:Middle East Bank (K) Ltd
H5__98                                   | H5__98:Don't know (DO NOT READ
H5__99                                   | H5__99:Refused to Answer (DO NOT READ OUT
H10i__99                                 | Refused to Answer/Kataa kujibu (DO NOT READ OUT)99
H12__98                                  | H12. How did you lose money from your account:Don’t know/Sijui (DO NOT READ OUT)
H14__98                                  | H14__98:Don't know/Sijui(DO NOT READ OUT)
H16_3                                    | H16_3. I can easily communicate with my bank if I need to
H16_4                                    | H16_4.  I can easily access my funds in my bank account
H16_6                                    | H16_6. My bank cares for me/has my interests at heart
I1a__1                                   | Asante Financial Services (East Africa) Limited
I1a__9                                   | Creditarea Capital Limite
I1a__11                                  | Dexintec Kenya Limited T/A Easybuy
I1a__42                                  | Okolea International Limited
I1a__81                                  | Real People Kenya Limited
I6__98                                   | I6__98:Don't know/Sijui (DO NOT READ OUT)
I6__99                                   | I6__99:Refused to Answer/Kataa kujibu (DO NOT READ OUT)
I8_2                                     | I8_2.My [Institution] treats me fairly and with respect
I8_3                                     | I8_3. I can easily communicate with my [institution] if I need to
I8_4                                     | I8_4. I can easily access my funds in my institution account
J1__9                                    | J1_9: Poor treatment/customer service
J1_Other_Specify                         | J1_: Reason why you stopped using SACCO In Own Name
J2_Others_Specify                        | J2_: Other reasons for not having SACCO Account
J12_1                                    | J12_1: Terms and conditions  for product and services like fees are clear
J12_3                                    | J12_3: I can easily communicate with my SACCO
J12_4                                    | J12_4: I can easily access my funds at my SACCO Account
K2i__3                                   | K2i__3:I have not heard of/don't understand how to use mobile money
K2ii__5                                  | K2ii__5:Poor teatment/customer service
K2ii_Other                               | K2ii_Other:Other reasons (specify)
K14_3                                    | K14_3:I can easily communicate with my mobile money provider if I need to
K14_4                                    | K14_4:I can easily access my funds in my mobile money  account
M2i__3                                   | M2i__3:I have not heard of/don't understand how to use mobile banking
M3__4                                    | M3__4:Equitel/ Eazzy loan
M12_3                                    | M12_3:I can easily communicate with my mobile bank provider if I need to
M12_4                                    | M12_4:I can easily access my funds in my mobile banking account
N2i__6                                   | N2i__6:There are no chamas near me
N2i__11                                  | relocated to the area
N2ii__5                                  | N2ii__5:I don't trust my chama/poor leadership
N4__1                                    | N4__1:Welfare - We collect money to help each other through life events e.g. fun
N4__2                                    | N4__2:Lump sum-We collect money and give to each member a lump sum (pot) or gift
N8__4                                    | N8__4:Have a certificate of registration (e.g. registrar of companies, social se
N12_1c                                   | N12_1c:I can easily communicate with my chama if I need to
N12_1d                                   | N12_1d:I can easily access my funds in my chama if I need to
N12_1f                                   | N12_1f:My chama treats me well and with respect
O3__5                                    | O3_5 County Government
O3__12                                   | O3_12 Colleagues
O5__1                                    | O5_1 Medical reasons
O5__2                                    | O5_2 Death of friend or family member
O5__16                                   | Personal reasons/personal care
O5i                                      | O5. Financial Assistance Reason - Other
P1_1__11                                 | P1_1. Personal/Family reasons/Sickness/accident
P2i                                      | P2. Year Started
P2iia                                    | P2iia. Other area of operation - Before Feb 2020 (Precovid)
P3                                       | P3. County
P5__6                                    | P5. High/increased cost of supplies
P5__12                                   | P5. Increased competition due to selling similar products
P5__18                                   | Pests & Diseases
P5__19                                   | Owner's health issues
P5__98                                   | P5. Don’t know (DO NOT READ OUT)
P5__99                                   | P5. Refused to Answer  (DO NOT READ OUT)
P5a__7                                   | P5a. Increased tax for my business
P8                                       | P8.  Reason choosing Financing Channel
P9                                       | P9. Reason Loan Business
P9i                                      | P9. Reason Loan Business - other
P11__99                                  | P11. "Refused to Answer  (DO NOT READ OUT)"
P12__2                                   | P12. Card reader machine (e.g. POS device / PDQ)
P21__2                                   | P21:Inceased customers/ high demand for my products or services
P21__3                                   | P21:Increased access to finance/ available credit
P21__8                                   | Better weather/ climatic conditions
P22__1                                   | P22. Reason(s) for worsened:Increased/ high cost of compliance
P22__3                                   | P22. Reason(s) for worsened:Reduced access to finance/ credit
P22__4                                   | P22. Reason(s) for worsened:Increased/ high competition
P22__5                                   | P22. Reason(s) for worsened:Increased/high cost of supplies
P22__6                                   | P22. Reason(s) for worsened:Insecurity
P22__7                                   | P22. Reason(s) for worsened:Poor infrastructure
P22__8                                   | P22. Reason(s) for worsened:High debt
P22__10                                  | Bad weather/ climatic conditions
P22__15                                  | Owner's health issues
P22__16                                  | Pests & Diseases
P22__96                                  | P22. Reason(s) for worsened:Others Specify
P22__98                                  | P22. Reason(s) for worsened:Don't know
P22__99                                  | P22. Reason(s) for worsened:Refused to Answer
Q1i                                      | Q1i. Unit of measure
Q2__4                                    | Lease/Rent (you don't own)
Q2__98                                   | Don’t know (DO NOT READ OUT)
Q2__99                                   | "Refused to Answer (DO NOT READ OUT)
Q6__1                                    | Q6. County of farmland:Mombasa
Q6__2                                    | Q6. County of farmland:Kwale
Q6__3                                    | Q6. County of farmland:Kilifi
Q6__4                                    | Q6. County of farmland:Tana River
Q6__5                                    | Q6. County of farmland:Lamu
Q6__6                                    | Q6. County of farmland:Taita-Taveta
Q6__7                                    | Q6. County of farmland:Garissa
Q6__8                                    | Q6. County of farmland:Wajir
Q6__9                                    | Q6. County of farmland:Mandera
Q6__10                                   | Q6. County of farmland:Marsabit
Q6__11                                   | Q6. County of farmland:Isiolo
Q6__12                                   | Q6. County of farmland:Meru
Q6__13                                   | Q6. County of farmland:Tharaka-Nithi
Q6__14                                   | Q6. County of farmland:Embu
Q6__15                                   | Q6. County of farmland:Kitui
Q6__16                                   | Q6. County of farmland:Machakos

In [56]:
for var in ["hhWeight", "indWeight"]:
    print("\n" + "=" * 60)
    print(var)
    print(df[var].describe())
    print("Missing:", df[var].isna().sum())
    print("Zero:", (df[var] == 0).sum())
    print("Negative:", (df[var] < 0).sum())
    print("Unique:", df[var].nunique())

============================================================
hhWeight
count    20871.000000
mean       683.165156
std        594.646933
min         39.615500
25%        350.589934
50%        556.911105
75%        801.331391
max      14660.199401
Name: hhWeight, dtype: float64
Missing: 0
Zero: 0
Negative: 0
Unique: 1837

============================================================
indWeight
count    20871.000000
mean      1463.903606
std       1740.023128
min         20.093548
25%        552.523560
50%        994.181702
75%       1773.134888
max      73513.226562
Name: indWeight, dtype: float64
Missing: 0
Zero: 0
Negative: 0
Unique: 14577

In [57]:
print("Number of households/records:", len(df))
print("Unique clusters:", df["A07"].nunique())

print("\nObservations per cluster:")
print(df["A07"].value_counts().describe())

Number of households/records: 20871
Unique clusters: 1849

Observations per cluster:
count    1849.000000
mean       11.287723
std         2.530007
min         1.000000
25%        10.000000
50%        12.000000
75%        13.000000
max        15.000000
Name: count, dtype: float64

In [58]:
target = "defaulted"

print(df[target].value_counts())
print(df[target].value_counts(normalize=True))

defaulted
0    13920
1     6951
Name: count, dtype: int64
defaulted
0    0.666954
1    0.333046
Name: proportion, dtype: float64

In [59]:
# Look at variables related to major predictor domains

domains = {
    "Demographics": ["Age", "Sex", "Education"],
    "Savings": ["Savings_usage", "Savings_formal", "Savings_informal", "tot_savings"],
    "Loans": ["Loan_usage", "Loan_formal", "Loan_informal"],
    "Digital finance": [
        "Digital_credit_usage_fnl",
        "formal_digital_loan_fnl",
        "mobile_money_access_2"
    ],
    "Insurance": [
        "All_Insurance_excluding_NHIF",
        "All_Insurance_including_NHIF"
    ],
    "Pension": [
        "Pension_usage",
        "Pension_Usage_without_NSSF"
    ],
    "Financial health": [
        "new_fh_score",
        "nfh_categories"
    ],
    "Shocks": [
        "experienced_shock"
    ]
}

for domain, variables in domains.items():
    print(f"\n--- {domain} ---")
    for var in variables:
        if var in df.columns:
            print(var)

--- Demographics ---
Age
Sex
Education

--- Savings ---
Savings_usage
Savings_formal
Savings_informal
tot_savings

--- Loans ---
Loan_usage
Loan_formal
Loan_informal

--- Digital finance ---
Digital_credit_usage_fnl
formal_digital_loan_fnl
mobile_money_access_2

--- Insurance ---
All_Insurance_excluding_NHIF
All_Insurance_including_NHIF

--- Pension ---
Pension_usage
Pension_Usage_without_NSSF

--- Financial health ---
new_fh_score
nfh_categories

--- Shocks ---
experienced_shock

In [60]:
candidate_vars = [
    "Age",
    "Sex",
    "Education",
    "Savings_usage",
    "Savings_formal",
    "Savings_informal",
    "tot_savings",
    "Loan_usage",
    "Loan_formal",
    "Loan_informal",
    "Digital_credit_usage_fnl",
    "formal_digital_loan_fnl",
    "mobile_money_access_2",
    "All_Insurance_excluding_NHIF",
    "All_Insurance_including_NHIF",
    "Pension_usage",
    "Pension_Usage_without_NSSF",
    "new_fh_score",
    "nfh_categories",
    "experienced_shock"
]

summary = pd.DataFrame({
    "variable": candidate_vars,
    "dtype": [df[v].dtype for v in candidate_vars],
    "missing": [df[v].isna().sum() for v in candidate_vars],
    "unique": [df[v].nunique(dropna=True) for v in candidate_vars]
})

summary

                        variable    dtype  missing  unique
0                            Age    int64        0       6
1                            Sex    int64        0       2
2                      Education    int64        0       5
3                  Savings_usage    int64        0       2
4                 Savings_formal    int64        0       2
5               Savings_informal    int64        0       2
6                    tot_savings    int64        0       2
7                     Loan_usage    int64        0       2
8                    Loan_formal    int64        0       2
9                  Loan_informal    int64        0       2
10      Digital_credit_usage_fnl    int64        0       2
11       formal_digital_loan_fnl    int64        0       2
12         mobile_money_access_2    int64        0       2
13  All_Insurance_excluding_NHIF    int64        0       2
14  All_Insurance_including_NHIF    int64        0       2
15                 Pension_usage    int64        0       2
16    Pension_Usage_without_NSSF    int64        0       2
17                  new_fh_score  float64        0      10
18                nfh_categories    int64        0       3
19             experienced_shock    int64        0       2

In [61]:
variables_to_inspect = [
    "Age",
    "Sex",
    "Education",
    "Savings_usage",
    "Savings_formal",
    "Savings_informal",
    "tot_savings",
    "Loan_usage",
    "Loan_formal",
    "Loan_informal",
    "Digital_credit_usage_fnl",
    "formal_digital_loan_fnl",
    "mobile_money_access_2",
    "All_Insurance_excluding_NHIF",
    "All_Insurance_including_NHIF",
    "Pension_usage",
    "Pension_Usage_without_NSSF",
    "new_fh_score",
    "nfh_categories",
    "experienced_shock"
]

for var in variables_to_inspect:
    print(f"\n{'='*60}")
    print(var)
    print("Label:", meta.column_names_to_labels.get(var))
    print("Values:")
    print(df[var].value_counts(dropna=False).sort_index())

============================================================
Age
Label: Agegroup of Selected Individual
Values:
Age
1    1121
2    3997
3    5361
4    3942
5    2545
6    3905
Name: count, dtype: int64

============================================================
Sex
Label: Sex of Selected Individual
Values:
Sex
1     8545
2    12326
Name: count, dtype: int64

============================================================
Education
Label: Education Level of Respodent
Values:
Education
1    3078
2    7684
3    7345
4    2755
5       9
Name: count, dtype: int64

============================================================
Savings_usage
Label: Savings Usage overall
Values:
Savings_usage
0     7628
1    13243
Name: count, dtype: int64

============================================================
Savings_formal
Label: Savings usage formal
Values:
Savings_formal
0    11635
1     9236
Name: count, dtype: int64

============================================================
Savings_informal
Label: Savings usage informal
Values:
Savings_informal
0    16031
1     4840
Name: count, dtype: int64

============================================================
tot_savings
Label: Savings Category
Values:
tot_savings
0     7628
1    13243
Name: count, dtype: int64

============================================================
Loan_usage
Label: Loan usage overall
Values:
Loan_usage
0     8096
1    12775
Name: count, dtype: int64

============================================================
Loan_formal
Label: Loan usage formal
Values:
Loan_formal
0    12340
1     8531
Name: count, dtype: int64

============================================================
Loan_informal
Label: Loan usage informal
Values:
Loan_informal
0    12604
1     8267
Name: count, dtype: int64

============================================================
Digital_credit_usage_fnl
Label: Digital_credit_hustlerfund_mobile_money_provider_m_banking_& Digital_MFIs
Values:
Digital_credit_usage_fnl
0    13620
1     7251
Name: count, dtype: int64

============================================================
formal_digital_loan_fnl
Label: formal_digital_loan_fnl
Values:
formal_digital_loan_fnl
0    13620
1     7251
Name: count, dtype: int64

============================================================
mobile_money_access_2
Label: Have ever accessed mobile money_including loan from provider
Values:
mobile_money_access_2
0     2956
1    17915
Name: count, dtype: int64

============================================================
All_Insurance_excluding_NHIF
Label: Insurance_usage
Values:
All_Insurance_excluding_NHIF
0    19817
1     1054
Name: count, dtype: int64

============================================================
All_Insurance_including_NHIF
Label: Insurance_usage2
Values:
All_Insurance_including_NHIF
0    16854
1     4017
Name: count, dtype: int64

============================================================
Pension_usage
Label: pension_usage
Values:
Pension_usage
0    18966
1     1905
Name: count, dtype: int64

============================================================
Pension_Usage_without_NSSF
Label: pension_usage_2
Values:
Pension_Usage_without_NSSF
0    20541
1      330
Name: count, dtype: int64

============================================================
new_fh_score
Label: New financial health score
Values:
new_fh_score
0.000000    1283
0.111111    2244
0.222222    2537
0.333333    4276
0.444444    2499
0.555556    2528
0.666667    3161
0.777778     504
0.888889     720
1.000000    1119
Name: count, dtype: int64

============================================================
nfh_categories
Label: New financial health categories
Values:
nfh_categories
1    5504
2    9303
3    6064
Name: count, dtype: int64

============================================================
experienced_shock
Label: experienced shock
Values:
experienced_shock
0    11785
1     9086
Name: count, dtype: int64

In [62]:
keywords = [
    "income",
    "employment",
    "employed",
    "occupation",
    "business",
    "household",
    "depend",
    "financial literacy",
    "literacy",
    "debt",
    "credit",
    "loan",
    "saving",
    "shock",
    "financial access",
    "access"
]

for keyword in keywords:
    print(f"\n{'='*70}")
    print(f"KEYWORD: {keyword.upper()}")

    matches = []

    for var, label in meta.column_names_to_labels.items():
        if label and keyword.lower() in str(label).lower():
            matches.append((var, label))

    for var, label in matches:
        print(f"{var:35} | {label}")

======================================================================
KEYWORD: INCOME
B3Ai                                | B3Ai.  Income Sources- Other
D2__1                               | D2_1: I lost my job/income
D3__1                               | D3_1: Don't have a regular income/job/too expensive/can't afford
E3__9                               | E3_9: Income is low and unab
E4__1                               | E4. :Don't have money/income/job; Can't afford loans
E5__1                               | E5. :I lost my job/income
F2__1                               | F2_1: No regular income/job or unable to save
F3__1                               | F3_1: Lost job/income
F2B__1                              | F2B_1: Lost job/income
F2C__1                              | F2C_1: No money/job/income
H2__1                               | H2__1:I don't have a regular income/ I can't afford/ I don't havemoney to save
K2i__1                              | K2i__1:Don't have money/income/job/too expensive
K2ii__1                             | K2ii__1:I lost my job/income too expensive
M2i__1                              | M2i__1:Don't have money/income/job/can't afford to save
M2ii__1                             | M2ii__1:I lost my job/income/too expensive
N2i__1                              | N2i__1:Don't have money/income/job/can't afford to contribute
N2ii__1                             | N2ii__1:I lost my job/income
P7a__1                              | P7a.Income from business reinvested
P7a__2                              | P7a.Income from other business
P7a__3                              | P7a.Income from salary invested
P7a__4                              | P7a.Income from agriculture
Q1                                  | Q1. Agriculture Income
Q7b                                 | Q7b. Crops/Livestock which brought you the most income
Q21                                 | Q21. main decisions maker spending income
R2A__5                              | R2A. Death of main income earner/family member
R2A__7                              | R2A. Loss of a job or a source of income or a wage cut
R2A__12                             | R2A__12:Loss of income or major financial expenses due to taking on care for som
U21__2                              | U21__2 Used regular income to buy materials whenever possible
Investment_usage_fnl                | Investment usage fnl incl chumz and received income in last 12 months
Reason_for_saving_my_paypoint       | Where i receive my income

======================================================================
KEYWORD: EMPLOYMENT
B3G                                 | B3G. Private or Public Sector Employment
C1_41                               | C1-41. Employment/ Occupation pension scheme, NOT NSSF
S5__3                               | Employment and career related activities (searching for jobs/vacancies etc.)
nC1_41                              | RECODE of C1_41 (C1-41. Employment/ Occupation pension scheme, NOT NSSF)

======================================================================
KEYWORD: EMPLOYED
B3A__2                              | B3A. Employed/regular employees
B3A__4                              | B3A. Running own business/Self employed
B3F1                                | B3F1.    Where you are employed

======================================================================
KEYWORD: OCCUPATION
C1_41                               | C1-41. Employment/ Occupation pension scheme, NOT NSSF
nC1_41                              | RECODE of C1_41 (C1-41. Employment/ Occupation pension scheme, NOT NSSF)

======================================================================
KEYWORD: BUSINESS
B1L__4                              | B1L__4:Machinery, vehicles, equipment, tools, building for business/self-employm
B3A__4                              | B3A. Running own business/Self employed
B3D__3_1                            | B3D__3.1: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__5_1                            | B3D__5.1: B3D. Received Payments:Merchant/business paybill/till number
B3D__3_2                            | B3D__3.2: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__5_2                            | B3D__5.2: B3D. Received Payments:Merchant/business paybill/till number
B3D__3_3                            | B3D__3.3: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__5_3                            | B3D__5.3: B3D. Received Payments:Merchant/business paybill/till number
B3D__3_4                            | B3D__3.4: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__5_4                            | B3D__5.4: B3D. Received Payments:Merchant/business paybill/till number
B3D__3_5                            | B3D__3.5: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__5_5                            | B3D__5.5: B3D. Received Payments:Merchant/business paybill/till number
B3D__3_6                            | B3D__3.6: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__5_6                            | B3D__5.6: B3D. Received Payments:Merchant/business paybill/till number
B3D__3_7                            | B3D__3.7: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__5_7                            | B3D__5.7: B3D. Received Payments:Merchant/business paybill/till number
B3D__3_8                            | B3D__3.8: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__5_8                            | B3D__5.8: B3D. Received Payments:Merchant/business paybill/till number
B3D__3_9                            | B3D__3.9: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bia
B3D__5_9                            | B3D__5.9: B3D. Received Payments:Merchant/business paybill/till number
B3D__3_10                           | B3D__3.10: B3D. Received Payments:Mobile money business wallet (e.g. Pochi la bi
B3D__5_10                           | B3D__5.10: B3D. Received Payments:Merchant/business paybill/till number
C1_13a                              | C1_13a. Personal loan/business loan from a commercial bank
C1_13b                              | C1_13b. Personal loan/business loan from a microfinance bank
E3__4                               | E3_4: Lack of business propo
E2D__6                              | Started a business/worked more hours
E3A__10                             | E3A: Acted as Guarantor:Hustler Fund group/business loan
G1A1__3                             | G1A1__3:Mobile money business wallet (e.g. Pochi la biashara)
G1A1__5                             | G1A1:  Merchant/business paybill/till number
G1A2__3                             | G1A2__3:Mobile money business wallet (e.g. Pochi la biashara)
G1A2__5                             | G1A2:  Merchant/business paybill/till number
G1A3__3                             | G1A3__3:Mobile money business wallt (e.g. Pochi la biashara)
G1A3__5                             | G1A3:  Merchant/business paybill/till number
G1A4__3                             | G1A4__3:Mobile money business wallet (e.g. Pochi la biashara)
G1A4__5                             | G1A4:  Merchant/business paybill/till number
G1A5__3                             | G1A5__3:Mobile money business wallet (e.g. Pochi la biashara)
G1A5__5                             | G1A5:  Merchant/business paybill/till number
G1A6__3                             | G1A6__3:Mobile money business wallet (e.g. Pochi la biashara)
G1A6__5                             | G1A6:  Merchant/business paybill/till number
G1A7__3                             | G1A7__3:Mobile money business wallet (e.g. Pochi la biashara)
G1A7__5                             | G1A7:  Merchant/business paybill/till number
G1A8__3                             | G1A8__3:Mobile money business wallet (e.g. Pochi la biashara)
G1A8__5                             | G1A8:  Merchant/business paybill/till number
G1A9__3                             | G1A9__3:Mobile money business wallet (e.g. Pochi la biashara)
G1A9__5                             | G1A9:  Merchant/business paybill/till number
I1a__70                             | Business Cash Advance Limited
O5__7                               | O5_7 Support or start farm or business
O5__10                              | O5_10 To start/support the business
P1i                                 | P1i. Business operation status
P1a                                 | P1a.  How many businesses do you currently own or share with other individuals:
P1b                                 | P1b.How many businesses do you currently own or share with other individuals: Jo
P1c                                 | P1c. How many businesses do you currently own or share with other individuals: J
P1_1i                               | P1_1i. Other resons for closed business
P2ii                                | P2ii. Where does your MAIN business from
P5__5                               | P5:Difficulty paying business expenses (rent, utilities, labour)
P5__8                               | P5. Uncertainity regarding business premises
P5__17                              | Poor Infrastructure/ Business environment e.g Roads, Electricity
P5a__1                              | P5a. High cost of supplies for your business due
P5a__7                              | P5a. Increased tax for my business
P6ii                                | P6ii You said you used a saving, for the startup cash / money for your business,
P7a__1                              | P7a.Income from business reinvested
P7a__2                              | P7a.Income from other business
P9                                  | P9. Reason Loan Business
P9i                                 | P9. Reason Loan Business - other
P12__1                              | P12. Have till/paybill number in the business name
P12__3                              | P12. Bank account in your business name
P12__6                              | P12. Have a single/ unified Business Permit
P12__7                              | P12. Membership to a business association
P15i__3                             | P15iMobile money business wallet (e.g. Pochi la biashara)
P15i__5                             | P15i. Merchant/business paybill/till number
P15ii__3                            | P15ii__3:Mobile money business wallet (e.g. Pochi la biashara)
P15ii__5                            | P15ii. ways received payments:Merchant/business paybill/till number
P20                                 | P20.  Business performance
P21__9                              | Business Diversification
P22__11                             | Harsh business environment
Q15a__3                             | Q15a. Mobile money business wallet (e.g. Pochi la biashara
Q15a__5                             | Q15a. Merchant/business paybill/till number
R2A__6                              | R2A__6:Loss or damage due totheft(e.g property, assets, business etc
R2C__16                             | Reinvested business profits
U19b__10                            | U19b. Own Land:Business/ Commercial
saving_for_business                 | Saving for business
Start_new_business_credit           | To start new business
Expand_business_credit              | To expand / invest in machinery, equipment for my business
Working_capital_business_credit     | For working capital for my business
Premise_land_for_business_credit    | To invest in the premise or land for my business
Another_persons_business_credit     | To invest in another person's business
nC1_13a                             | RECODE of C1_13a (C1_13a. Personal loan/business loan from a commercial bank)
nC1_13b                             | RECODE of C1_13b (C1_13b. Personal loan/business loan from a microfinance bank)

======================================================================
KEYWORD: HOUSEHOLD
A14ii                               | Sex of a household member
A14iii                              | Relationship of the household member to the head of household
A14_slept                           | slept in the household last night
RESPONDENT                          | A14vii. Select Name of the respondent who provided Household members information
NHM                                 | Number of household members.
A22i                                | A22i) Number of children in the household
A23                                 | A23 Household chronic disease status
B1Di                                | B1Di: In the past 1 month, did you or any household member have to eat fewer mea
E2B                                 | E2B: In the past 12 months, did someone in your household repay or help to repay
E3C                                 | E3C:  Pay household member loan
E3D__1                              | E3D: Who in your household did you repay a loan for?:Spouse/ partner
E3D__2                              | E3D: Who in your household did you repay a loan for?:Mother
E3D__3                              | E3D: Who in your household did you repay a loan for?:Father
E3D__4                              | E3D: Who in your household did you repay a loan for?:Daughter
E3D__5                              | E3D: Who in your household did you repay a loan for?:Son
E3D__6                              | E3D: Who in your household did you repay a loan for?:Other relative(s)
E3D__7                              | E3D: Who in your household did you repay a loan for?:Non relative(s)
E3D__99                             | E3D: Who in your household did you repay a loan for?:Refused to Answer
O3__9                               | O3_9 Friend/Family within kenya outside the household
O3__10                              | O3_10 Household members
O5__3                               | O5_3 Education expenses for self or others within the household
O5__4                               | O5_4 Education expenses for others outside my household
U5                                  | U5. How many dwelling units does this household occupy
U24_9Automation                     | Monthly Expenditure on household appliances and furnishes
HHid                                | Household id Generated
Edu_within_household_credit         | For education for self or others within household
Edu_outside_household_credit        | For education for others outside household
Day2day_household_needs_credit      | To meet daytoday household needs
Acquire_household_goods_credit      | To acquire household goods

======================================================================
KEYWORD: DEPEND

======================================================================
KEYWORD: FINANCIAL LITERACY
fl_score                            | Financial Literacy Score
Financial_literacy_index_fnl        | Financial literacy index

======================================================================
KEYWORD: LITERACY
fl_score                            | Financial Literacy Score
Financial_literacy_index_fnl        | Financial literacy index

======================================================================
KEYWORD: DEBT
E3__5                               | E3_5: Still had debt to pay
E5__7                               | E5. :Unethical debt recovery/harassment
M2ii__7                             | M2ii__7:Unethical debt recovery/harassment
N2ii__6                             | N2ii__6:Unethical debt recovery/harassment
O5__12                              | O5_12 To repay a loan/ debt
P1_1__12                            | P1_1. Over indebtedness
P22__8                              | P22. Reason(s) for worsened:High debt
Q24__8                              | Q24. High debt
defaulted                           | Defaulted on Loans_Debt
nfhi_13                             | No debt stress past 3 months
managedebt_perception               | Perception on managingexisting debts
Pay_off_debts_credit                | To pay off debts
Repay_debts_someone_else_credit     | To repay debts for someone else who was unable to repay such as family, friend
For_old_age_credit                  | To repay debts for someone else who was unable to repay such as family, friend

======================================================================
KEYWORD: CREDIT
B1Hi                                | B1Hi. Source of loans/credit
B3D__8_1                            | B3D__8.1: B3D. Received Payments:Credit cards / debit cards
B3D__8_2                            | B3D__8.2: B3D. Received Payments:Credit cards / debit cards
B3D__8_3                            | B3D__8.3: B3D. Received Payments:Credit cards / debit cards
B3D__8_4                            | B3D__8.4: B3D. Received Payments:Credit cards / debit cards
B3D__8_5                            | B3D__8.5: B3D. Received Payments:Credit cards / debit cards
B3D__8_6                            | B3D__8.6: B3D. Received Payments:Credit cards / debit cards
B3D__8_7                            | B3D__8.7: B3D. Received Payments:Credit cards / debit cards
B3D__8_8                            | B3D__8.8: B3D. Received Payments:Credit cards / debit cards
B3D__8_9                            | B3D__8.9: B3D. Received Payments:Credit cards / debit cards
B3D__8_10                           | B3D__8.10: B3D. Received Payments:Credit cards / debit cards
C1_4                                | C1-4. Savings at a Sacco / Savings and Credit Cooperative organisation
C1_14                               | C1_14. Credit card
C1_27                               | C1-27. Taking goods and services on credit from a shopkeeper
C1_28                               | C1_28:Loan / credits from buyer of your harvest / supplier of agricultural input
E2__6                               | E2_6: Credit-Only institution  (e
E3__7                               | E3_7: Bad credit history
E3__8                               | E3_8: No credit history
E4__9                               | do not qualify/Bad credit history
E1iD                                | E1iD: Number of creditcard loans past 12 months
E1iiiD                              | E1iiiD: Reason for taking creditcard loan product
E1iiiD_Other                        | E1iiiD: Reason for taking creditcard loan; Others
E1vD                                | E1vD: Frequency of creditcard loan repayments
E1vD_Other                          | E1vD: Frequency of creditcard loan repayments; Others
E1viD                               | E1viD: Channels used for repaying creditcard loan
E1viD_Other                         | E1viD: Channels used for repaying creditcard loan; Others
E1viiD                              | E1viiD: Amount of creditcard loan borrowed
E1viiiD                             | E1viiiD: Amount of creditcard loan approved
E1ixD                               | E1ixD: Date of borrowing the creditcard loan
E1xD                                | E1xD: Creditcard loan repayment due date
E1iQ                                | E1iQ: Number of times you purchased goods on credit from the shopkeeper in the p
E1iiiQ                              | E1iiiQ: Reason for taking goods on credit from Shopkeeper
E1iiiQ_Other                        | E1iiiQ: Reason for taking goods on credit from Shopkeeper; Others
E1vQ                                | E1vQ: Repayment frequency for goods purchased on credit from the shopkeeper
E1vQ_Other                          | E1vQ: Repayment frequency for goods purchased on credit from the shopkeeper; Oth
E1viQ                               | E1viQ: Channels used to repay for goods purchased on credit from the shopkeeper
E1viQ_Other                         | E1viQ: Channels used to repay for goods purchased on credit from the shopkeeper;
E1viiQ                              | E1viiQ: Amount of goods requested for purchase on credit from the shopkeeper

In [63]:
keywords = {
    "Income": ["income", "earnings"],
    "Employment": ["employment", "employed", "occupation", "job"],
    "Household": ["household size", "household members", "depend"],
    "Business": ["business owner", "business activity", "enterprise"],
    "Debt": ["debt", "outstanding"],
    "Financial literacy": ["financial literacy"],
    "Financial access": ["financial access"],
    "Shock": ["shock"]
}

for category, terms in keywords.items():
    matches = []

    for var, label in meta.column_names_to_labels.items():
        if label:
            label_lower = str(label).lower()
            if any(term.lower() in label_lower for term in terms):
                matches.append((var, label))

    print(f"\n{category}: {len(matches)} matches")
    for var, label in matches[:10]:
        print(f"  {var} → {label}")

Income: 30 matches
  B3Ai → B3Ai.  Income Sources- Other
  D2__1 → D2_1: I lost my job/income
  D3__1 → D3_1: Don't have a regular income/job/too expensive/can't afford
  E3__9 → E3_9: Income is low and unab
  E4__1 → E4. :Don't have money/income/job; Can't afford loans
  E5__1 → E5. :I lost my job/income
  F2__1 → F2_1: No regular income/job or unable to save
  F3__1 → F3_1: Lost job/income
  F2B__1 → F2B_1: Lost job/income
  F2C__1 → F2C_1: No money/job/income

Employment: 31 matches
  B3A__2 → B3A. Employed/regular employees
  B3A__4 → B3A. Running own business/Self employed
  B3F1 → B3F1.    Where you are employed
  B3G → B3G. Private or Public Sector Employment
  C1_41 → C1-41. Employment/ Occupation pension scheme, NOT NSSF
  D1Ai__1 → D1Ai_1: Loss of Job
  D1B__1 → D1B_1: Lack of a regular job/can't afford a pension
  D2__1 → D2_1: I lost my job/income
  D3__1 → D3_1: Don't have a regular income/job/too expensive/can't afford
  E4__1 → E4. :Don't have money/income/job; Can't afford loans

Household: 3 matches
  RESPONDENT → A14vii. Select Name of the respondent who provided Household members information
  NHM → Number of household members.
  O3__10 → O3_10 Household members

Business: 3 matches
  E3A__8 → E3A: Acted as Guarantor:Government e.g. Uwezo, Women Enterprise Fund, HELB
  E3B__8 → E3B: Lost money/Asset as Guarantor:Government e.g. Uwezo, Women Enterprise Fund,
  I1a__8 → Colkos Enterprises Limited

Debt: 53 matches
  E3__5 → E3_5: Still had debt to pay
  E5__7 → E5. :Unethical debt recovery/harassment
  E1iiA → E1iiA: Number of Outstanding bank Loans
  E1xiA → E1xiA: Outstanding bank loan amount
  E1iiB → E1iiB: Number of Outstanding microfinance bank loans
  E1xiB → E1xiB: Outstanding microfinance bank loan amount
  E1iiC → E1iiC: Number of Outstanding bank overdraft loans
  E1xiC → E1xiC: Outstanding bank overdraft loan amount
  E1iiE → E1iiE: Number of Outstanding mobile banking loans
  E1xiE → E1xiE: Outstanding mobile banking loan amount

Financial literacy: 2 matches
  fl_score → Financial Literacy Score
  Financial_literacy_index_fnl → Financial literacy index

Financial access: 0 matches

Shock: 5 matches
  R2B → R2B. Main Shock
  R2F → R2F. Potential product for climate shock
  R2Fi → R2Fi. Potential product for climate shock - Other
  experienced_shock → experienced shock
  nfhi_21 → Protection against shocks

In [64]:
new_candidates = [
    "NHM",
    "B3A__2",
    "B3A__4",
    "B3F1",
    "B3G",
    "fl_score",
    "Financial_literacy_index_fnl"
]

for var in new_candidates:
    print(f"\n{'='*60}")
    print(var)
    print("Label:", meta.column_names_to_labels.get(var))
    print(df[var].value_counts(dropna=False).sort_index())

============================================================
NHM
Label: Number of household members.
NHM
1     3425
2     2414
3     3013
4     3417
5     2936
6     2127
7     1423
8      946
9      452
10     360
11     164
12      92
13      35
14      27
15      21
16       6
17       2
18       5
19       4
20       2
Name: count, dtype: int64

============================================================
B3A__2
Label: B3A. Employed/regular employees
B3A__2
0    18347
1     2524
Name: count, dtype: int64

============================================================
B3A__4
Label: B3A. Running own business/Self employed
B3A__4
0    16914
1     3957
Name: count, dtype: int64

============================================================
B3F1
Label: B3F1.    Where you are employed
B3F1
                                                              12132
##N/A##                                                           5
2000                                                              1
3000                                                              1
5 star hotel hosting both local and international tourists        1
                                                              ...
works seasonally as a laundry personnel                           1
works with the county government                                  1
world marketing                                                   1
writing magazines                                                 1
youth church leader                                               1
Name: count, Length: 4933, dtype: int64

============================================================
B3G
Label: B3G. Private or Public Sector Employment
B3G
1       1635
2        883
98         3
99         3
NaN    18347
Name: count, dtype: int64

============================================================
fl_score
Label: Financial Literacy Score
fl_score
0     713
1    3493
2    8580
3    8085
Name: count, dtype: int64

============================================================
Financial_literacy_index_fnl
Label: Financial literacy index
Financial_literacy_index_fnl
1    8085
2    8580
3    3493
4     713
Name: count, dtype: int64

In [65]:
candidate_vars = [
    "Age",
    "Sex",
    "Education",
    "NHM",
    "B3A__2",
    "B3A__4",
    "Savings_usage",
    "Savings_formal",
    "Savings_informal",
    "Loan_usage",
    "Loan_formal",
    "Loan_informal",
    "Digital_credit_usage_fnl",
    "mobile_money_access_2",
    "All_Insurance_excluding_NHIF",
    "All_Insurance_including_NHIF",
    "Pension_usage",
    "Pension_Usage_without_NSSF",
    "fl_score",
    "experienced_shock"
]

results = []

for var in candidate_vars:
    grouped = df.groupby(var)["defaulted"].agg(["mean", "count"])

    results.append({
        "variable": var,
        "groups": df[var].nunique(),
        "min_default_rate": grouped["mean"].min(),
        "max_default_rate": grouped["mean"].max()
    })

pd.DataFrame(results).sort_values("max_default_rate", ascending=False)

                        variable  groups  min_default_rate  max_default_rate
12      Digital_credit_usage_fnl       2          0.153231          0.670804
10                   Loan_formal       2          0.140681          0.611300
9                     Loan_usage       2          0.008029          0.539022
11                 Loan_informal       2          0.202396          0.532237
3                            NHM      20          0.000000          0.500000
8               Savings_informal       2          0.303724          0.430165
0                            Age       6          0.056200          0.419698
5                         B3A__4       2          0.315656          0.407379
19             experienced_shock       2          0.277896          0.404578
7                 Savings_formal       2          0.284057          0.394760
2                      Education       5          0.203379          0.388022
18                      fl_score       4          0.182328          0.380829
6                  Savings_usage       2          0.262454          0.373707
13         mobile_money_access_2       2          0.127199          0.367011
4                         B3A__2       2          0.328773          0.364105
16                 Pension_usage       2          0.332068          0.342782
15  All_Insurance_including_NHIF       2          0.331079          0.341299
1                            Sex       2          0.330602          0.336571
14  All_Insurance_excluding_NHIF       2          0.304554          0.334561
17    Pension_Usage_without_NSSF       2          0.324242          0.333187

In [66]:
pairs = [
    ("Savings_usage", "tot_savings"),
    ("Digital_credit_usage_fnl", "formal_digital_loan_fnl"),
    ("All_Insurance_excluding_NHIF", "All_Insurance_including_NHIF"),
    ("Pension_usage", "Pension_Usage_without_NSSF"),
]

for a, b in pairs:
    print(f"{a} vs {b}:")
    print("  Identical:", (df[a] == df[b]).all())
    print("  Agreement:", (df[a] == df[b]).mean())

Savings_usage vs tot_savings:
  Identical: True
  Agreement: 1.0
Digital_credit_usage_fnl vs formal_digital_loan_fnl:
  Identical: True
  Agreement: 1.0
All_Insurance_excluding_NHIF vs All_Insurance_including_NHIF:
  Identical: False
  Agreement: 0.8580326769201284
Pension_usage vs Pension_Usage_without_NSSF:
  Identical: False
  Agreement: 0.9245364381198793

In [67]:
for var in [
    "All_Insurance_excluding_NHIF",
    "All_Insurance_including_NHIF",
    "Pension_usage",
    "Pension_Usage_without_NSSF"
]:
    print(f"\n{var}")
    print("Label:", meta.column_names_to_labels.get(var))
    print("Value labels:", meta.variable_value_labels.get(var))

All_Insurance_excluding_NHIF
Label: Insurance_usage
Value labels: {0: 'Non-usage', 1: 'Usage'}

All_Insurance_including_NHIF
Label: Insurance_usage2
Value labels: {0: 'Non-usage', 1: 'Usage'}

Pension_usage
Label: pension_usage
Value labels: {0: 'Non-usage', 1: 'Usage'}

Pension_Usage_without_NSSF
Label: pension_usage_2
Value labels: {0: 'Non-usage', 1: 'Usage'}